New persondetails view
jellyfin-archive/jellyfin-roku-legacy pull request #1004
Opened 2023-02-01 19:28 UTC by sevenrats

**Changes**

muck about with the layout to make better use of space.
increase text size in dialog
always allow dialog selection even if the text is not ellipsized
set focus to description by default instead of fav menu, assuming that the use pattern will be to inspect the description before favoriting.

react to missing birthdate info by increasing Name size to elliminate deadspace. 

- [x] unbreak the overview dialog

2023-02-06 03:08 UTC, candry7731 approved these changes
Like the layout with moving the favorite button to the top. Also styling the person details makes this a great addition. 

it would be great that if the person has no info we show "no info" or something like that instead of a blank box... something like below.

![image](https://user-images.githubusercontent.com/83685828/216874771-cee6b07d-632c-4bb9-819f-95263ffc6e1c.png)

2023-02-06 05:59 UTC, sevenrats commented
I agree.

2023-02-07 19:17 UTC, candry7731 commented
Much better with the "no details" options. 

I am seeing the vert align when clicking on a show then viewing the extra's info however it's missing when clicking from a person then seeing there extra's info... 
![image](https://user-images.githubusercontent.com/83685828/217342898-998bc472-7bfb-43a5-9ed3-2939bfd8b242.png)

I'm also getting this error
![image](https://user-images.githubusercontent.com/83685828/217342787-63bbd4e3-106a-4569-8f2b-4e7b9c4a11e6.png)

2023-02-07 19:53 UTC, sevenrats commented
yeah the code is filthy dirty right now. The main things I did were change the font size if birthdate info is missing, and move the layout around when we have it to try and maximize the balance with the submit button.  I fixed the slider, I think.

2023-02-07 19:59 UTC, candry7731 commented
the slider spacing looks good until you go in from a person details screen then click into the slider and the margins revert to being 0 margin on the left side and a hug gap on the right....

2023-02-11 01:08 UTC, 1hitsong requested changes

2023-02-11 01:08 UTC, 1hitsong commented on components/PersonDetails.brs
> +        print "key down"
Debug code

2023-02-11 01:08 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <source>Biographical information for this person is not currently available.</source>
Same line of text already added on line 1024.

2023-02-11 18:00 UTC, 1hitsong approved these changes

2023-02-11 18:00 UTC, 1hitsong commented
To be merged 2/12 unless issue arises.

2023-02-12 12:02 UTC, merged