Create Setting for Next Up button duration
jellyfin-archive/jellyfin-roku-legacy pull request #1013
Opened 2023-02-03 19:02 UTC by candry7731

Creates a setting for users to customize when the next up button appears. 

The default is 30 seconds

To disable the button set to 0

2023-02-03 19:10 UTC, candry7731 commented
Adds #942 functionality

2023-02-04 01:45 UTC, 1hitsong requested changes
Also, new setting title and descriptions need to be added to translations file.

2023-02-04 01:45 UTC, 1hitsong commented on settings/settings.json
> -                        "default": "365"
Why are we modifying the default value for maxdaysnextup?

2023-02-04 01:45 UTC, 1hitsong commented on settings/settings.json
> +                "title": "Change next up button show duration",
```suggestion
                "title": "Next Episode Button Time",
```

2023-02-04 01:45 UTC, 1hitsong commented on settings/settings.json
> +                "description": "Default is 30 seconds, you can set to 0 to diable the button or set new time in seconds to display the button",
```suggestion
                "description": "Set how many seconds before the end of an episode the Next Episode button should appear. Set to 0 to disable.",
```

2023-02-04 15:32 UTC, sevenrats commented on settings/settings.json
> +                "title": "Change next up button show duration",
Please insert new settings in alphabetical order. General Menu, Menus, Settings

2023-02-05 02:25 UTC, candry7731 commented on settings/settings.json
> +                "title": "Change next up button show duration",
Done

2023-02-05 02:28 UTC, candry7731 commented on settings/settings.json
> -                        "default": "365"
That was a mistake, I fixed it back

2023-02-05 02:28 UTC, candry7731 commented on settings/settings.json
> +                "title": "Change next up button show duration",
This is updated

2023-02-05 02:28 UTC, candry7731 commented on settings/settings.json
> +                "description": "Default is 30 seconds, you can set to 0 to diable the button or set new time in seconds to display the button",
This is updated

2023-02-05 12:01 UTC, 1hitsong approved these changes

2023-02-05 12:06 UTC, merged