Fix typo: trancoding -> transcoding
jellyfin-archive/jellyfin-roku-legacy pull request #1026
Opened 2023-02-12 22:27 UTC by RussianCow

**Changes**
There is a typo in the HVEC Direct Play description where "trancoding" is used instead of "transcoding".

**Issues**

N/A (please let me know if I need to create an issue to link here)

2023-02-13 13:02 UTC, jimdogx submitted a review, later dismissed

2023-02-13 13:02 UTC, jimdogx commented on locale/hu/translations.ts
> +        <source>Attempt Direct Play for HEVC media with unsupported profile levels before falling back to transcoding if it fails.</source>
Since you're already changing these files, let's delete the duplicate entries.  Hungarian is easy as they are all three the same.  French has a duplicate but I have no idea which one is correct.

2023-02-14 20:17 UTC, RussianCow commented on locale/hu/translations.ts
> +        <source>Attempt Direct Play for HEVC media with unsupported profile levels before falling back to transcoding if it fails.</source>
Will do! I don't speak French, but I put both phrases into the [DeepL Translator](https://www.deepl.com/en/translator) and this second one most [closely matched](https://www.deepl.com/en/translator#fr/en/Tente%20la%20lecture%20directe%20du%20codec%20HEVC%20comportant%20des%20niveaux%20de%20profils%20incompatibles%20avant%20de%20transcoder%20si%20cela%20%C3%A9choue.) the source:

> Tente la lecture directe du codec HEVC comportant des niveaux de profils incompatibles avant de transcoder si cela échoue.

> Attempt direct playback of HEVC codec with incompatible profile levels before transcoding if this fails.

Are you okay with me using this one and removing the other duplicate?

2023-03-02 16:03 UTC, cewert requested changes
We can only edit the `en_US` translation file or else Weblate will break. Please remove the edits to the other files and we can get this merged

2023-03-07 14:33 UTC, cewert approved these changes
I went ahead and removed the edits to the other translation files so we can get Weblate working again. Thanks for your contribution!

2023-03-13 20:17 UTC, 1hitsong approved these changes

2023-03-15 18:38 UTC, merged