Fix crashlog errors in Main.brs
jellyfin-archive/jellyfin-roku-legacy pull request #1066
Opened 2023-03-02 18:43 UTC by cewert

**Changes**
- Ensure vars are valid using [optional chaining operators](https://developer.roku.com/en-gb/docs/references/brightscript/language/expressions-variables-types.md#optional-chaining-operators)
- Converted `blah <> invalid` to `isValid(blah)` when found within the same function as the crash

**Issues**
Fixes #1058

2023-03-04 19:20 UTC, 1hitsong requested changes

2023-03-04 19:20 UTC, 1hitsong commented on source/Main.brs
> +            if isValid(ptr) and isValid(series?.seasonData?.items)
We should also ensure the count() on ptr is at least 2 and that the item in position 1 is valid.

2023-03-04 19:20 UTC, 1hitsong commented on source/Main.brs
> +                if isValid(group?.lastFocus)
If this condition fails because group is invalid, then line 499 will throw an error.

2023-03-04 19:20 UTC, 1hitsong commented on source/Main.brs
> +                if isValid(group?.lastFocus)
If this condition fails because group is invalid, then line 522 will throw an error.

2023-03-04 19:20 UTC, 1hitsong commented on source/Main.brs
> +                    else if isValid(node?.showID)
This is doing the opposite of what it did before. This needs to be `if not isValid`

2023-03-04 19:20 UTC, 1hitsong commented on source/Main.brs
> +                        if retryVideo <> invalid
This can be converted to use isValid()

2023-03-05 13:33 UTC, cewert commented
No longer using optional chaining operators and I've addressed all review comments

2023-03-15 00:40 UTC, 1hitsong approved these changes

2023-03-15 00:41 UTC, 1hitsong commented
@cewert Other than merge conflict, looks good.

2023-03-15 02:57 UTC, merged