Fix crash in JFOverhang.brs
jellyfin-archive/jellyfin-roku-legacy pull request #1070
Opened 2023-03-03 16:35 UTC by cewert

We were still calling `resetTime` after exiting the screensaver regardless of what the hideClock setting was set to

**Issues**
Fixes #1069
Introduced by #697

2023-03-04 23:44 UTC, cewert commented
This PR doesn't use the optional chaining operators

2023-03-13 20:56 UTC, 1hitsong commented
ResetTime() is also called from `scenemanager.brs`

Because the ResetTime function is exposed, instead of updating 1 of the calls, I think we should update the function itself. As the first line of resetTime() let's do `if m.hideClock then return` That way it future proofs the function.

2023-03-13 20:57 UTC, 1hitsong requested changes
Update resetTime function directly

2023-03-15 00:33 UTC, 1hitsong approved these changes

2023-03-15 00:33 UTC, merged