Add support for ass format subtitles for custom caption
jellyfin-archive/jellyfin-roku-legacy pull request #1075
Opened 2023-03-03 22:23 UTC by depctg

This patch add support for parsing and rendering ass format subtitles.

**Changes**

- Modify `deviceCapabilities` to allow direct stream ass subtitle tracks without transcoding.
- Add simple ass file parser.

**Issues**

- Currently the parser simply translate ass Dialogue instructions to pure texts, ignoring any other instructions and control sequences in the `Text` field. As the rendering is customized its possible to honor ass style.
- More control sequence (e.g. \N) could be processed in the parser.

2023-03-13 22:14 UTC, 1hitsong commented
This is great! For an MVP release, can you go ahead and either parse or remove more of the control elements? I'd be find it it removed all control elements and simply left the text itself.

As you can see in the screenshot, I used a demo file to test this, but because the control elements are rendered, it's not very usable.

![image](https://user-images.githubusercontent.com/3330318/224843668-7410d2e9-76c3-4364-ab8a-288e76cc4e93.png)

2023-03-13 22:22 UTC, 1hitsong requested changes

2023-03-13 22:22 UTC, 1hitsong commented on components/captionTask.brs
> +    if url[0] <> invalid
Let's go ahead and use the `isValid()` helper function instead of <> invalid. Use for all instances.

2023-03-13 22:22 UTC, 1hitsong commented on components/captionTask.brs
> +        if subtype = "vtt"
All string comparisons should force case. `subtype = LCase(url[2])`

2023-03-13 22:22 UTC, 1hitsong commented on components/captionTask.brs
> +    ' TODO: inline comments
Remove TODO comments

2023-03-13 22:22 UTC, 1hitsong commented on components/captionTask.brs
> +            dialoge = reLine.match(lines[i])[1]
Variable misspelled. Use either `dialog` or `dialogue`

2023-03-13 22:22 UTC, 1hitsong commented on components/captionTask.brs
> +                dialoge = dialoge.split(",")
Use different variable name here. Reusing in this way makes it harder to maintain.

2023-03-23 16:52 UTC, cewert commented
I know this doesn't say merge conflict but the required workflow won't run until you merge the latest version of unstable into your PR branch FYI

2023-04-21 01:51 UTC, closed without merging

2023-04-25 19:58 UTC, depctg commented
Thanks for the review, I've fixed the problems and add more filters on ass style sequences.

2023-04-25 20:22 UTC, 1hitsong commented
@depctg I'm unable to reopen. Just open a new PR 👍