Move TV Library to its own view
jellyfin-archive/jellyfin-roku-legacy pull request #1082
Opened 2023-03-05 00:35 UTC by 1hitsong

**Changes**
Moves TV Libraries off the shared itemgrid view and into its own TVLibraryView component.

This allows us to avoid needing to have collection type checks all over the view and allows us to modify the tv library view without fear of messing up anything else.

2023-03-23 16:50 UTC, cewert commented
I know this doesn't say merge conflict but the required workflow won't run until you merge the latest version of unstable into your PR branch FYI

2023-06-24 22:45 UTC, jimdogx commented
There is one warning, but otherwise appears to work great.

```
[{
	"resource": "/Users/jimi/Source/jellyfin-1hitsong/components/ItemGrid/TVShowLibraryView.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "1107",
	"severity": 4,
	"message": "This import is unnecessary because compiler option 'autoImportComponentScript' is enabled",
	"source": "brs",
	"startLineNumber": 37,
	"startColumn": 41,
	"endLineNumber": 37,
	"endColumn": 62
}]
```

2023-06-24 23:20 UTC, cewert requested changes

2023-06-24 23:20 UTC, cewert commented on components/ItemGrid/TVShowLibraryView.brs
> +    m.resetGrid = get_user_setting("itemgrid.reset") = "true"
using old syntax

2023-06-24 23:20 UTC, cewert commented on components/ItemGrid/TVShowLibraryView.brs
> +    m.deviFeature = devinfo.HasFeature("voice_remote")
this is saved to global device - `m.global.device`

2023-06-24 23:20 UTC, cewert commented on components/ItemGrid/TVShowLibraryView.brs
> +        viewSetting = get_user_setting("display.livetv.landing")
old syntax

2023-06-24 23:20 UTC, cewert commented on components/ItemGrid/TVShowLibraryView.brs
> +        m.view = get_user_setting("display." + m.top.parentItem.Id + ".landing")
old syntax

2023-06-24 23:20 UTC, cewert commented on components/ItemGrid/TVShowLibraryView.xml
> +  <script type="text/brightscript" uri="TVShowLibraryView.brs" />
```suggestion
```

This is the line from the warning. It's not needed.

2023-06-24 23:20 UTC, cewert commented on components/ItemGrid/TVShowLibraryView.xml
> +  <script type="text/brightscript" uri="pkg:/source/utils/deviceCapabilities.brs" />
These should be import statements in `TVShowLibraryView.brs`

2023-07-24 01:54 UTC, closed without merging