Remove optional chaining operators from code
jellyfin-archive/jellyfin-roku-legacy pull request #1085
Opened 2023-03-06 16:28 UTC by cewert

## Changes
- Remove all optional chaining operators from code
- Convert `blah <> invalid` to `isValid(blah)` in same file as optional chaining operators
- Remove extra white space 
- NOTE: The XML formatting is because our repo uses the format on save user setting in vscode. If we don't like how [the extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml) is formatting our files we can add user settings in vscode to modify it's behavior

## Issues
Fixes #1083

2023-03-07 23:04 UTC, 1hitsong requested changes

2023-03-07 23:04 UTC, 1hitsong commented on components/ListPoster.brs
> +        if isValid(itemData.json.UserData) and isValid(itemData.json.UserData.UnplayedItemCount)
With chaining we were also confirming itemData and itemData.json were valid.

2023-03-07 23:04 UTC, 1hitsong commented on components/home/HomeItem.brs
> +            if isValid(itemData.json.UserData) and isValid(itemData.json.UserData.UnplayedItemCount)
With chaining we were also checking that itemData and itemData.json were valid.

2023-03-07 23:04 UTC, 1hitsong commented on components/home/HomeRows.brs
> +            if isValid(item.json.UserData) and isValid(item.json.UserData.PlayedPercentage)
With chaining we were also checking that item.json is valid.

2023-03-07 23:04 UTC, 1hitsong commented on components/tvshows/TVListDetails.brs
> +    if isValid(itemData.UserData) and isValid(itemData.UserData.Played) and itemData.UserData.Played = true
With chaining we were also checking that itemData is valid.

2023-03-07 23:04 UTC, 1hitsong commented on components/tvshows/TVListDetails.brs
> +    if isValid(itemData.UserData) and isValid(itemData.UserData.PlayedPercentage) and itemData.UserData.PlayedPercentage > 0
With chaining we were also checking that itemData is valid.

2023-03-07 23:04 UTC, 1hitsong commented on components/tvshows/TVShowDetails.brs
> +        if isValid(itemData.UserData) and isValid(itemData.UserData.UnplayedItemCount)
With chaining we were also checking that itemData is valid.

2023-03-07 23:04 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if isValid(meta.json) and isValid(meta.json.ChannelId)
With chaining we were also checking that meta is valid.

2023-03-07 23:04 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if not isValid(meta.json.MediaSources[0]) or (isValid(meta.json.MediaSources[0]) and meta.json.MediaSources[0].SupportsDirectPlay = false)
I'd prefer these to still be separated. With the `not` and the `or` with the `and` and the parenthesis. A maintainer will need to break this line apart to read it.

2023-03-07 23:04 UTC, 1hitsong commented on source/api/Items.brs
> +        if data.UserData <> invalid and data.UserData.PlayedPercentage <> invalid
With chaining we were checking that data is valid.

Also, missing use of isValid()

2023-03-08 00:26 UTC, cewert commented on components/ListPoster.brs
> +        if isValid(itemData.json.UserData) and isValid(itemData.json.UserData.UnplayedItemCount)
Yes, we were. I'm assuming because it was easy to just add a couple of question marks. But I don't really understand why since the rest of the function assumes those two vars will be valid. The function needs to be refactored and in an effort to keep this PR simple and easy to review I decided against refactoring every function I came across that was like this. Which was most of them. I believe this will apply to all your other comments that are similar to this but I can go through each one and double check if you'd like.

if `itemData` is invalid then the function will crash on [line 56](https://github.com/jellyfin/jellyfin-roku/blob/04ec2effdb10d89d7fa87d302db23bbf07d0fdcb/components/ListPoster.brs#L56)

if `itemData.json` is invalid then every other if statement inside the function will crash

2023-03-08 00:33 UTC, cewert commented on components/home/HomeItem.brs
> +            if isValid(itemData.json.UserData) and isValid(itemData.json.UserData.UnplayedItemCount)
`itemData` can't be invalid or else the function would return on [line 26](https://github.com/jellyfin/jellyfin-roku/blob/04ec2effdb10d89d7fa87d302db23bbf07d0fdcb/components/home/HomeItem.brs#L26)

as for `itemData.json` the rest of the function assumes it will be valid so if it doesn't crash here it will crash somewhere else. The whole function needs refactored

2023-03-08 00:36 UTC, cewert commented on components/home/HomeRows.brs
> +            if isValid(item.json.UserData) and isValid(item.json.UserData.PlayedPercentage)
hmm I guess I just missed this one. Will fix

2023-03-08 00:39 UTC, cewert commented on components/tvshows/TVListDetails.brs
> +    if isValid(itemData.UserData) and isValid(itemData.UserData.PlayedPercentage) and itemData.UserData.PlayedPercentage > 0
The app would crash before it got to this line if `itemData` is invalid because the ~60 lines of code above it assume it's valid. Function needs refactored

2023-03-08 00:41 UTC, cewert commented on components/tvshows/TVShowDetails.brs
> +        if isValid(itemData.UserData) and isValid(itemData.UserData.UnplayedItemCount)
If we validate `itemData` is valid here we will just push the crash to a different part of the function because the rest assumes it's valid. Function needs refactored

2023-03-08 00:42 UTC, cewert commented on source/VideoPlayer.brs
> +    if isValid(meta.json) and isValid(meta.json.ChannelId)
We don't need to because [line 26](https://github.com/jellyfin/jellyfin-roku/blob/04ec2effdb10d89d7fa87d302db23bbf07d0fdcb/source/VideoPlayer.brs#L26) is already checking if meta is valid

2023-03-08 00:51 UTC, cewert commented on source/VideoPlayer.brs
> +    if not isValid(meta.json.MediaSources[0]) or (isValid(meta.json.MediaSources[0]) and meta.json.MediaSources[0].SupportsDirectPlay = false)
I combined them because it just looked redundant but I guess I agree that the other way is probably easier to read. Will fix

2023-03-08 00:57 UTC, cewert commented on source/api/Items.brs
> +        if data.UserData <> invalid and data.UserData.PlayedPercentage <> invalid
data will never be invalid because of the check on [line 76](https://github.com/jellyfin/jellyfin-roku/blob/04ec2effdb10d89d7fa87d302db23bbf07d0fdcb/source/api/Items.brs#L76)

as for `isValid()`, I tried and the brightscript extension gave me errors saying that certain components didn't have the misc.brs file in scope. My understanding was that every file that includes this file `source/api/Items.brs` would also have to include the file for `isValid()`. So in an effort to keep this PR simple and easy to review I didn't chase down all the components.

2023-03-08 01:02 UTC, cewert commented on components/tvshows/TVListDetails.brs
> +    if isValid(itemData.UserData) and isValid(itemData.UserData.Played) and itemData.UserData.Played = true
The app would crash before it got to this line if `itemData` is invalid because the code above it assume it's valid. Function needs refactored

2023-03-08 01:29 UTC, 1hitsong approved these changes

2023-03-09 19:35 UTC, merged