Update What's New popup content
jellyfin-archive/jellyfin-roku-legacy pull request #1090
Opened 2023-03-16 13:06 UTC by 1hitsong

## Changes
Update What's New popup content with latest changes for release.

2023-03-16 14:40 UTC, cewert approved these changes
We could probably condense some of the stuff I did but that sounds like a lot of work

2023-03-16 15:25 UTC, cewert commented on source/static/whatsNew.json
> +    },
```suggestion
```

2023-03-16 15:26 UTC, cewert commented on source/static/whatsNew.json
> +    },
```suggestion
```

the automation workflow is new and the one below already mentions it

2023-03-16 15:28 UTC, cewert commented on source/static/whatsNew.json
> +    },
the project board automation doesn't do anything atm because we don't have access to the JF bot and I don't think 99% of people will care about either of these

2023-03-16 15:30 UTC, cewert commented on source/static/whatsNew.json
> +    },
```suggestion
```

The npm vulnerabilities were introduced by me with the new workflows I made. This feels like patting myself on the back 😆

2023-03-16 15:32 UTC, cewert requested changes
I lied it wasn't a lot of work 😄 Please address code suggestions. You're giving me way too much credit lol

2023-03-16 22:14 UTC, 1hitsong commented
@cewert Updated

2023-03-16 22:17 UTC, cewert approved these changes

2023-03-17 02:58 UTC, candry7731 approved these changes

2023-03-19 23:01 UTC, merged