Only show next episode popup if web client setting is turned on
jellyfin-archive/jellyfin-roku-legacy pull request #1101
Opened 2023-03-19 14:07 UTC by cewert

## Changes
- check web client setting before showing next episode popup

## Issues
Fixes #1099

2023-03-22 06:41 UTC, 1hitsong requested changes

2023-03-22 06:41 UTC, 1hitsong commented on components/JFVideo.brs
> +    if m.top.userConfig.EnableNextEpisodeAutoPlay and not m.nextEpisodeButton.visible
This change will need to be copied into the new video player we're migrating to `components\video\VideoPlayerView.brs`

2023-03-22 18:18 UTC, cewert commented
Instead of pushing the `userConfig` down to each component that needs it, I've saved it to a global var where it can be accessed easily from anywhere. This will slightly increase our apps memory usage but seems like a fair trade off for having easy access to the userConfig from any component which will come in handy for other features in the future.

As for the next episode popup, I've tested playing an episode from a TV library and also using the shuffle function to test the new video player. The next episode popup was successfully suppressed in both cases but when using shuffle play the next episode still played automatically. I believe this is a bug and should be handled in another PR

2023-03-23 00:18 UTC, 1hitsong approved these changes

2023-03-23 00:33 UTC, merged