Reworks URL to match other clients
jellyfin-archive/jellyfin-roku-legacy pull request #115
Opened 2020-02-19 09:18 UTC by anthonylavado

**Changes**
Changes the server entry screen to have a single URL entry, to take both server name, base url, and port.
This matches the other clients, and effectively adds Base URL support. It also removes the https check, since we should verify that whenever possible.
If a protocol isn't specified, it assumes `http://` for the user's sake.

Adds a little explainer text, just like in the Android app.

**Issues**
Fixes #95.

**Notes**
This is my first attempt at anything Roku related, and this is one step closer to publishing to the store.

2020-02-19 09:25 UTC, dkanada commented on source/api/baserequest.brs
> +  if base.left(5) <> "https" or base.left(5) <> "http:"
```suggestion
  if base.left(4) <> "http"
```

2020-02-19 09:26 UTC, dkanada commented on source/api/baserequest.brs
> +  req.setCertificatesFile("common:/certs/ca-bundle.crt")
Do we want to always append these, even for insecure connections?

2020-02-19 09:26 UTC, dkanada commented on source/ShowScenes.brs
> +
Maybe add a base URL to the example domain. I would also remove one of the two newlines below.

2020-02-19 09:27 UTC, dkanada commented on components/config/scene.xml
> +      translation="[150, 350]" />
indent two spaces

2020-02-19 09:37 UTC, anthonylavado commented on source/api/baserequest.brs
> +  req.setCertificatesFile("common:/certs/ca-bundle.crt")
I don’t know what the cost of doing so is, if anything. Memory?
I suppose I could revert to the method before of detecting https at the start and going from there.

I know this URL build will probably be reworked at some point, right now it’s reused a lot (it’s being called for every request).

2020-02-19 09:38 UTC, anthonylavado commented on source/api/baserequest.brs
> +  if base.left(5) <> "https" or base.left(5) <> "http:"
Good point

2020-02-19 09:40 UTC, JustAMan requested changes

2020-02-19 09:40 UTC, JustAMan commented on source/ShowScenes.brs
> +  items = [ server_field]
Extra space after [?

2020-02-19 09:40 UTC, JustAMan commented on source/api/baserequest.brs
> +  if base.left(5) <> "https" or base.left(5) <> "http:"
You should actually check for `http://` or `https://`, otherwise some funny domain (like `httpsfoo.org`) would break this logic

2020-02-19 17:45 UTC, anthonylavado commented on source/ShowScenes.brs
> +  items = [ server_field]
```suggestion
  items = [ server_field ]
```

2020-02-20 00:40 UTC, bisby commented on source/api/baserequest.brs
> +  if base.left(5) <> "https" or base.left(5) <> "http:"
this should also be an `and`

`https://my.server.left(5) <> "http:"` evaluates to true. so this breaks with an or

2020-02-20 00:46 UTC, bisby requested changes
The protocol check is actively broken and prevents proper login. But otherwise this functions (thought admittedly I use https, so I can't speak to loading the certs every time).

2020-02-20 05:20 UTC, anthonylavado commented
I’ll fix the protocol check. I did test with a remote server using https (the demo server) and a local server using http, and both worked without issue. Even when I didn’t specify http for the local server, it got successfully appended from what I could tell in my testing.

I’ll revise it to be more robust though.

2020-02-20 09:50 UTC, JustAMan approved these changes

2020-02-20 16:14 UTC, bisby approved these changes

2020-02-21 03:31 UTC, merged