Prevent crash by validating Filter Menu data
jellyfin-archive/jellyfin-roku-legacy pull request #1214
Opened 2023-04-20 16:06 UTC by cewert

## Changes
- Validate filter menu data before using

## Issues
Fixes #1193

fixes v1.6.4 crash log line 56

2023-04-21 17:10 UTC, 1hitsong commented
Similar logic that was causing the error in the log also appears in onKeyEvent()

Line 269 and 323 access the same m.filtermenu variables, but we're not confirming they're valid before using them.

![image](https://user-images.githubusercontent.com/3330318/233695276-f74b2aba-a5a1-4ef5-9324-105ea0c5edd1.png)
![image](https://user-images.githubusercontent.com/3330318/233695357-76d4c18e-55af-4e52-8249-3f16972cbc64.png)

2023-04-21 17:54 UTC, cewert commented
`m.filterMenu` is also being using three more  times lower in the onKeyEvent() function. I don't see any crashes in the Roku crash logs for any of these lines. 

![more-filtermenu](https://user-images.githubusercontent.com/16514652/233701167-e9bb5ec2-fb5d-49bf-ac1d-1a403441a267.PNG)

It looks like we could call the new `isFilterMenuDataValid` function immediately if key = right or OK then return false if the function returns false. Does that solution work for you?

2023-05-11 16:48 UTC, cewert commented
@1hitsong can you take another look at this, please? I think it's ready to merge as long as my last commit works for you.

2023-05-20 00:52 UTC, 1hitsong requested changes

2023-05-20 00:52 UTC, 1hitsong commented on components/ItemGrid/ItemGridOptions.brs
> +    if isFilterMenuDataValid() = false
```suggestion
    if not isFilterMenuDataValid()
```

2023-05-20 00:52 UTC, 1hitsong commented on components/ItemGrid/ItemGridOptions.brs
> +        if isFilterMenuDataValid() = false then return false
By checking at the top for OK presses, it means the View and Sort options also won't work if the filter data is bad. I think we should isolate it so we only check the filter data is valid and return false if the user is attempting to view the filter options. That way we don't impact the other options.

2023-05-26 20:47 UTC, 1hitsong approved these changes

2023-05-27 20:46 UTC, merged