Update device profile when device capabilities change + enable all device events
jellyfin-archive/jellyfin-roku-legacy pull request #1217
Opened 2023-04-22 13:51 UTC by cewert

We were only telling jellyfin about our device profile once after login. This changes that so the device profile gets updated as needed when the device capabilities change (plug in speakers, turn on receiver, etc.).

This also enables all device events and logs their responses to help with debugging

## Changes
- Enable all [device events](https://developer.roku.com/docs/references/brightscript/events/rodeviceinfoevent.md) and log their responses to help with debugging
- When `audioCodecCapabilityChanged` or `videoCodecCapabilityChanged` update server with new device capabilities

## Issues
None but this may fix some edge case bugs

2023-04-29 17:29 UTC, cewert commented
The latest commit moves `PostDeviceProfile()` outside of `LoginFlow()` to ensure it's always ran because not all login paths make it to the end of the `LoginFlow` function. Since this is the only time in our app where we send our device capabilities to the jellyfin server, this may be a bugfix.

2023-05-19 21:11 UTC, 1hitsong requested changes

2023-05-19 21:11 UTC, 1hitsong commented on source/Main.brs
> +            else if event.Mode <> invalid
For these valid checks, let's go ahead and use isValid()

2023-05-26 20:53 UTC, 1hitsong approved these changes

2023-05-27 20:43 UTC, merged