Replace API check marks for watched items on home view
jellyfin-archive/jellyfin-roku-legacy pull request #1223
Opened 2023-04-23 16:39 UTC by 1hitsong

## Changes
Updates check marks on watched items on the home view to not use the API played indicator, but the PlayedIndicator component. 

This is 1 of many PRs I'll be opening to add this component across the client. I want to keep the PRs small to make testing easier.

## Issues
This is part of the set of fixes for #402

2023-04-24 01:06 UTC, cewert commented on components/PlayedCheckmark.brs
> +    m.checkmark.font.size = 35
```suggestion
    checkmark = m.top.findNode("checkmark")
    checkmark.font.size = 35
```

No need to save this to the m var

2023-04-24 01:09 UTC, cewert commented on components/data/HomeData.xml
> +    <field id="watched" type="bool" value="false" />
```suggestion
    <field id="isWatched" type="bool" value="false" />
```

2023-04-24 01:37 UTC, cewert requested changes
Doesn't work with the smaller movie posters

![PXL_20230424_011324760 MP](https://user-images.githubusercontent.com/16514652/233880446-81cf0056-debe-43f3-a487-5c4af6444aaa.jpg)

2023-04-24 01:58 UTC, cewert commented on components/PlayedCheckmark.xml
> +    <Label id="checkmark" width="60" height="42" font="font:SmallestBoldSystemFont" horizAlign="center" vertAlign="bottom" text="✓" />
I changed the font to Medium here and size to 48 in `PlayedCheckmark.brs` and I think it looks a lot better (I'm near sighted so def biased here 😆) but I couldn't figure out how to center it in the box. It doesn't seem to respect `vertAlign` 🤷 

![PXL_20230424_015332113 MP](https://user-images.githubusercontent.com/16514652/233882329-0b9baa2f-c9d7-4b87-8337-40648c13904a.jpg)

2023-04-24 14:21 UTC, 1hitsong commented
> Doesn't work with the smaller movie posters

I honestly didn't know the Latest rows could show watched content. Turns out there's a setting to toggle it.

![image](https://user-images.githubusercontent.com/3330318/234025192-8eabe22a-ba63-41f4-a201-50476c023e83.png)

2023-04-25 13:01 UTC, cewert commented on manifest
> +run_as_process=1
debugging code

2023-04-25 13:05 UTC, 1hitsong commented on manifest
> +run_as_process=1
Good catch! Odd changing branches didn't zero this out 🤔

2023-04-25 13:09 UTC, cewert commented
This works with the smaller movie posters now 🎉  The checkmarks also update when the home screen is "refreshed" for the most part (latest in x) with the exception of the Favorites row. That's outside the scope of this PR but thought I'd mention it in case it's an easy fix (I didn't look into it).

Once the debug code is removed from the manifest file I think this is ready to be merged 👍 

![PXL_20230425_125651344 MP](https://user-images.githubusercontent.com/16514652/234286601-2ab1d65e-c4db-4667-b7ad-783ffe31bf87.jpg)

2023-04-25 14:12 UTC, cewert approved these changes
You removed the debugging code so fast I didn't notice 😆

2023-04-25 14:32 UTC, merged