Implement global session variable to track current server and user session
jellyfin-archive/jellyfin-roku-legacy pull request #1224
Opened 2023-04-25 03:51 UTC by cewert

Save information about the currently selected server and logged in user to the global variable. This allows easy access from anywhere and also should be much faster (relatively speaking) than reading data from the Roku device's "hard drive" (though I don't have any data to prove this). Using the app does feel notably faster at times

Most of the code I wrote is in `source/ShowScenes.brs` and `source/utils/globals.brs`. I've tested logging in with an empty registry, with saved tokens, logging out, and switching servers. I still need to test "quick connect".

## Changes
- Create global session var
  - Server - to hold server URL and data from `ServerInfo()`
  - User - to hold user id, name, auth token, configuration, policy, user settings, etc.
- Integrate session var into login flow. Update session whenever we find saved session data in the registry (i.e. server, active_user, token)
- Populate server data once a server is picked
- Populate user data once the user is authenticated
- Update code base to use session vars:
  - `get_setting("server)` is now `m.global.session.server.url`
  - `get_setting("active_user)` is now `m.global.session.user.id`
  - `get_user_setting("token)` is now `m.global.session.user.authToken`
- Add `source/utils/globals.brs` to a few XML files that needed it

Depends on PR #1140

2023-05-19 16:04 UTC, cewert commented
The biggest change in logic is how the user settings are handled now.

- All default user settings are read from `settings/settings.json` when [app first loads](https://github.com/jellyfin/jellyfin-roku/pull/1224/files#diff-20d93f2448cbd74f4e508446707eb15e3d299ab2765be87dc5a8873cc11b6fcbR16) and [saved to the global session](https://github.com/jellyfin/jellyfin-roku/pull/1224/files#diff-95c22fb1629f65be26c07a9bfd1e2078271d7b09d6fd7e82eea81e63d55fe0ccR18) before a server or user is selected. This means all user settings need to have a default value. I believe this is already the case?
- After a user is authenticated, [grab all user settings from the registry and save to global session](https://github.com/jellyfin/jellyfin-roku/pull/1224/files#diff-95c22fb1629f65be26c07a9bfd1e2078271d7b09d6fd7e82eea81e63d55fe0ccR137) - overwriting any defaults.
- `get_user_setting()` no longer accepts the `default` param since all defaults are loaded on app startup.
- `set_user_setting()` and `unset_user_setting()` now add and remove the setting from the global session in addition to updating the registry

2023-05-26 21:07 UTC, 1hitsong requested changes

2023-05-26 21:07 UTC, 1hitsong commented on source/utils/session.bs
> +            print "m.global.session.user.settings = ", m.global.session.user.settings
This writes all the user setting data to the console. Can we move this to only be printed if in debug?

2023-05-27 21:57 UTC, cewert commented on source/utils/session.bs
> +            print "m.global.session.user.settings = ", m.global.session.user.settings
We could do that but currently our [production build removes comments](https://github.com/jellyfin/jellyfin-roku/blob/unstable/bsconfig-prod.json#L27) so it would be redundant. You can test this by running `npm run build-prod` locally and inspecting the files in `build/`.

2023-05-27 23:18 UTC, 1hitsong commented on source/utils/session.bs
> +            print "m.global.session.user.settings = ", m.global.session.user.settings
I did as you said and the output file still includes the print message. Was your expectation that the build script would remove this?

![image](https://github.com/jellyfin/jellyfin-roku/assets/3330318/5d04f42a-a929-4cad-8834-07e152e21ffa)

2023-05-28 00:00 UTC, cewert commented on source/utils/session.bs
> +            print "m.global.session.user.settings = ", m.global.session.user.settings
Hah Yea I don't know what I was thinking sorry. It removes roku-log statements and comments - not print statements. Fix incoming

2023-05-29 01:52 UTC, 1hitsong approved these changes

2023-06-01 12:43 UTC, merged