Respect user's audio preference from the server
jellyfin-archive/jellyfin-roku-legacy pull request #1252
Opened 2023-05-06 22:02 UTC by jimdogx

Uses the user's Default Playback preferences for TV Shows from the Server.

## Changes
* Reads the user's Playback preference: "Preferred audio language" and "Play default audio track regardless of language".
* Saves this information in settings.
* Uses these settings when playing a TV episode (unless the user has opened the Audio Selection Options).

## Issues
Fixes: #806 

I tested this from "Next Up", "Continue Watching" and the TV Show episode list page.

2023-05-06 22:16 UTC, cewert commented on source/Main.brs
> +function FindPreferredAudioStream(streams, id = "")
```suggestion
function FindPreferredAudioStream(streams as dynamic, id = "" as string) as integer
```

Can we also move this out of `Main.brs`? I moved all the other functions out of Main (put them in showScenes) because the new logger doesn't work in Main and also because the rooibos unit testing framework can't test any of the code in Main

2023-05-06 22:20 UTC, jimdogx commented on source/Main.brs
> +function FindPreferredAudioStream(streams, id = "")
Sure can!  Been out of the loop for a while so I know there is a lot of stuff I've missed 😄

2023-05-06 22:25 UTC, cewert commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
I changed this around in #1224 but currently you can access the user config from `m.user.configuration`. `m.user` gets set to `AboutMe()` right before we call `LoadUserPreferences()`

2023-05-06 22:30 UTC, cewert commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
Just realized you're using the `Users/Me` API call instead of `Substitute("Users/{0}", id)` that `AboutMe()` uses. Not sure how much those differ so this may be necessary to get the info you're looking for I'm not sure.

2023-05-07 00:46 UTC, jimdogx commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
Yep, I looked at m.user.configuration first.  I doesn't have any of the playback settings that Users/Me does 😄

2023-05-07 00:49 UTC, jimdogx commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
But now that I'm looking at your #1224 there are some things I can use (like active user).... 👍

2023-05-07 00:52 UTC, jimdogx commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
Just noticed it's not merged yet.  So it will have to be cleaned up after... or this PR can wait to be merged after #1224 😄

2023-05-07 01:45 UTC, cewert commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
Interesting! Sounds like I should add the extra config settings from `Users/Me` to the global user session var.

I still got #1224 marked as draft because I haven't tested quick connect yet and as of right now I have no way of doing so. If this ends up merged first I'm OK with going back and fixing things if need be.

2023-05-11 14:13 UTC, jimdogx commented on source/api/userauth.brs
> +    jsonResponse = getJson(resp)
Now that Global Player (Part 1) has been merged, I can see about working on getting this in to the latest code base.  I'll look at adding Users/Me to m.user.configuration (or m.user.preferences etc).

2023-05-12 02:19 UTC, 1hitsong requested changes

2023-05-12 02:19 UTC, 1hitsong commented on source/Main.brs
> +                        audio_stream_idx = FindPreferredAudioStream(itemNode.json.MediaStreams)
We need to ensure `itemNode.json.MediaStreams` is valid before using it.

2023-05-12 02:19 UTC, 1hitsong commented on source/Main.brs
> +                        audio_stream_idx = FindPreferredAudioStream(invalid, selectedItem.json.id)
We need to ensure `selectedItem.json.id` is valid before using it.

2023-05-12 02:24 UTC, 1hitsong requested changes

2023-05-12 02:24 UTC, 1hitsong commented on source/ShowScenes.brs
> +        if jsonResponse <> invalid and jsonResponse.MediaStreams <> invalid
We can flip this to remove the else clause.

```suggestion
        if jsonResponse = invalid or jsonResponse.MediaStreams = invalid then return 1
```

2023-05-12 02:24 UTC, 1hitsong commented on source/ShowScenes.brs
> +            if streams[i].Type = "Audio" and streams[i].Language = preferredLanguage
String comparisons should always force case.

```suggestion
            if LCase(streams[i].Type) = "audio" and LCase(streams[i].Language) = LCase(preferredLanguage)
```

2023-05-12 22:25 UTC, cewert reviewed
This looks good to me 👍

2023-05-13 01:49 UTC, 1hitsong commented
When playing an episode from a collection, it doesn't play preferred audio language, it played default track.

When playing an episode from a playlist, it doesn't play preferred audio language, it played default track.

2023-05-13 17:28 UTC, jimdogx commented
Closing this PR in lieu of #1265 since that works better with the new Global Queue Player (thanks @1hitsong ).

2023-05-13 17:28 UTC, closed without merging