Allow selection of TV Show versions
jellyfin-archive/jellyfin-roku-legacy pull request #1279
Opened 2023-05-21 04:39 UTC by jimdogx

Allows the user to select between versions of TV Shows.

## Changes
* Adds Video (along side Audio) as an option for TV Shows.

## Issues
#1276 

## Known Issues
* Multiple versions of TV Shows is not currently automatically detected by Jellyfin, but may be in the future: https://github.com/jellyfin/jellyfin/pull/8004
* Users can manually group TV Shows via some clients (e.g. Android)
* If one of the Videos has different audio options, the user must select the Video desired, exit options and re-enter options in order to see the refreshed audio options.

2023-05-26 22:50 UTC, 1hitsong requested changes

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +        if streams[i].VideoType = "VideoFile"
Straing comparisons should force case.

```suggestion
        if LCase(streams[i].VideoType) = "videofile"
```

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +            "StreamIndex": i })
Formatting got messed up on this line for some reason /shrug

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +        if m.tvListOptions.options <> invalid and m.tvListOptions.options.videos <> invalid
For consistency, let's go ahead and use isValid() for these checks.

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +sub videoOptionsClosed()
Let's go ahead and add a function documentation comment for your new function

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +        if mediaSources <> invalid
Let's use isValid()

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +        if mediaStreams <> invalid
Let's use isValid()

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +        if m.tvListOptions.options <> invalid
Let's use isValid()

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListDetails.brs
> +    m.top.findNode("video_codec").visible = false
We're using `m.top.findNode("video_codec")` several times here. Go ahead and save it to a variable so we don't need to search the nodes each time.

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +    if m.top.options.videos <> invalid
Use isValid()

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +            if view.Selected <> invalid and view.Selected = true
Use isValid()

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +    if m.top.options.audios <> invalid
Use isValid()

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +                else
The blank then clause is weird. Let's just remove it and go with `if m.selectedVideoIndex <> selIndex`

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +                else
Same as above - let's remove the blank then clause.

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListDetails.brs
> +            if mediaStreams[i].Type = "Audio" and audioIdx = invalid
String comparisons should force case

2023-05-26 22:50 UTC, 1hitsong commented on components/tvshows/TVListDetails.brs
> +        if streams[i].VideoType = "VideoFile"
String comparisons should force case.

2023-05-26 22:52 UTC, jimdogx commented on components/tvshows/TVEpisodeRowWithOptions.brs
> +        if streams[i].VideoType = "VideoFile"
I keep forgetting this.  Thanks!

2023-05-26 23:02 UTC, jimdogx commented on components/tvshows/TVListOptions.brs
> +                else
Good catch....copy and paste from the old way it was being done.

2023-05-29 00:32 UTC, 1hitsong requested changes

2023-05-29 00:32 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +            if isValid(view.Selected) and view.Selected = true
```suggestion
            if isValid(view.Selected) and view.Selected
```

2023-05-29 00:32 UTC, 1hitsong commented on components/tvshows/TVListOptions.brs
> +            if isValid(audio.Selected) and audio.Selected = true
```suggestion
            if isValid(audio.Selected) and audio.Selected
```

2023-05-29 03:18 UTC, jimdogx commented
Note: I made one last change, I copied the change made for movie options in #1286 as it really does look better when you have long video / audio descriptions.

2023-06-22 12:28 UTC, 1hitsong approved these changes

2023-06-22 13:02 UTC, merged