proof of concept - infer server url proto and port
jellyfin-archive/jellyfin-roku-legacy pull request #1280
Opened 2023-05-21 06:40 UTC by sevenrats

Allow the user to enter much less information, since entering info on the roku suxxx.
This draft version is over commented and prints, for your reading pleasure.
Please comment.
Once we are in agreement I will remove the excessive comments and print statements.
doesn't really address #366 but its a giant leap forward.

2023-05-21 13:51 UTC, cewert commented
The debugging stuff can stay to help with testing but if this is ready for review please remove the draft tag.

2023-05-21 15:01 UTC, cewert requested changes

2023-05-21 15:01 UTC, cewert commented on source/utils/misc.brs
> +    input_url = urlRegex.Match(input)
Vars should be camelCase

2023-05-21 15:01 UTC, cewert commented on source/utils/misc.brs
> +    timeout.Mark()
```suggestion
```

[roDateTime objects are automatically marked on creation.](https://developer.roku.com/en-ca/docs/references/brightscript/interfaces/ifdatetime.md#mark-as-void)

2023-05-21 15:01 UTC, cewert commented on source/utils/misc.brs
> +        proto_candidates.push(proto + "//" + host) ' but still allow arbitrary protocols if they are declared
What other protocols could possibly work here?

2023-05-21 15:01 UTC, cewert commented on source/utils/misc.brs
> +        req = CreateObject("roUrlTransfer")
Shouldn't we be attaching the default roku SSL cert to the request if the protocol is https?

We do this automatically in `APIRequest()` but you're not using that function - see [here](https://github.com/jellyfin/jellyfin-roku/blob/unstable/source/api/baserequest.brs#L66)

2023-05-21 15:01 UTC, cewert commented on source/utils/misc.brs
> +function url_candidates(input as string)
Please use camelCase or PascalCase for new function names. We haven't settled on one or the other so you can pick whichever you want - I usually match the other functions in the file I'm working on.

2023-05-21 15:01 UTC, cewert commented on source/utils/misc.brs
> +function determine_server_url(url as string)
Please use camelCase or PascalCase for new function names. We haven't settled on one or the other so you can pick whichever you want - I usually match the other functions in the file I'm working on.

2023-05-21 15:22 UTC, sevenrats commented on source/utils/misc.brs
> +function url_candidates(input as string)
omg i can't believe i've been writing this much python.  in my head i'm like "why does snake case even exist this is dumb" and then I go and do it. lol.

2023-05-21 15:24 UTC, sevenrats commented on source/utils/misc.brs
> +        proto_candidates.push(proto + "//" + host) ' but still allow arbitrary protocols if they are declared
well, the primary purpose of this logic is to simply pass through http or https as it was declared. elsewise, i have no idea what a user might have going on, I'm just pointing out that this code does not discriminate here because it would not be appropriate for this block to descriminate against certain protos.  if we decide to santize them we should do it right when submit is clicked.

2023-05-21 15:28 UTC, sevenrats commented on source/utils/misc.brs
> +        req = CreateObject("roUrlTransfer")
yes. will do.

2023-05-22 05:05 UTC, sevenrats commented on source/utils/misc.brs
> +        req = CreateObject("roUrlTransfer")
the amount of changes that it would take to buildUrl() and APIRequest() just aren't justified for this in my opinion, so I did this.
I will follow up with a pr that unifies the setCertificate functionality in a single place like i did with the regexes so it doesn't get stringy.

2023-06-27 02:20 UTC, cewert requested changes

2023-06-27 02:20 UTC, cewert commented on source/utils/misc.brs
> +    if url[2] = invalid
```suggestion
    if url[1] = invalid
```

2023-06-27 02:20 UTC, cewert commented on source/utils/misc.brs
> +    port = url[3]
Need to also grab the next thing in the array `url[4]`. This won't work with url's with a sub dir like `https://demo.jellyfin.org/stable`.

2023-06-27 02:20 UTC, cewert commented on source/utils/misc.brs
> +    if url[2] = invalid
```suggestion
    if url[1] = invalid
```
using host instead of proto

2023-06-27 02:30 UTC, cewert commented on source/utils/misc.brs
> +        proto_candidates.push("https://" + host)
You could make an array of all possible protocols `[ "http", "https" ]` and loop through them here and even below in the for loop on 236. Then it would be easy to add more in the future.

2023-06-27 02:32 UTC, cewert commented on source/utils/misc.brs
> +        proto_candidates.push("https://" + host)
```suggestion
    possibleProtos = [ "http", "https" ]
    if proto = "none:"
        ' try every possible proto if user declared nothing
        for each possibleProto in possibleProtos
            proto_candidates.push(possibleProto + "://" + host) 
        end for
```

Something like this

2023-07-05 16:47 UTC, candry7731 commented
I would like to test this, Let me know if you need help with the merge conflicts

2023-08-08 01:43 UTC, closed without merging