add reused regexes to globals
jellyfin-archive/jellyfin-roku-legacy pull request #1281
Opened 2023-05-21 16:49 UTC by sevenrats

move regexes that get used more than once into global constants

2023-05-21 17:01 UTC, cewert commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
Do we really need to save the whole object? Wouldn't saving the main regex string suffice?

2023-05-21 17:18 UTC, sevenrats commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
the whole object is super duper tiny, and the point of this is to avoid the repeated lines of code.  if we store only the string then we don't elliminate repeated lines, we only change the lines that repeat.

2023-05-21 18:00 UTC, cewert commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
I thought the point of the PR was to "add reused regexes to globals" and the main thing that is reused is the regex string not the object. You also saved the objects to the `constants` global field which was filled with strings and not objects.

Saving the objects like this also prevents us from changing the last parameter when creating the regex object vs saving just the regex string. There are [four valid params](https://developer.roku.com/en-ca/docs/references/brightscript/components/roregex.md) (probably five if you include blank). So if needed in the future, will we store multiple regex objects with the same regex string just so we can support the other params?

2023-05-21 18:06 UTC, sevenrats commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
each object is defined by it's purpose, not only by its string.   we will never want case sensitive localhost matching, for example.  storing the objects is the correct, because it allows the regex to be reused with a single line. putting the objects in constants is appropriate because they are constant.
can you help me understand your objections?

2023-05-21 18:18 UTC, sevenrats commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
the main motivator for this PR is that I'm about to copy the whole url regex and it's associated comments to it's THIRD home in the code.  doing this reduces the lines it takes to invoke the regexes, and gives them a single home where they can be commented/changed.  For as often as it would happen, if we really needed to I think storing multiple regex objects that had the same string would not be the end of the world, but I can't imagine a situation in which we would need this.  such a regex would need to have multiple applications that were reused in the code. if one did I think the overhead is justified for readability and efficiency.

2023-05-21 18:38 UTC, cewert commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
I'm not against saving the objects I just think saving objects in global should only be done if absolutely necessary like the scene manager or the global video player. The recent bug where the system screensaver wouldn't turn on was caused by changing a param on the global video player even though the player wasn't in focus - weird things can happen sometimes and I have trust issues when it comes to roku OS doing what it's supposed to 😛 Since we don't *need* to save the object my instinct is to not save it and only save the string.

> this pr reduces the burden of using the regexes, and gives them a single home where they can be commented/changed.

That would still be true if we only saved the strings in global. The only difference being the one line needed to create the regex object.

> Maybe youd prefer if they were in m.global.regex instead of m.global.constants?

That makes more sense to me but it's not a big deal either way. I'd like the rest of the team to weigh in on this and the string vs object debate.

2023-05-21 18:53 UTC, sevenrats commented on source/utils/globals.brs
> +                url: CreateObject("roRegex", "^(.*:)//([A-Za-z0-9\-\.]+)(:[0-9]+)?(.*)$", ""),
we are essentially on the same page although i dont agree that the burden is reduced by storing the strings.  It will be the same burden as without the pr because you will still need to find an existing instance and copy it, because you may remember the m.global.constants.... string but you won't remember all the flags that were passed to it, so the use pattern remains "find an instance, copy it, put it another place in the code" instead of simply utilizing the memorable variable name directly.

2023-05-26 22:13 UTC, 1hitsong submitted a review, later dismissed

2023-05-26 22:13 UTC, 1hitsong commented on source/utils/misc.brs
> +function parseUrl(url as string) as object
Let's go ahead and add function documentation comment

2023-05-26 22:13 UTC, 1hitsong commented on source/utils/misc.brs
> +function isLocalhost(url as string) as boolean
Let's go ahead and add function documentation comment

2023-05-29 01:01 UTC, 1hitsong commented
Code looks good. Let's go ahead and add tests since these are small functions.

You can find examples `test-app\source\tests\utils\misc\isValid.spec.bs`

2023-06-23 17:40 UTC, cewert commented
@sevenrats I added unit tests for your new functions. Please check them out and add any use cases I may have missed.

2023-06-23 17:45 UTC, cewert requested changes

2023-06-23 17:45 UTC, cewert commented on source/utils/misc.brs
> +' Proto must be declared or array members will be invalid
```suggestion
' Proto must be declared or array will be empty
```

2023-06-23 17:45 UTC, cewert commented on source/utils/misc.brs
> +' Returns an array from a url of [proto, host, port, subdir/params]
```suggestion
' Returns an array from a url - [ proto, host, port, subdir/params ]
' If port or subdir are not found, an empty string will be added to the array
```

2023-06-26 20:32 UTC, sevenrats commented on source/utils/misc.brs
> +' Proto must be declared or array members will be invalid
no they aren't empty they are invalid

2023-06-26 21:07 UTC, cewert commented on source/utils/misc.brs
> +' Proto must be declared or array members will be invalid
I guess technically they are invalid because they don't exist but I know for a fact that an empty array is returned because I observed it while writing the unit tests and even wrote a unit test for this specific scenario [here](https://github.com/jellyfin/jellyfin-roku/pull/1281/files#diff-a122b05f8bbd86f74315d44cc55ddfce440d8e5ee85f2a4cc34123f860270718R21).

2023-06-27 00:29 UTC, sevenrats commented on source/utils/misc.brs
> +' Proto must be declared or array members will be invalid
i wrote invalid because if you look for it you get invalid, and I was just trying to prepare other developers for this.  like you can check if the value is there with an isValid(), like i do in #1280  if you scroll down to misc.brs theres tons of debug prints in there that make clear why i made this choice.  just take a look at that and I will defer to your final decision.

2023-06-27 02:08 UTC, cewert commented on source/utils/misc.brs
> +' Proto must be declared or array members will be invalid
My point is that the way it's written could be interpreted as returning `[ invalid, invalid, invalid, invalid ]` when really it returns `[]`. `isValid()` will say false for both but they are not the same thing.

I don't think there's anyway to misinterpret "array will be empty" but if you want to add something about it returning invalid or whatever go for it 👍

2023-06-27 02:09 UTC, cewert commented on source/utils/misc.brs
> +' Returns an array from a url of [proto, host, port, subdir/params]
```suggestion
' Returns an array from a url - [ url, proto, host, port, subdir/params ]
' If port or subdir are not found, an empty string will be added to the array
```

we should add a reference to the original url getting returned

2023-06-30 06:53 UTC, sevenrats commented
Im +1 on this. are we waiting on anything else?

2023-06-30 15:05 UTC, cewert approved these changes

2023-06-30 15:07 UTC, merged