unify setCertificates functionality
jellyfin-archive/jellyfin-roku-legacy pull request #1282
Opened 2023-05-22 05:22 UTC by sevenrats

i didnt actually test this

2023-05-22 13:32 UTC, cewert commented on source/utils/globals.brs
> +            capath: "common:/certs/ca-bundle.crt"
I don't see the point in saving the default cert path to the global array.

The best part of the global array is that it can be easily access from both source code and component code. Since our app is only ever going to use this string once from the `setCertificateAuthority` function it doesn't make sense to me to save the path permanently in memory. It doesn't save code. It doesn't make anything more convenient.

2023-05-22 15:11 UTC, sevenrats commented on source/utils/globals.brs
> +            capath: "common:/certs/ca-bundle.crt"
this was just a little lul. i mean i like having it here because i change it down stream but really i can go find it anywhere.

2023-05-27 20:51 UTC, cewert requested changes

2023-05-27 20:51 UTC, cewert commented on source/api/baserequest.brs
> +sub setCertificateAuthority(request as object) as void
Can you add a function documentation comment please?

2023-05-29 19:10 UTC, cewert commented on source/api/baserequest.brs
> +' your custom CA file goes here
```suggestion
```

2023-05-30 13:40 UTC, cewert approved these changes

2023-06-01 18:09 UTC, merged