Update GetPlaybackInfoTask.brs
jellyfin-archive/jellyfin-roku-legacy pull request #1320
Opened 2023-06-28 18:35 UTC by candry7731

Add Device ID filter the the Get sessions API Call. This allows us to get the correct device playback if multiple devices are active at once. 

Also add Tanscoding info for Direct Streaming. This will show if there is no transcodingInfo from the deviceSession. This is more inline with the web server activity info box.

## Issues
Device session was only quering the first active device. This filters the query to get the device ID

2023-06-28 22:07 UTC, cewert requested changes

2023-06-28 22:07 UTC, cewert commented on locale/en_US/translations.ts
> +        <message>
```suggestion
		<message>
			<source>Direct playing</source>
			<translation>Direct playing</translation>
        <message>
```

I didn't see `Direct playing` in the translation file either

2023-06-29 02:18 UTC, cewert requested changes

2023-06-29 02:18 UTC, cewert commented on components/GetPlaybackInfoTask.brs
> +    sessions = api.sessions.Get(params)
We should also fix the same API request in `GetPlaybackInfo()` in `VideoPlayer.brs`. I haven't tested but I'm assuming it has the same bug you found here where it's not using the right session.

That said, it's probably better if we just update the [`api.sessions.Get()` function](https://github.com/jellyfin/jellyfin-roku/blob/unstable/source/api/sdk.bs#L1377) to use `{ "deviceId": m.global.device.id }` as the default params instead of updating both function calls. I think most of the time that's what we'd want and it could always be overridden.

2023-06-29 02:32 UTC, candry7731 commented on components/GetPlaybackInfoTask.brs
> +    sessions = api.sessions.Get(params)
I like that, how would we update to use the defualt params? I don't see any other calls with default params.....

2023-06-29 02:55 UTC, cewert commented on components/GetPlaybackInfoTask.brs
> +    sessions = api.sessions.Get(params)
I just mean updating the default params of the function itself. Right now it defaults to an empty array. Something like this:

```
function Get(params = { "deviceId": m.global.device.id } as object)
    req = APIRequest("/sessions", params)
    return getJson(req)
end function
```

2023-06-29 14:26 UTC, candry7731 commented on components/GetPlaybackInfoTask.brs
> +    sessions = api.sessions.Get(params)
Done! Reverted the sessions api call in the playback file and updated the api to default to device ID

2023-06-29 16:43 UTC, cewert requested changes

2023-06-29 16:43 UTC, cewert commented on source/api/sdk.bs
> +        function Get(params = {"deviceId": m.global.device.id} as object)
The linter doesn't like this line. I think it needs spaces between the brackets
```suggestion
        function Get(params = { "deviceId": m.global.device.id } as object)
```

2023-06-30 02:14 UTC, cewert requested changes
I know you were just copying web client but the commas aren't needed. After that it's ready to go 👍

2023-06-30 02:14 UTC, cewert commented on components/GetPlaybackInfoTask.brs
> +        sessionStats.data.push("<b>" + tr("The source file is entirely compatible with this client, and the session is receiving the file without modifications.") + "</b>")
```suggestion
        sessionStats.data.push("<b>" + tr("The source file is entirely compatible with this client and the session is receiving the file without modifications.") + "</b>")
```

2023-06-30 02:14 UTC, cewert commented on locale/en_US/translations.ts
> +            <translation>The source file is entirely compatible with this client, and the session is receiving the file without modifications.</translation>
```suggestion
            <source>The source file is entirely compatible with this client and the session is receiving the file without modifications.</source>
            <translation>The source file is entirely compatible with this client and the session is receiving the file without modifications.</translation>
```

2023-06-30 02:50 UTC, cewert approved these changes

2023-06-30 02:50 UTC, merged