proof of concept - infer server url proto and port redux
jellyfin-archive/jellyfin-roku-legacy pull request #1357
Opened 2023-09-07 00:49 UTC by sevenrats

## Changes

## Issues

2023-09-07 01:10 UTC, cewert requested changes
First pass on the code. Haven't tested it yet

2023-09-07 01:10 UTC, cewert commented on source/utils/misc.brs
> +function inferServerUrl(url as string)
```suggestion
function inferServerUrl(url as string) as string
```

then you can have your function return "" instead of returning invalid

2023-09-07 01:10 UTC, cewert commented on source/utils/misc.brs
> +function inferServerUrl(url as string)
Add function definition please.

2023-09-07 01:10 UTC, cewert commented on source/utils/misc.brs
> +    ' proto $1, host $2, port $3, the-rest $4
add function definition please. should probably move this comment up there.

2023-09-07 01:10 UTC, cewert commented on source/utils/misc.brs
>  function isLocalhost(url as string) as boolean
function definition

2023-09-07 01:39 UTC, sevenrats commented on source/utils/misc.brs
> +    ' proto $1, host $2, port $3, the-rest $4
oh woops. this was bad merge fixing.

2023-09-07 01:49 UTC, cewert commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
the old function always returned a string. if the new function returns empty we should just skip everything or throw an error

```suggestion
                serverUrl = inferServerUrl(screen.serverUrl)
                if serverUrl <> ""
```

2023-09-07 02:09 UTC, sevenrats commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
this doesn't actually work. i have a better idea tho i think one sec.

2023-09-07 02:11 UTC, sevenrats commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
no i don't have a better idea, but, this doesn't work.

2023-09-07 02:23 UTC, cewert commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
alright. I'll see what I can do when I test it. you added the closing for the if statement right?

2023-09-09 23:11 UTC, sevenrats commented
need to sanitize the path element in the regex so that it doesn't have  trailing /
because if it did that would mess up the concatenation of /info/public

2023-09-10 18:02 UTC, cewert requested changes

2023-09-10 18:02 UTC, cewert commented on source/utils/misc.brs
> +                print "Successfully inferred server URL: " selectedUrl
still need to verify the server responding is a jellyfin server and not an emby server for example

2023-09-10 22:44 UTC, cewert commented on source/utils/misc.brs
> +    if path.endswith("/") then path = path.Left(len(path) - 1)
I think this should be at the top of the function. It's possible to add a slash after the url without having a subdir like `http://192.168.1.2/` or `jelllyfin.example.com/`

2023-09-10 22:58 UTC, sevenrats commented on source/utils/misc.brs
> +    if path.endswith("/") then path = path.Left(len(path) - 1)
it only matters with path because remember we are handling outputs of the regex, not the string itself.  only the path might have a problematic trailing slash

2023-09-10 22:59 UTC, sevenrats commented on source/utils/misc.brs
> +    if path.endswith("/") then path = path.Left(len(path) - 1)
have you seen a trailing slash come through the regex? i didnt specifically test this

2023-09-10 23:15 UTC, cewert commented on source/utils/misc.brs
> +    if path.endswith("/") then path = path.Left(len(path) - 1)
right and if you move this to the top, you will eliminate the trailing slash on the path as well as any other trailing slashes for url's without paths. no downside with potential upside

2023-09-10 23:21 UTC, sevenrats commented on source/utils/misc.brs
> +    if path.endswith("/") then path = path.Left(len(path) - 1)
i will change it but for the record its plenty robust.  the regex is desinged to handle this because in this case port is empty and path is "/", which gets trimmed properly to "" by the code as written.

2023-09-10 23:28 UTC, cewert commented on source/utils/misc.brs
> +function isJellyfinServer(si as object) as boolean
function definition

2023-09-10 23:29 UTC, sevenrats commented on source/utils/misc.brs
> +function isJellyfinServer(si as object) as boolean
lol wut where did it go?

2023-09-10 23:30 UTC, sevenrats commented on source/utils/misc.brs
> +function isJellyfinServer(si as object) as boolean
oh i undid it trying to troubleshoot the bad json response. sheesh.

2023-09-11 01:44 UTC, cewert commented on source/utils/misc.brs
> +    ' as its mostly compat for legacy registry entries that predate this code
why would you want to remove this check? it prevents us from inferring the url when we know we have a working one already. regardless of server or app version, isn't this a good thing no matter what?

2023-09-11 01:45 UTC, cewert commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
marking this as unresolved since this was never addressed

2023-09-11 01:47 UTC, cewert commented on source/utils/misc.brs
> +    ' as its mostly compat for legacy registry entries that predate this code
huh, apparently I reviewed old code. this comment is gone now. my fault

2023-09-11 01:50 UTC, sevenrats commented on source/utils/misc.brs
> +    ' as its mostly compat for legacy registry entries that predate this code
just from before we established that this code is permanent. its already gone.

2023-09-11 01:53 UTC, sevenrats commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
i guess i dont see the problem. it gets caught right there at 63.

2023-09-11 01:54 UTC, sevenrats commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
like, isConnected evaluates to false and handles not just the zero string case but any other case which does not resolve.  it seems to me that this code is already designed to handle this.

2023-09-11 02:04 UTC, cewert commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
the old function always had a value. now that your function can return an empty string, we should stop resetting registry variables for no reason. the code is assuming that the serverurl is legit but we know it's not when it's empty

![pr-suggestion](https://github.com/jellyfin/jellyfin-roku/assets/16514652/d454db40-0a52-4175-9016-086860c04fae)

2023-09-11 02:07 UTC, cewert commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
actually we could just move this down below `if isConnected` that way we don't have to add an if statement

2023-09-11 02:07 UTC, sevenrats commented on source/ShowScenes.brs
> +                serverUrl = inferServerUrl(screen.serverUrl)
oh yeah. i agree. thats not what i thought you meant ive been encapsulate the whole rest of the block, which of course breaks it.
do you want to push this in or should i?

2023-09-11 02:31 UTC, cewert requested changes
Works well for me. No duplicates. No bugs 👍 

Once the debugging stuff is cleaned up I'll approve. It's ok to leave some debugging but right now it's a bit excessive

2023-09-13 13:46 UTC, cewert commented on source/utils/misc.brs
> +function isJellyfinServer(si as object) as boolean
si isn't very descriptive.
```suggestion
function isJellyfinServer(serverResponse as object) as boolean
```

2023-09-13 13:46 UTC, cewert commented on source/utils/misc.brs
> +    final_candidates = []
```suggestion
    finalCandidates = []
```

2023-09-14 22:23 UTC, cewert commented on source/utils/misc.brs
> +function urlCandidates(input as string)
function definition

2023-09-14 22:24 UTC, cewert commented on source/utils/misc.brs
> +            protoCandidates.push(supportedProto + "//" + host)
you're not adding the path. won't this break if a user supplies a path but no protocol?

```suggestion
            protoCandidates.push(supportedProto + "//" + host + path)
```

2023-09-14 22:26 UTC, sevenrats commented on source/utils/misc.brs
> +            protoCandidates.push(supportedProto + "//" + host)
this is not necessary. protoCandidates is only used to build finalCandidates, and finalCandidates is where we add the path and port.

2023-09-14 22:52 UTC, cewert commented on source/utils/misc.brs
> +                isJellyfinServer(resp.GetString())
you're not validating the response is from jellyfin before you return the url. I have emby on 8096 and when I use the ip with no port emby public users are shown.

```suggestion
            if resp.GetResponseCode() = 200 and isJellyfinServer(resp.GetString())
                selectedUrl = hosts.lookup(resp.GetSourceIdentity().ToStr())
```

2023-09-14 23:06 UTC, sevenrats commented on source/utils/misc.brs
> +                isJellyfinServer(resp.GetString())
oh you are right! good catch this is literally just throwing away the bool. I think this is how I had it during my test invocations.  thank god for your emby server. fixing now.

2023-09-14 23:07 UTC, sevenrats commented on source/utils/misc.brs
> +                isJellyfinServer(resp.GetString())
in fact, I had it this way. I think this must have been the victim of a ctrl-z storm

2023-09-14 23:24 UTC, cewert approved these changes
Looks good to me nice job 👍

2023-10-15 19:55 UTC, 1hitsong commented
Hard crash if user enters server value that begins with forward slashes: `//128.1.8.8`

2023-10-15 23:19 UTC, sevenrats commented
@1hitsong i'm not able to reproduce this can we see a crash log please

2023-10-15 23:24 UTC, cewert commented
Pretty sure when he says hard crash he means that the roku device reboots which would mean no crash log.

2023-10-15 23:26 UTC, sevenrats commented
> Pretty sure when he says hard crash he means that the roku device reboots which would mean no crash log.

the crash I've been able to reproduce is a softy. the spinner keeps going and the home button works. I can't get it to crash hard.  What do you think should be done about it?

2023-10-15 23:52 UTC, 1hitsong commented
Your latest changed fixed my crash.

2023-10-15 23:53 UTC, sevenrats commented
> Your latest changed fixed my crash.

nice. good catch as always.

2023-10-16 00:00 UTC, 1hitsong requested changes

2023-10-16 00:00 UTC, 1hitsong commented on source/utils/misc.brs
> +    d = ParseJson(systemInfo)
```suggestion
    data = ParseJson(systemInfo)
```

Let's use a more descriptive variable name.

2023-10-16 00:00 UTC, 1hitsong commented on source/utils/misc.brs
> +    return False
```suggestion
    return false
```

2023-10-16 00:00 UTC, 1hitsong commented on source/utils/misc.brs
> +        return d.ProductName = "Jellyfin Server"
1. String comparisons should force a case using LCase()
2. "Jellyfin Server" is a magic string, we should move it to a constant in `source\utils\globals.brs`

2023-10-16 13:28 UTC, sevenrats commented on source/utils/misc.brs
> +        return d.ProductName = "Jellyfin Server"
this one i don't understand.  you want me to put the magic string in constant globals. I get that.  but then, force a case on it?  im not grokking forcing the case on the magic string.  you want it stored as-is and then Lcased for the comparison or you want it stored lcase?

2023-10-16 14:07 UTC, 1hitsong commented on source/utils/misc.brs
> +        return d.ProductName = "Jellyfin Server"
You would force the case on what is currently `d.ProductName`. Just store the constant lower cased.

2023-10-21 13:10 UTC, sevenrats commented on source/utils/misc.brs
> +        return d.ProductName = "Jellyfin Server"
sorry to delay this should all get addressed this coming week

2023-10-30 12:50 UTC, 1hitsong commented on source/utils/misc.brs
> +        return d.ProductName = "Jellyfin Server"
@sevenrats FYI, we're starting to close up the release window and would like to include this change. This you'll have time to get it up and out this week?

2023-10-30 14:48 UTC, sevenrats commented on source/utils/misc.brs
> +        return d.ProductName = "Jellyfin Server"
yes

2023-10-31 21:35 UTC, 1hitsong approved these changes

2023-10-31 21:35 UTC, merged