Improve Quick Play support
jellyfin-archive/jellyfin-roku-legacy pull request #1376
Opened 2023-09-16 21:30 UTC by cewert

Expand Quick Play support

NOTE: Some queries take a little while to load (like shuffling a large series or shuffling an artist with a lot of songs) and since there is no loading spinner it may seem as if the app is unresponsive.

## Changes
- BoxSet support added
  - Play all the movies in the collection
  - Works from home screen and library view when viewing collections
- Series support added
  - Play the first unwatched episode
    - If all episodes are watched, shuffle play all episodes
  - Works from the home screen and TV library view
- Season support added
  - Play the first unwatched episode
    - If all episodes are watched, play the whole season starting from episode 1
  - Works from the home screen and series detail view
- Album support added
  - Play the whole album starting from track 1
  - Works from the home screen, music library view(when viewing albums), and music artist detail view
- Music artist support added
  - Shuffle all songs by found by the selected artist
  - Works from the home screen and music library view

## Issues
Fixes #1138
Fixes #1139

2023-09-17 00:21 UTC, sevenrats commented
there actually is a loading spinner in there.  or, at least there was, I haven't looked.  its implemented as a progressDialog where everything except the loading spinner has its visibility shut off.  it was working normally until the universal playslist changes.  all to say, it may just still be in there with the wrong z index or visibility

2023-09-17 00:24 UTC, sevenrats commented
parts of it are still in there it looks like: https://github.com/jellyfin/jellyfin-roku/blob/e11a563ec73e923ebb4d88ed4e5ac1199ea9682e/source/VideoPlayer.brs#L62

2023-09-17 00:47 UTC, 1hitsong commented
### Music Artists
Quick Play on Artist with no albums, only an Appears On credit, does not play anything. I expected it would play their appears on song.

### Music Album
Quick Play on Album from the Appears On section does not play anything. I expected it would play the album.

2023-09-17 01:21 UTC, cewert commented
@sevenrats added the spinner. Thanks for pointing out those functions 👍

2023-09-17 16:20 UTC, sevenrats commented
fair warning that progressDialog's such as this one block the back button.  in 99.9% of cases this is no big deal, and in the rest of cases, its a small deal, but, it is in line to get fixed.

2023-09-17 16:32 UTC, cewert commented
> fair warning that progressDialog's such as this one block the back button. in 99.9% of cases this is no big deal, and in the rest of cases, its a small deal, but, it is in line to get fixed.

I didn't notice that but that sounds perfect to me. We have no way of cancelling the quick play functions once they start and some are pretty long so disabling the back button makes a lot of sense to me.

May want to add a function parameter to allow the dev to control the back button behavior `sub startMediaLoadingSpinner(enableBackButton = false as boolean)`

2023-09-19 03:01 UTC, cewert commented
## Changes
- Add support for "Appears on" row when viewing music artist
- Fix music logic so that all songs are played when quick playing an artist or music library
  - Number of songs in playlist now matches the number of songs listed in the "Artist (Presentation)" view
- Optimize api quieries
  - To shuffle play all 1366 of the songs in my music library now takes ~3.8 seconds
- Add "collectionFolder" support
  - Supports `movies`, `tvshows`, `boxsets`, and `music` collection types
    - movies: shuffle play all movies found in collection
    - tvshows: shuffle play all watched episodes in collection
    - boxsets: pick a random boxset inside and play all the items inside
    - music: shuffle play all audio files in collection
  - Works from the "My Media" and favorite rows on the home page and also the main grid view
- Add "UserView "support
  - Supports `playlists` collection type
  - Picks a random playlist inside and shuffle plays it
  - Works from the "My Media" and favorite rows on the home page and also the main grid view
- Move quick play logic out of main and into it's own file under a namespace of `quickplay`

Besides pictures, which aren't ready for the global queue yet, I think this is everything.

@1hitsong the two things you mentioned should be fixed

2023-09-23 01:15 UTC, 1hitsong commented
### Home / My Media
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Movies | ✔️ |
| TV Show  | ✔️ |
| Music  | ❌ | Crashed Roku. Console shows: TotalRecordCount: 26082. <br>Are we limiting the number of items we retrieve? I believe WebUI limits to 200 |
| Collections | ✔️ |
| Live TV | ➖ | Does nothing, flashes black on the screen. Unknown collection type. |
| Music Videos | ➖ | Does nothing, flashes black on the screen. Unknown collection type. |
| Playlists  | ✔️ |
| Recordings | ➖ | Does nothing, flashes black on the screen. Unknown collection type. |

### Home / Continue Watching
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Movie  | ✔️ |
| TV Show  | ✔️ |

### Home / Next Up
| Function         | Test Result     | Details |
|--------------|-----------|--|
| TV Show  | ✔️ |

### Home / Favorites
| Function         | Test Result     | Details |
|--------------|-----------|--|
| TV Season  | ✔️ |
| TV Episode  | ✔️ |
| Movie  | ✔️ |

### Home / Latest in Movies
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Movie  | ✔️ |

### Home / Latest in TV Shows
| Function         | Test Result     | Details |
|--------------|-----------|--|
| TV Show  | ✔️ |

### Home / Latest in Music
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Album  | ✔️ |

### Home / On Now
| Function         | Test Result     | Details |
|--------------|-----------|--|
| TV Program  | ➖ | Does nothing, flashes black on the screen. Unknown collection type. |

### Home / Latest in Music Videos
| Function         | Test Result     | Details |
|--------------|-----------|--|
| TV Program  | ➖ | Popup - This type is not yet supported: MusicVideo.<br> This is unrelated to this PR. |

2023-09-23 01:37 UTC, 1hitsong commented
### Movie Library
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Movies (Presentation) | ✔️ |
| Movies (Grid) | ✔️ |
| Studio | ➖ | Does nothing, flashes black on the screen. Itemnode type is folder. |
| Genre / 6 selected movies | ❌ | Quickplay doesn't work on the films to the right of the genre collection image. No console log. |
| Genre / Collection image | ❌ | Quick doesn't work. Expected it to shuffle play all movies under genre |
| Genre / Genre View | ✔️ |

2023-09-23 01:45 UTC, cewert commented
Good call on limiting the music.. Thank you for breaking it lol. I'm thinking about testing with my 1300 files again and using one of the roku tools to measure ram usage. looks like the lowest ram for the devices we support is 512MB. I think it'd be best to base it on that instead of a random number. PCs have to share the CPU with other tasks but the roku will only be playing music so might as well fill up the ram with songs IMO. I also have the songs sorted by album before they get randomized so if if you turn off shuffle it lets you find more songs from the same album. At least it did for me because it loaded my whole library :smile: so that's another benefit of having as big of a playlist as possible.

I don't have TV setup but I'll try to find a free stream to test with. I should be able to find a music video to test with

Action list
- Limit music library songs
- live tv
- recording
- music video

2023-09-23 02:30 UTC, 1hitsong commented
### Music  Library
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Artists (Presentation) | ✔️ |
| Artists (Grid) | ✔️ |
| Album Artists (Presentation) | ✔️ |
| Album Artists (Grid) | ✔️ |
| Albums | ✔️ |
| Genres | ❌ | Quick play doesn't work. Expected it to shuffle play all songs under genre |
| Genres / Selected Genre / Album | ✔️ |
| Artists - With Albums | ✔️ |
| Artists - With only appears on | ✔️ |
| Artists - With only 1 song  | ❌ | Shows shuffle icon activated, but in all other instances we hide icon when only 1 song available|
| 1st click after changing the view setting | ❌ | After changing the view, quick play won't work until you press an arrow key or * |

2023-09-23 14:11 UTC, cewert commented
All of the red X's should be fixed with the exception of `1st click after changing the view setting` because I wasn't able to reproduce. Also added support for playing studios when viewing movie library

2023-09-23 19:14 UTC, 1hitsong commented
### Collections  Library
| Function         | Test Result     | Details |
|--------------|-----------|--|
| Collection | ✔️ |

2023-09-24 01:50 UTC, cewert commented
## Changes
- Fix regression on episode list view where quickplay was double firing and showing an error
- Remove memory checker
- Limit all queries to 2000 items
- Add quickplay support for type "Person"
  - Shuffle play all Videos, Movies, and watched Episodes found
  - Works from movie details and series details views
- Add quickiplay support for type "tvchannel"
  - Works from favorites on home page, livetv library channel view and livetv guide view
- Add quickplay support for "livetv" libraries on the My Media row
  - Select a random channel and watch it live

I'm not able to reproduce the TV library network bug or the movie library collection image bug you found.

I don't have access to guide data so I don't think I'll be able to add support for type "programs" or "recordings".

2023-09-24 02:04 UTC, sevenrats commented
does this code tolerate incomplete metadata?  we usually run into bugs related to that when we change this code. I will try to test tomorrow.

2023-09-24 02:22 UTC, cewert commented
> does this code tolerate incomplete metadata? we usually run into bugs related to that when we change this code. I will try to test tomorrow.

I don't understand your concern since we've tested this like crazy but as long as the itemNode that gets passed to main has a type and an id it will probably work.

2023-09-24 02:42 UTC, sevenrats commented
> > does this code tolerate incomplete metadata? we usually run into bugs related to that when we change this code. I will try to test tomorrow.
> 
> I don't understand your concern since we've tested this like crazy but as long as the itemNode that gets passed to main has a type and an id it will probably work.
what i will am afraid of and what i will do tomorrow is:
create a strm file that points to any video online. scan it in but don't play it yet. browse to it as if i were going to play it on the roku using these changes. if it is a problem it will amount to some isvalid checks somewhere

2023-09-24 03:03 UTC, cewert commented
Ahh yea I didn't test with a strm file. Thanks for testing 👍

2023-10-19 23:13 UTC, 1hitsong commented
Testing tables updated.

The two issues I mentioned are also still happening. Since you weren't able to reproduce them, I'll give it a quick look.

2023-10-19 23:58 UTC, 1hitsong requested changes

2023-10-19 23:58 UTC, 1hitsong commented on source/utils/quickplay.bs
> +            paramArray["genreIds"] = itemNode.id
I fixed the movie genre quickplay playing tv episodes by adding these lines below line 367.

```
            if isValid(itemNode.json.MovieCount) and itemNode.json.MovieCount > 0
                paramArray["includeItemTypes"] = "Movie"
            end if
```

2023-10-28 19:50 UTC, 1hitsong approved these changes

2023-10-28 21:25 UTC, merged