Fix early exit from settings screen
jellyfin-archive/jellyfin-roku-legacy pull request #1390
Opened 2023-09-24 02:18 UTC by cewert

While focused on the setting data form, hitting back or left would almost always exit the screen instead of navigating the settings tree as it should. This PR fixes that
## Changes
- Fix early exit from settings screen

2023-10-25 22:45 UTC, cewert commented
Not sure when this got introduced but I can reproduce this on unstable now.

2023-10-31 20:51 UTC, 1hitsong commented on components/settings/settings.brs
> +    if m.settingDetail.focusedChild <> invalid or m.radioSetting.hasFocus() or m.boolSetting.hasFocus() or m.integerSetting.hasFocus()
```suggestion
    if isValid(m.settingDetail.focusedChild) or m.radioSetting.hasFocus() or m.boolSetting.hasFocus() or m.integerSetting.hasFocus()
```

2023-10-31 20:55 UTC, 1hitsong requested changes

2023-10-31 20:55 UTC, 1hitsong commented on components/settings/settings.brs
> +    else if (key = "back" or key = "left") and isFormInFocus() = true
```suggestion
    else if (key = "back" or key = "left") and isFormInFocus()
```

2023-10-31 20:55 UTC, 1hitsong commented on components/settings/settings.brs
> +    if m.settingDetail.focusedChild <> invalid or m.radioSetting.hasFocus() or m.boolSetting.hasFocus() or m.integerSetting.hasFocus()
We're importing misc already, might as well use isValid() for new code.

2023-10-31 21:03 UTC, 1hitsong approved these changes

2023-10-31 21:03 UTC, merged