Respect Home Section settings from web
jellyfin-archive/jellyfin-roku-legacy pull request #1414
Opened 2023-10-14 02:03 UTC by 1hitsong

## Changes
Updates home view so the sections follow the settings from the web. This will causes the Roku home view to match the web home view except for Roku displaying the favorites row at the bottom, which is not an option on web.

There will be follow up PRs to allow users to set custom section settings on the Roku client. I separated them to limit scope for testing.

## Issues
Fixes #1385

2023-10-19 17:25 UTC, lakerssuperman commented
Just curious, would this affect things such as the default sort order for Collections?  The default on web is to show movies in a collection sorted by release date, but on Roku the default is alphabetical.  Each collection can be individually changed to sort by release date, but that can take awhile to do depending on number of collections.   Thanks!

This issue is referenced in [#391 ](https://github.com/jellyfin/jellyfin-roku/issues/391)

2023-10-19 17:47 UTC, 1hitsong commented
@lakerssuperman That's a separate issue and would need to be address in a different part of the code. This PR's goal is to make the sections on Roku match the sections setup on the server settings - except for Roku adding a Favorites section to the bottom, which is not an option in the web settings.

2023-10-19 21:31 UTC, lakerssuperman commented
> @lakerssuperman That's a separate issue and would need to be address in a different part of the code. This PR's goal is to make the sections on Roku match the sections setup on the server settings - except for Roku adding a Favorites section to the bottom, which is not an option in the web settings.

Roger Roger.  Thank you!

2023-10-22 00:08 UTC, cewert reviewed
Here's my notes from testing. Still need to look at the code.

Is your plan to support everything in the web client -> user settings -> Home section?

If so, these are the items that didn't work based on my testing:
- `My Media (small)` looked the same as `My Media`
- Duplicate section entries resulted in only the first entry being shown (I don't think this is an issue just mentioning it)
- `Default screen` does nothing for music, tvshow, and movie libraries (Live TV works)

2023-10-22 00:40 UTC, 1hitsong commented
> Is your plan to support everything in the web client -> user settings -> Home section?

Not as part of this PR. As you mentioned, the section `My Media (small)` hasn't been designed on Roku. We'll need to figure out what example this looks like. For now it's the same as the regular My Media. Also, Continue Reading is suppressed as we have no method for reading.

>Duplicate section entries resulted in only the first entry being shown (I don't think this is an issue just mentioning it)

I had to deal with this directly in code. Roku simply will not show a duplicated row. Try as I might to make it work, it never worked. So for this PR, I use the 1st instance only.

>Default screen does nothing for music, tvshow, and movie libraries (Live TV works)

That's outside the bounds of this PR. The goal is only to honor the home section selections and order.

2023-10-22 01:14 UTC, cewert requested changes

2023-10-22 01:14 UTC, cewert commented on components/config/ConfigList.brs
> +sub configList_show_dialog(configField)
Since you're already renaming this, can you make this lowerCamelCase instead of snake_case?

2023-10-22 01:14 UTC, cewert commented on components/home/HomeRows.brs
> +    ' consider home screen loaded when above rows are loaded
```suggestion
    ' consider home screen loaded when all rows are loaded
```

The `AppLaunchComplete` beacon is used in the automated testing mentioned in the chat recently. It used to get fired before the "Latest In" sections iirc. vs now where you have it at the bottom. This will negatively affect our load time score but it's hard to say how much because we can't test it right now and because the demo server would be used which doesn't have much data to load.

If possible, I think the best solution would be to fire the beacon after the first 2 rows are loaded - once everything "above the fold" is loaded.

2023-10-22 01:14 UTC, cewert commented on components/home/HomeRows.brs
> +sub createResumeRow(content as dynamic, sizeArray as dynamic)
If we plan on supporting "Continue listening" and "Continue Reading" one day then it would make sense to rename this. You would also need to change `continueRow`, `LoadContinueTask` and `updateContinueItems()`.

2023-10-22 01:14 UTC, cewert commented on components/home/HomeRows.brs
> +    end if
These used to be chained together so we ran `m.LoadContinueTask` and it updated them all but now you are only updating resume and next up.

`Latest In` and `Favorites` rows should also be updated. Maybe Live TV too? There are a few home sections I can't test so I'm not sure how they work exactly but we should be updating everything except the "My Media" row at least.

2023-10-22 01:14 UTC, cewert commented on source/api/userauth.brs
> +    if jsonResponse <> invalid and jsonResponse.CustomPrefs <> invalid
```suggestion
    if isValid(jsonResponse) and isValid(jsonResponse.CustomPrefs)
```

you imported misc so these can all be changed

2023-10-22 01:14 UTC, cewert commented on source/api/userauth.brs
> +        if jsonResponse.CustomPrefs["landing-livetv"] <> invalid
```suggestion
        if isValid(jsonResponse.CustomPrefs["landing-livetv"])
```

2023-10-22 01:14 UTC, cewert commented on source/api/userauth.brs
> +sub LoadUserHomeSections(customPrefs as object)
Should this be called `SaveUserHomeSections` instead since all it does is take an array of user settings and saves some to the registry/session?

PS: Looks like I missed `LoadUserPreferences()` when I setup the `session` namespace. Feel free to move all this in there if you prefer. Seems like it would fit under `session.user.Login()`

2023-10-22 01:14 UTC, cewert commented on source/api/userauth.brs
> +sub LoadUserHomeSections(customPrefs as object)
If you leave it here it needs a function definition

2023-10-22 01:14 UTC, cewert commented on components/home/HomeRows.brs
> +    m.homeSectionIndexes.AddReplace("count", m.homeSectionIndexes.count - 1)
```suggestion
    m.homeSectionIndexes.AddReplace("count", m.homeSectionIndexes.count--)
```

2023-10-22 01:14 UTC, cewert commented on components/home/HomeRows.brs
> +            m.homeSectionIndexes[section] = m.homeSectionIndexes[section] - 1
```suggestion
            m.homeSectionIndexes[section]--
```

2023-10-22 20:16 UTC, 1hitsong commented on components/home/HomeRows.brs
> +    ' consider home screen loaded when above rows are loaded
I went with checking if 2 sections with data are loaded, or if we reach the end of the web client data - in cases where someone may only have 1 row displayed.

2023-10-24 02:33 UTC, cewert commented on components/home/HomeRows.brs
> +    if not isValid(removedSectionIndex) then return
Won't this blow up if `m.homeSectionIndexes[sectionName]` is invalid?

```suggestion
    if isValid(m.homeSectionIndexes[sectionName])
        removedSectionIndex = m.homeSectionIndexes[sectionName]
    else
        return
    end if
```

2023-10-25 20:01 UTC, 1hitsong commented on components/home/HomeRows.brs
> +    if not isValid(removedSectionIndex) then return
I'm not following this one.

If `m.homeSectionIndexes[sectionName]` is invalid, then `removedSectionIndex` will be set to invalid, so the `isValid()` check on line 103 will exit the function.

If `sectionName` isn't found in `m.homeSectionIndexes`, then `removedSectionIndex` will be set to invalid, so the `isValid()` check on line 103 will exit the function.

2023-10-25 22:21 UTC, cewert commented on components/home/HomeRows.brs
> +    if not isValid(removedSectionIndex) then return
Yea you're right. My fault.

2023-10-25 22:22 UTC, cewert approved these changes

2023-10-25 22:30 UTC, merged