Add support for TV show season level extra features
jellyfin-archive/jellyfin-roku-legacy pull request #1416
Opened 2023-10-15 02:37 UTC by JarodTAerts

## Changes
Add ability to display and play TV Show Season level special features and extras via a button in the TVEpisodes component which toggles between episodes and extras. The Extras button only shows if there are extras present for the season and passed into the TVEpisodes component. Doing this required adding an extra call when loading a TV Show season where we fetch any special features for that season and pass them into the TVEpisodes component via a new interface along with a separate new interface to hold the episodes data. These two interfaces are then used to toggle the .objects data fed into the episodes picker when the Extras button is selected.

Also fixed a small bug where any non-episode content would fail to play from the TVEpisodes view due to the next up queue logic attempting to fire on it. 

## Testing
This was testing on my TVShows library that has seasons both with and without extras. Did following tests:
- Ran automated testing from VSCode
- Ran Jellyfin against my server, ensured playback of Movies and TV Shows worked as expected.
   - Opened TV season with extras and verified that the Extras button showed, toggled as expected, and was able to play extra content
   - Opened TV season without extras and verified the Extras button did not show.
   - Verified navigation in TVEpisodes component worked as expected with new Extras button.

To test this feature, you must have a TV Show season in your library which has extras features in the season directory as explained in following Jellyfin docs: https://jellyfin.org/docs/general/server/media/shows/#show-extras.

## Issues
https://github.com/jellyfin/jellyfin-roku/issues/1415

2023-10-15 13:05 UTC, sevenrats commented on source/api/Items.brs
> +function TVSeasonExtras(season_id as string) as dynamic
i know it isn't clear from look around the code, but we have recently started requiring function comments on all new functions (feel free to doc some old ones too lol).
here is an example
https://github.com/jellyfin/jellyfin-roku/blob/1465c620f9a0e15cfdcc23596fbd5637ce6d7a12/source/utils/misc.brs#L213

2023-10-15 13:11 UTC, sevenrats commented on components/tvshows/TVEpisodes.brs
> +    showExtras = isValid(m.top.extrasObjects) and (not m.top.extrasObjects.IsEmpty())
how would you feel about renaming this to doShowExtras or boolShowExtras to avoid the ambiguity of "should I show the extras" versus "extras of a show"

2023-10-15 17:51 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +    showExtras = isValid(m.top.extrasObjects) and (not m.top.extrasObjects.IsEmpty())
`showHasExtras` or `showExtrasButton` sound good to me

2023-10-15 17:53 UTC, sevenrats commented on components/tvshows/TVEpisodes.brs
> +    showExtras = isValid(m.top.extrasObjects) and (not m.top.extrasObjects.IsEmpty())
the hardest part of programming is naming things.

2023-10-15 18:09 UTC, cewert requested changes
Gave the code a quick look. I'll test this when I get some time. I don't have any shows with extras so I'll need to set something up.

2023-10-15 18:09 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +    m.Extras = m.top.findNode("Extras")
Can you change this var to be lower case please?

I know our code isn't great when it comes to standardizing these things but we're pretty good about using lowerCamelCase for vars (although we still haven't updated the rest of the codebase). Files are mostly PascalCase and function names are kind of a mess and use both lowerCamelCase and PascalCase so feel free to take your pick.

2023-10-15 18:09 UTC, cewert commented on components/tvshows/TVEpisodes.xml
> +    <JFButton id="Extras" minChars="10" text="Extras" translation="[90, 740]" visible="false"></JFButton>
Same thing here. Can you change this to lowercase please?

2023-10-15 18:09 UTC, cewert commented on source/api/Items.brs
> +function TVSeasonExtras(season_id as string) as dynamic
Can you change season_id from snake case to lowerCamelCase please?

2023-10-15 18:18 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +        m.Extras.visible = true
This may not matter but just an FYI... when the button is not visible it will still consume space in the GUI similar to `visibility: hidden` in CSS.

2023-10-15 18:21 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +    showExtras = isValid(m.top.extrasObjects) and (not m.top.extrasObjects.IsEmpty())
`There are 2 hard problems in computer science: cache invalidation, naming things, and off-by-1 errors.` 😆

2023-10-15 18:54 UTC, 1hitsong requested changes

2023-10-15 18:54 UTC, 1hitsong commented on source/api/Items.brs
> +    url = Substitute("/Users/{0}/Items/{1}/SpecialFeatures", m.global.session.user.id, season_id)
Let's use the SDK. Import it at the top of the file

`import "pkg:/source/api/sdk.bs"`

```suggestion
    data = api.users.GetSpecialFeatures(m.global.session.user.id, season_id)
```

2023-10-15 18:54 UTC, 1hitsong commented on source/api/Items.brs
> +    if data = invalid then return invalid
```suggestion
    if not isValid(data) then return invalid
```

2023-10-15 18:54 UTC, 1hitsong commented on source/api/Items.brs
> +        if tmp.image <> invalid
```suggestion
        tmp = CreateObject("roSGNode", "TVEpisodeData")
        tmp.image = PosterImage(item.id, { "maxWidth": 400, "maxheight": 250 })
        if isValid(tmp.image)
```

2023-10-15 18:54 UTC, 1hitsong commented on source/api/Items.brs
> +        if tmpMetaData <> invalid and tmpMetaData.overview <> invalid
```suggestion
        if isValid(tmpMetaData) and isValid(tmpMetaData.overview)
```

2023-10-15 18:54 UTC, 1hitsong commented on source/api/Items.brs
> +    return extrasData
```suggestion
    return { Items: results }
```

2023-10-15 18:54 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +    if showExtras and key = "up" and (m.Extras.hasFocus())
There's no need for the showExtras variable. We can determine if it applies by checking the visibility of the button.
```suggestion
    if m.Extras.visible and key = "up" and (m.Extras.hasFocus())
```

2023-10-15 18:54 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +    if showExtras and key = "down" and (m.Shuffle.hasFocus())
```suggestion
    if m.Extras.visible and key = "down" and (m.Shuffle.hasFocus())
```

2023-10-15 18:54 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +        if showExtras and m.Extras.hasFocus()
```suggestion
        if m.Extras.visible and m.Extras.hasFocus()
```

2023-10-15 18:54 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +            if m.Extras.text.trim() = "Extras"
We use the Roku translation files for any displayed text, so these conditions must check against the translations. Also, all string comparisons must force case.

You'll need to add both Episodes and Extras to the translation file: `C:\Users\tgpo\Documents\code\jellyfin-roku\locale\en_US\translations.ts`

```suggestion
            if LCase(m.Extras.text.trim()) = LCase(tr("Extras"))
```

2023-10-15 18:54 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +                m.Extras.text = "Episodes"
```suggestion
                m.Extras.text = tr("Episodes")
```

2023-10-15 18:54 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +                m.Extras.text = "Extras"
```suggestion
                m.Extras.text = tr("Extras")
```

2023-10-15 19:15 UTC, 1hitsong commented
Functionality wise, this works great.

2023-10-15 19:56 UTC, JarodTAerts commented on source/api/Items.brs
> +function TVSeasonExtras(season_id as string) as dynamic
Sounds good, will make sure this and all functions I touched here are have comments.

2023-10-15 19:56 UTC, JarodTAerts commented on components/tvshows/TVEpisodes.brs
> +    showExtras = isValid(m.top.extrasObjects) and (not m.top.extrasObjects.IsEmpty())
Agreed, will roll with `showExtrasButton`

2023-10-15 19:57 UTC, JarodTAerts commented on components/tvshows/TVEpisodes.brs
> +    m.Extras = m.top.findNode("Extras")
Will do, I am a C# guy by trade so will roll with UpperCamel functions and lowerCamel functions 🙂

2023-10-15 20:39 UTC, JarodTAerts commented on components/tvshows/TVEpisodes.brs
> +    showExtras = isValid(m.top.extrasObjects) and (not m.top.extrasObjects.IsEmpty())
Actually removing this variable altogether in favor of suggestion to use the visibility of Extras button to show if extras are avaliable.

2023-10-17 01:38 UTC, JarodTAerts commented on components/tvshows/TVEpisodes.xml
> +    <JFButton id="Extras" minChars="10" text="Extras" translation="[90, 740]" visible="false"></JFButton>
Also changed shuffle id in this class to keep things consistent

2023-10-20 00:45 UTC, JarodTAerts commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
This content is autoformatting to add the extra tab which is technically the correct xml format. This commit (https://github.com/jellyfin/jellyfin-roku/commit/2051a8fbbede94e805796b31b8ac533f6f162697) switched removed that tab. If wanted, I can remove the tab, but since it is auto-formatting with it I felt it made sense to keep it.

2023-10-20 01:41 UTC, cewert commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
Nice catch.

Since it's by weblate, I would normally say leave it because weblate is in charge of committing new translations but this is a "translation" of the english file which doesn't make any sense to me because the whole file is already in english. The only file we are supposed to manually edit is the english file. Then the other files get automatically created and updated by weblate which then get imported by the roku app (at least the 7ish locales that are supprted by roku). 

@anthonylavado is there a valid use case for users to edit our english weblate file online or should we lock that down so users can't change things on us? I don't know what exactly he changed but if any of the source strings get changed then all the code that calls that source string would need to be changed too.

2023-10-20 03:01 UTC, JarodTAerts commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
So, I had only touched this file based on the comment from @1hitsong who mentioned I would need to add all user facing strings to it so they could be localized correctly. After the commit I linked above, there were merge conflicts which I had to resolve, but the autoformatting of vscode/the solution added back the tab that was removed in that commit. I think I need at least those two strings "Episodes" and "Extras" added to the translations file, but I can find a way to remove the tab and get rid of the excessive diff.

> You'll need to add both Episodes and Extras to the translation file: C:\Users\tgpo\Documents\code\jellyfin-roku\locale\en_US\translations.ts

2023-10-20 03:09 UTC, JarodTAerts commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
Is there a different file where I should actually put these translations?

2023-10-22 13:13 UTC, cewert commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
> Is there a different file where I should actually put these translations?

No, you put them in the right file. You did great. I'm just questioning why that commit came from weblate in the first place.

2023-10-22 13:21 UTC, cewert commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
I opened up that commit locally so I could see the diff. I still don't understand the changes. 

Some of the changes are flagging things as `unfinished` which doesn't make sense since the translation string matches the source string:
![weblate-english1](https://github.com/jellyfin/jellyfin-roku/assets/16514652/4d7dc5a5-b6fb-4aea-8b04-24b69b1098f2)

The rest of the file has changes like this where he changed single quotes to use `&apos;` instead.
![weblate-english2](https://github.com/jellyfin/jellyfin-roku/assets/16514652/f099bb93-6ed5-4bb8-84a1-0a1a7880588b)

2023-10-22 14:28 UTC, JarodTAerts commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
Yeah, it does not make too much sense. Wonder if it makes sense to revert that commit? Seems like some parts, like the "unfinished", could cause issues with any release. As for my changes. I will probably make sure I match what existing in unstable right now and just add my two new items if that sounds good.

2023-10-22 15:57 UTC, cewert commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
Yea, let's just revert the us translation commit.

Worst case, it breaks some translation strings. Best case, the single quote stuff doesn't matter and we have to manually undo the `unfinished` changes. 

I don't see a reason to keep it. If the single quotes need changed for some reason, then that should be done in a PR so that reason can be explained.

2023-10-24 23:38 UTC, JarodTAerts commented on locale/en_US/translations.ts
> +    <defaultcodec>UTF-8</defaultcodec>
Made PR to revert the translation commit here: https://github.com/jellyfin/jellyfin-roku/pull/1432. After that goes in I can repull the us translation file and add just my two additional items. Thanks for the help figuring this out!

2023-10-25 16:29 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +        m.Extras.visible = true
```suggestion
        m.extras.visible = true
```

2023-10-25 16:30 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +    if key = "right" and (m.shuffle.hasFocus() or m.Extras.hasFocus())
```suggestion
    if key = "right" and (m.shuffle.hasFocus() or m.extras.hasFocus())
```

2023-10-25 16:30 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +    if m.extras.visible and key = "up" and (m.Extras.hasFocus())
```suggestion
    if m.extras.visible and key = "up" and (m.extras.hasFocus())
```

2023-10-25 16:31 UTC, cewert commented on components/tvshows/TVEpisodes.brs
> +        m.Extras.setFocus(true)
```suggestion
        m.extras.setFocus(true)
```

2023-10-26 03:22 UTC, JarodTAerts commented on components/tvshows/TVEpisodes.brs
> +        m.Extras.visible = true
Thanks for catching and sorry about this. Was working while on vacation and away from my test device so hadn't run it. Fixed these and will test again soon when able.

2023-10-26 11:44 UTC, 1hitsong commented
Functionality still working well.

2023-10-26 15:48 UTC, cewert approved these changes

2023-10-26 15:55 UTC, 1hitsong requested changes

2023-10-26 15:55 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +    if m.extras.visible and key = "up" and (m.extras.hasFocus())
```suggestion
    if m.extras.visible and key = "up" and m.extras.hasFocus()
```

2023-10-26 15:55 UTC, 1hitsong commented on components/tvshows/TVEpisodes.brs
> +    if m.extras.visible and key = "down" and (m.shuffle.hasFocus())
```suggestion
    if m.extras.visible and key = "down" and m.shuffle.hasFocus()
```

2023-10-26 17:21 UTC, 1hitsong approved these changes

2023-10-26 17:22 UTC, merged