Search fix - using the Users/Items api instead of Search Hints.
jellyfin-archive/jellyfin-roku-legacy pull request #1453
Opened 2023-10-28 22:07 UTC by matty-r

## Changes
Adjusts the search query to use the Users/{userid}/Items api instead.

## Issues
Fixes #1029

2023-10-28 22:37 UTC, 1hitsong commented
This works great.

Since you're already updating the API endpoint, we might as well go ahead and convert it to use the SDK.

2023-10-28 22:41 UTC, 1hitsong requested changes

2023-10-28 22:41 UTC, 1hitsong commented on source/api/Items.brs
> +        resp = APIRequest(Substitute("Users/{0}/Items", m.global.session.user.id), {
Let's go ahead and use the SDK since you're already changing the endpoint.

```
        data = api.users.GetItemsByQuery(m.global.session.user.id, {
            "searchTerm": query,
            "IncludePeople": true,
            "IncludeMedia": true,
            "IncludeShows": true,
            "IncludeGenres": true,
            "IncludeStudios": true,
            "IncludeArtists": true,
            "IncludeItemTypes": "LiveTvChannel,Movie,BoxSet,Series,Episode,Video,Person,Audio,MusicAlbum,MusicArtist,Playlist",
            "EnableTotalRecordCount": false,
            "ImageTypeLimit": 1,
            "Recursive": true,
            "limit": 100
        })
```

2023-10-28 23:11 UTC, 1hitsong approved these changes

2023-10-29 00:39 UTC, cewert approved these changes

2023-10-29 22:24 UTC, merged