Add quickplay support to search results
jellyfin-archive/jellyfin-roku-legacy pull request #1456
Opened 2023-10-29 02:39 UTC by cewert

## Changes
- Observe `quickPlayNode` and update it with the focused item when play is pressed

## Issues
Fixes #1455

2023-10-29 14:51 UTC, 1hitsong requested changes

2023-10-29 14:51 UTC, 1hitsong commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
```suggestion
        if isValid(m.searchSelect.rowItemFocused) and m.searchSelect.rowItemFocused.count() > 0
```

2023-10-29 14:51 UTC, 1hitsong commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
1. Continuing our move to isValid()
2. There's a path to an exception if we don't check the count() value. You can recreate this by searching for something that returns no results, press right until your cursor leaves the keyboard. It's technically in the search results area, but we're showing no results. Press play and it'll throw the exception. Testing the count is > 0 fixes it.

2023-10-29 17:29 UTC, roidy commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
> 2. There's a path to an exception if we don't check the count() value. You can recreate this by searching for something that returns no results, press right until your cursor leaves the keyboard. It's technically in the search results area, but we're showing no results. Press play and it'll throw the exception. Testing the count is > 0 fixes it.

Would it be better to put the count > 0 check  on line 60 to prevent the user ever leaving the keyboard if there are no results? Being able to leave the keyboard to an empty row seems like a bug and shouldn't be possible.

2023-10-29 19:13 UTC, cewert commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
> 1. Continuing our move to isValid()
> 
>     2. There's a path to an exception if we don't check the count() value. You can recreate this by searching for something that returns no results, press right until your cursor leaves the keyboard. It's technically in the search results area, but we're showing no results. Press play and it'll throw the exception. Testing the count is > 0 fixes it.

1. I was only using isValid() if the file had already imported misc.brs. Otherwise I would feel obligated to fix the rest of the file and things get out of scope.
2. I liked @roidy suggestion but that code didn't work on line 60. Instead I'm using `m.searchHelpText.visible` to see if the results are ready for focus. Let me know what you think

2023-10-29 19:24 UTC, cewert commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
I'm using `m.searchSelect.itemdata.TotalRecordCount` to check the state of the search results now which seems to work great. Focus can only leave the keyboard when `TotalRecordCount > 0`.

2023-10-29 20:00 UTC, roidy commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
I see you've found a solution, I was going to suggest `m.searchSelect.content.getChildCount() > 0`

2023-10-30 18:35 UTC, 1hitsong requested changes

2023-10-30 18:35 UTC, 1hitsong commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
I vote we do both, prevent moving focus and testing the variable.

We've seen oh so many weird issues with focus on Roku and issues in the bug reports that technically shouldn't be possible. I think best practice should be to ensure the value exists instead of assuming it exists, even if we have code elsewhere that should prevent the circumstance from occurring.

2023-10-31 18:21 UTC, 1hitsong requested changes
Found another exception path.

1. Go to search
2. Type something that gets results
3. Navigate to search result - just hover over, don't click on it
4. Navigate back to keyboard and type garbage so results go away
5. Press Play button on remote

2023-10-31 19:16 UTC, 1hitsong requested changes

2023-10-31 19:16 UTC, 1hitsong commented on components/search/SearchResults.brs
> +    else if key = "play" and m.searchSelect.isinFocusChain() and m.searchSelect.rowItemFocused.count() > 0
Found another exception path.

1. Press mic button and say some letters that will return nothing
2. After to let go of the button, but before it updates the results, quickly press right
3. This will move the cursor into the search results section with no results
4. Press play, exception thrown

2023-10-31 19:28 UTC, cewert commented on components/search/SearchResults.brs
> +        if m.searchSelect.rowItemFocused <> invalid
> m.searchSelect.content.getChildCount() > 0

@roidy I ended up using this solution so thank you for the suggestion! This was more reliable since the itemData wasn't always getting cleared out when the results got cleared.

2023-10-31 19:30 UTC, cewert commented on components/search/SearchResults.brs
> +    else if key = "play" and m.searchSelect.isinFocusChain() and m.searchSelect.rowItemFocused.count() > 0
Using @roidy solution now which checks the child count of content instead of relying on the api data.

2023-10-31 19:30 UTC, roidy commented on components/search/SearchResults.brs
> +    else if key = "play" and m.searchSelect.isinFocusChain() and m.searchSelect.rowItemFocused.count() > 0
I think it should be `m.searchSelect.content.getChildCount() > 0` not `m.searchSelect.itemdata.TotalRecordCount > 0`

I've tested and using getChildCount I can't enter the search results until they are populated with content, regardless of weather I'm using the keyboard or voice.

2023-10-31 20:36 UTC, 1hitsong approved these changes

2023-10-31 21:05 UTC, merged