Create pause menu
jellyfin-archive/jellyfin-roku-legacy pull request #1461
Opened 2023-10-31 14:20 UTC by 1hitsong

## Changes
Creates a menu displayed when the user pauses playback of a video. **The trickplay bar is no longer shown.** This changes current behavior. The trickplay bar is still accessed by pressing left, right, rewind, or fast forward on the remote while the video is playing.

The menu has 3 buttons: 
1. List of all found chapters with current chapter in focus
2. Previous chapter
3. Next Chapter

The menu is designed to handle more icons and functions in the future.

If user tries to go before chapter 1, it simply replays the chapter from the start. User can not go beyond last chapter, instruction is ignored.

Chapter names are used in the list, so if user has a chapter named "It's All Over" instead of "Chapter 1," "It's All Over" will be displayed.

If no chapter data is found, buttons are still displayed, but are inactive. Chapter list displays "No chapter data found" and is also inactive.

## Issues
Fixes #445

## Notes
This PR uses a param introduced in Roku OS 10, video.seekMode. This param is needed to make the chapter selection accurate.

2023-10-31 17:39 UTC, lakerssuperman commented
Wow.  This looks awesome!  Special points for include a A Nightmare on Elm Street Part 2 screenshot!

2023-11-04 01:49 UTC, cewert requested changes

2023-11-04 01:49 UTC, cewert commented on components/video/PauseMenu.brs
> +
New files should be `.bs`

2023-11-04 19:37 UTC, cewert commented
The code looks good.

Right now the next chapter buttons are called `previous` and `next` but maybe we should rename them to `previous-chapter` and `next-chapter`? Eventually we will need icons for previous item(in playlist) and next item too.

2023-11-07 14:54 UTC, cewert requested changes

2023-11-07 14:54 UTC, cewert commented on components/Clock.xml
> +<component name="Clock" extends="Group" initialFocus="chapterNext">
```suggestion
<component name="Clock" extends="Group">
```

This looks like a leftover from a copy/paste

2023-11-10 23:48 UTC, cewert approved these changes
Works great. Nice job on this 👍

2023-11-10 23:50 UTC, merged