create generic task for posting data. wait for response code
jellyfin-archive/jellyfin-roku-legacy pull request #1462
Opened 2023-10-31 21:00 UTC by cewert

Create a general PostTask for posting data using the task thread. Use it for posting the device profile to the server. Convert Home and Settings to extend JFScreen. Override JFScreen methods to simplify code and post device profile

## Changes
- Create generic `PostTask.xml` to post data using the task thread
- Convert `Home.xml` and `Settings.xml` to extend `JFScreen` instead of `JFGroup`
- Create `OnScreenShown()` hook for `Home`
  - Refresh the data on the page
  - The first time the `Home` screen is shown, post device profile to server using PostTask
- Create `OnScreenHidden()` hook for `Settings`
  - Assume settings were changed and the device profile needs to be updated
    - Post device profile to server using PostTask
- When returning from screensaver, always run `OnScreenShown()` if group is a `JFScreen`

2023-10-31 21:19 UTC, 1hitsong requested changes

2023-10-31 21:19 UTC, 1hitsong commented on components/tasks/PostTask.bs
> +    if m.top.apiUrl <> ""
Let's exit early instead of having such a long if statement.

```
if m.top.apiUrl = ""
    print "ERROR in PostTask. Invalid API URL provided
    return
end if
```

2023-10-31 21:19 UTC, 1hitsong commented on components/tasks/PostTask.bs
> +    if respString <> invalid and respString <> ""
Let's go ahead and import misc and use isValidAndNotEmpty()

```suggestion
    if isValidAndNotEmpty(respString)
```

2023-10-31 21:19 UTC, 1hitsong commented on components/home/Home.brs
> +    if m.top.lastFocus <> invalid
```suggestion
    if isValid(m.top.lastFocus)
```

2023-10-31 21:19 UTC, 1hitsong commented on components/data/SceneManager.brs
> +        if group.subtype() = "JFScreen"
```suggestion
        if LCase(group.subtype()) = "jfscreen"

```

2023-10-31 21:19 UTC, 1hitsong commented on components/home/Home.brs
> +sub OnScreenShown()
Needs function definition.

2023-10-31 21:19 UTC, 1hitsong commented on components/home/Home.brs
> +sub postFinished()
Needs function definition.

2023-10-31 21:19 UTC, 1hitsong commented on components/settings/settings.brs
> +sub OnScreenHidden()
Needs function definition.

2023-10-31 21:19 UTC, 1hitsong commented on components/settings/settings.brs
> +sub postFinished()
Needs function definition.

2023-10-31 21:19 UTC, 1hitsong commented on components/tasks/PostTask.bs
> +sub init()
Needs function definition.

2023-10-31 21:19 UTC, 1hitsong commented on components/tasks/PostTask.bs
> +sub postItems()
Needs function definition.

2023-11-01 03:34 UTC, cewert commented on components/tasks/PostTask.bs
> +sub init()
For init()? We've never really done that

2023-11-01 10:16 UTC, 1hitsong commented on components/tasks/PostTask.bs
> +sub init()
Oh, yeah. I was just pasting it on all functions without a comment.

init() is likely overkill, but is there any benefit for the new documentation from adding one? Such as a brief description of the component - it's purpose, it's intended use, etc.

2023-11-01 13:46 UTC, cewert commented on components/tasks/PostTask.bs
> +sub init()
I think there is value in adding that information to the docs/files but I don't think `init()` is the best place for it.

Take the [AlbumView](https://jellyfin.github.io/jellyfin-roku/module-AlbumView.html) for example. Ideally the info we're talking about should be at the top of the page near `AlbumView` but instead it would end up in the middle of the page where `init()` happens to be in the list of functions. Making it unclear if we are talking about the file or the function.

All that said, I don't have a better solution and I'm not an expert with jsdoc so it's possible there is some kind of built in way of describing a file. This seems to be a limitation of using jsdocs for brighterscript to me or at least a limitation of the jsdoc extension we're using. This would probably work the way we want if all of our code used classes since javascript uses classes and [supports describing them](https://cancerberosgx.github.io/jsdoc-templates-demo/demo/ink-docstrap/Alive.html) the way we're talking about.

Eventually, we will have to modify the jsdoc extension that we're using so that namespaces get parsed correctly (assuming jsdoc works well for us and we use it long term). Maybe this is something we add on to the list of things to fix when the time comes? We could add a custom @file param or something to the top of the file that gets parsed the way we want.

2023-11-01 14:26 UTC, cewert commented on components/tasks/PostTask.bs
> +sub init()
So jsdoc has a [file tag](https://jsdoc.app/tags-file.html) to describe the file like we want which is the good news `@file (synonyms: @fileoverview, @overview)`

The bad news is I just tested it and instead of the module page getting the description, the home page gets updated with an entry for the module/file with the description 🤔

![jsdoc-file](https://github.com/jellyfin/jellyfin-roku/assets/16514652/f6600ea4-b4fe-4dba-9627-52e7f51de1f9)
![posttask-doc-sample](https://github.com/jellyfin/jellyfin-roku/assets/16514652/8016aad9-25cc-48e7-a7b5-ea7de89292ec)

Maybe this would work with a different theme? My requirements were dark theme that worked with the github action I was using. Maybe the light themes are better? 🥲

2023-11-11 00:12 UTC, 1hitsong approved these changes

2023-11-11 00:12 UTC, 1hitsong commented on components/home/Home.brs
> +' Used to update the foces, the state of the data, and tells the server about the device profile
```suggestion
' Used to update the focus, the state of the data, and tells the server about the device profile
```

2023-11-11 00:29 UTC, merged