Remove overhang logo and user when viewing media
jellyfin-archive/jellyfin-roku-legacy pull request #1514
Opened 2023-11-18 20:00 UTC by cewert

### Why remove the logo?
Branding is good but too much branding is bad. At the very minimum, the user will still see the logo on the home screen of the app as well as the server and user select screens. This just removes the logo from screens that display media (the home screen shows media too but is more of a dashboard) to allow the focus to be on the media itself. The user knows what app they are using at this point.

### Why remove the user?
As mentioned above, the home screen is basically the dashboard for the app and this is the one screen where the currently logged in user is shown. If the user ever isn't sure who is the logged in user, then can navigate to the home screen. This also allows more focus to be on the media itself while viewing it.

Before:
![unstable-logo](https://github.com/jellyfin/jellyfin-roku/assets/16514652/c9ad731f-52b8-4c11-9466-5894a9b2c51a)

After:
![remove-logo](https://github.com/jellyfin/jellyfin-roku/assets/16514652/acd17e55-b566-484b-9889-e1c039390d22)

## Changes
- Crop logo images to remove wasted space around the image
- Add overhang logo to "left group"
- Hide overhang logo and user when navigating away from the home screen

2023-11-18 20:07 UTC, cewert commented
It looks like the image quality went down a bit when I cropped these in paint 😁 We should recreate the images from the SVG sources.

2023-11-20 01:47 UTC, sevenrats commented
this is also more in line with web, which is nice.
do you mind attaching a screenshot of the home screen with the modified logo?

2024-01-09 01:29 UTC, 1hitsong requested changes

2024-01-09 01:29 UTC, 1hitsong commented on source/utils/misc.bs
> +    logoPoster.width = "270"
These are the old height and width values, not the new cropped values.

2024-01-09 01:29 UTC, 1hitsong commented on components/JFOverhang.xml
> +      <Poster id="overlayLogo" uri="pkg:/images/logo.png" height="66" />
The logo looks stretched horizontally. I had to add the width of 191 to make the image look normal.

2024-01-09 01:29 UTC, 1hitsong commented on components/config/SetServerScreen.bs
> +' Used to show logo, update the focus, the state of the data, and tells the server about the device profile.
Event handler function descriptions should describe the event being handled, not the functionality it contains. This prevents function descriptions from becoming stale or overloaded.

2024-01-09 01:29 UTC, 1hitsong commented on components/home/Home.bs
> +' Used to show logo, update the focus, the state of the data, and tells the server about the device profile.
Event handler function descriptions should describe the event being handled, not the functionality it contains. This prevents function descriptions from becoming stale or overloaded.

2024-01-09 01:29 UTC, 1hitsong commented on components/home/Home.bs
> +sub OnScreenHidden()
Event handler function descriptions should describe the event being handled, not the functionality it contains. This prevents function descriptions from becoming stale or overloaded.

2024-01-09 01:29 UTC, 1hitsong commented on components/login/UserSelect.bs
> +sub OnScreenShown()
Event handler function descriptions should describe the event being handled, not the functionality it contains. This prevents function descriptions from becoming stale or overloaded.

2024-01-13 18:25 UTC, 1hitsong requested changes
Functionality looks good now. 1 small code style change.

2024-01-13 18:25 UTC, 1hitsong commented on components/home/HomeRows.bs
> +        end if
We can simplify and remove the else clause.

```
if not isValid(sectionname) then exit for

sectionName = LCase(sectionName)
```

2024-02-08 00:53 UTC, 1hitsong approved these changes

2024-02-08 22:48 UTC, merged