Use more loading spinners when selecting media with the OK button
jellyfin-archive/jellyfin-roku-legacy pull request #1515
Opened 2023-11-18 22:59 UTC by cewert

## Changes
- Use loading spinners for `selectedItem` node events in main loop
- Rearrange things a bit in `CreateSeasonDetailsGroupByID()` so that the loading spinner goes away when the episodes are loaded instead of waiting on the extras/specials logic to finish

2023-11-20 18:13 UTC, sevenrats commented
just noting here what we discussed in chat, this does not mitigate the black screen that results from slow remote backends.

2023-11-22 02:27 UTC, cewert commented
I pretty much redid this whole PR and updated the OP. Added the main logic to JFScene, using 2 booleans on JFScene instead of the 4 component functions, and I added a `stopLoadingSpinner()` to every main screne when it was done loading data. I also converted all the current custom spinners to use the new JFScene one instead. Our whole app uses one spinner now that can be toggled by using `startLoadingSpinner()` and `stopLoadingSpinner()`.

2023-11-22 13:11 UTC, 1hitsong requested changes
1 small code style change.

2023-11-22 13:11 UTC, 1hitsong commented on components/JFScene.bs
> +    if m.top.isLoading
```suggestion
    m.spinner.visible = m.top.isLoading
```

2023-11-22 13:16 UTC, 1hitsong commented
There's still an old spinner ref on line 553 of `components\ItemGrid\MusicLibraryView.bs`

2023-11-22 13:20 UTC, 1hitsong commented
Inside `Main.bs` there are still 5 references to m.spinner. The ones without isValid checks are throwing errors, then ones with isValid checks simply aren't showing spinners.

2023-11-22 14:09 UTC, cewert commented
## Changes
- Addressed reviewer feedback
- Fixed all remaining custom spinner references/bugs
- Added the spinner to a few more things triggered from the main loop (selecting a series, season, album etc.)
- Stop showing the spinner a little earlier on audio player view.

2023-11-22 21:35 UTC, 1hitsong commented
I have 1 photo in my photo library. Clicking on it results in an infinite spinner that never goes away.

2023-11-22 21:40 UTC, 1hitsong commented
I pressed Play on the Recordings Library. Nothing loaded and I'm again stuck on an infinite spinner.

2023-11-22 23:32 UTC, sevenrats commented
this now does fix the missing spinner, but that spinner is behind some darkening left over from the progressDialog for some reason.  This is not the end of the world but it would be better to fix it somehow.
cewert when you have some time, please let me know how you feel about a solution like this one:
https://github.com/cewert/jellyfin-roku/pull/6/files

2023-11-22 23:54 UTC, sevenrats commented
also just noticed that there is still no spinner between episodes

2023-11-24 23:38 UTC, 1hitsong commented
> I pressed Play on the Recordings Library. Nothing loaded and I'm again stuck on an infinite spinner.

This issue is still occurring. All my other issues are resolved.

2023-11-25 03:13 UTC, cewert commented
## Changes
- Running `stopLoadingSpinner()` whenever quickplay api quieries are invalid or there are 0 items returned.
- Don't assume item type - Copy recording library logic fix from refactored new function in  #1531

2023-11-28 19:42 UTC, 1hitsong requested changes

2023-11-28 19:42 UTC, 1hitsong commented on source/utils/quickplay.bs
> +                if tvshowsData.items[0].Type = "Series"
```suggestion
                if LCase(tvshowsData.items[0].Type) = "series"
```

2023-11-30 01:21 UTC, 1hitsong approved these changes

2023-11-30 01:21 UTC, merged