Fix home image size
jellyfin-archive/jellyfin-roku-legacy pull request #1530
Opened 2023-11-22 14:35 UTC by 1hitsong

## Changes
Fixes logic for home section image sizes

## Issues
Fixes #1493

2023-11-22 22:18 UTC, cewert requested changes
The main nasty bug was fixed but there is a new focus bug. When hitting back to return to the home screen, focus is always at the top row(my media for me) instead of the row you came from.

2023-11-23 17:09 UTC, cewert commented
Adding this here so we don't forget... We talked in chat about using brighterscript constants or enums for the different items size arrays. There are 3 I think:
- [ ] Wide poster
- [ ] Movie poster
- [ ] Music album

2023-11-25 03:55 UTC, cewert requested changes

2023-11-25 03:55 UTC, cewert commented on components/home/HomeRows.bs
> +    m.loadingTimer.repeat = true
shouldn't repeat be false?
- there's no guarantee that the timers stop call gets made at line 539 so it's possible this just runs forever
- if the stop call takes say 5 seconds to run, then this would have repeated 5 times and stopped the loading spinner 5 times. I think once is plenty unless you are restarting the spinner every second somewhere and I'm missing it

2023-11-25 03:55 UTC, cewert commented on components/ImageSizes.bs
> +namespace imageSizes
1. Does this file need live in the `components/` folder? I think it would make more sense in `source/`.
2. Should we just create a generic `constants` file instead of having a separate file for each group? I think that would be easier in the future once we start using more constants
3. We should also add a jsdoc comment for the file. I've been using `@fileoverview` but `@file` and `@overview` also work.

2023-11-25 03:55 UTC, cewert commented on components/home/HomeRows.bs
> +        itemRow = m.top.content.getChild(m.top.rowItemSelected[0])
we need to add `isValidAndNotEmpty()` check somewhere for `m.top.rowItemSelected`

2023-11-25 03:55 UTC, cewert commented on settings/settings.json
> +                        "default": "false"
I thought we were wanting this true for new users but with a migration for current installs? We were talking about defaults using web clients settings if possible by default with client side overrides

2023-11-25 03:55 UTC, cewert commented on source/utils/session.bs
> +
I would prefer if we'd keep all the migration logic in `migrations.bs`. That way current users upgrading run the code once vs all new installs running this slice of code every time. Plus didn't we want to have default enabled so new installs would have things default to web client settings with overrides in roku user settings?

You'd set default to true, but during 2.0.0 migration, you set all current users found in registry to false (all registry sections besides the main "Jellyfin" section hold user settings with the name of each section being the userid.)

2023-11-25 03:55 UTC, cewert commented on locale/en_US/translations.ts
> +            <source>Use Web's Home Section Arrangement</source>
Maybe these should say "Web client" instead of just web? more explicit and sounds better IMO

2023-11-25 12:19 UTC, 1hitsong commented on components/home/HomeRows.bs
> +    m.loadingTimer.repeat = true
Nice catch. This was not intentional. Bad copy, distracted paste.

The timer will only run once and has the possibility of ending early. It's essentially our last call clean up routine so the user doesn't get stuck.

2023-11-25 12:56 UTC, 1hitsong commented on components/ImageSizes.bs
> +namespace imageSizes
> Does this file need live in the components/ folder? I think it would make more sense in source/.

I can think of arguments for both sides, but I'm not married to either at this point. If/when we expand this type of usage from a simple "fake enum" into full classes and stuff, then I'll be dead set on us having individual models folders.

> Should we just create a generic constants file instead of having a separate file for each group? I think that would be easier in the future once we start using more constants

I'm very against this. It would mean we would be including a lot of extra stuff that has nothing to do with the thing we need. It would make the file itself messy - different namespaces mixed together. When I was a C# programmer, all of this was a big no-no.

> We should also add a jsdoc comment for the file. I've been using @fileoverview but @file and @overview also work.

👍

2023-11-26 17:17 UTC, 1hitsong commented
Current State: this address the review items, but the 1st load users VS upgrade user setting still isn't working correctly.

I pushed my commits up so if someone has time to look at it, they can.

2023-11-26 21:57 UTC, cewert commented on source/constants/ImageSizes.bs
> +    const MUSIC_ALBUM = [261, 331]
These aren't image sizes because otherwise music album would be 261,261 since it's a square. This is the `rowItemSize` I think. These are the total size of each item in the row (on the home screen at least. I'm not sure about other screens) including the text.

2023-11-30 04:01 UTC, cewert requested changes
- Rows aren't being added when returning to the home page. Load the home page with an empty continue watching row, open a movie, use a client to play the movie at a random postion then pause  the movie, now hit back in roku client and notice the continue watching row doesnt get created.
- The text showing the number of items for each row (1 of 9) "flickers" when the page is being updated. On prod client, the numbers mostly don't flicker at all but sometimes will flicker once. This PR flickers at least twice it seems, sometimes 3 times.

2023-12-04 15:48 UTC, cewert requested changes

2023-12-04 15:48 UTC, cewert commented on components/home/HomeRows.bs
>          return
These two if statements can be refactored into one. Same goes for the other similar functions `Update x Items()`

```brighterscript
    sectionName = tr("Latest in") + " " + node.metadata.title + " >"

    if not isValidAndNotEmpty(itemData)
        m.expectedRowCount--
        removeHomeSection(sectionName)
        return
    end if
```

2023-12-05 16:36 UTC, cewert approved these changes

2023-12-05 16:55 UTC, merged