Add watched checkmark to Movies, Collections, TV Shows, Season list
jellyfin-archive/jellyfin-roku-legacy pull request #1547
Opened 2023-12-03 01:37 UTC by photonconvergence

Adds watched checkmark to most library views.
Aligns unwatched episode count rectangle in Season list view.
Removes the last API generated watched checkmark (Season list view)

Fixes:
https://github.com/jellyfin/jellyfin-roku/issues/312
https://github.com/jellyfin/jellyfin-roku/issues/402

Inspired by:
https://github.com/jellyfin/jellyfin-roku/pull/922
https://github.com/jellyfin/jellyfin-roku/pull/1223

2023-12-03 11:46 UTC, 1hitsong requested changes

2023-12-03 11:46 UTC, 1hitsong commented on components/ItemGrid/GridItem.bs
> +        if isValid(itemData.json.UserData.Played) and itemData.json.UserData.Played = true
Let's match the valid checks we do further down the view and confirm properties are valid all the way to what we need.

```suggestion
        if isValid(itemData.json) and isValid(itemData.json.UserData) and isValid(itemData.json.UserData.Played) and itemData.json.UserData.Played
```

2023-12-03 11:46 UTC, 1hitsong commented on components/ItemGrid/GridItemSmall.bs
> +    if isValid(itemData.json.UserData.Played) and itemData.json.UserData.Played = true
```suggestion
    if isValid(itemData.json) and isValid(itemData.json.UserData) and isValid(itemData.json.UserData.Played) and itemData.json.UserData.Played
```

2023-12-03 11:46 UTC, 1hitsong commented on components/ListPoster.bs
> +    if isValid(itemData.json.UserData.Played) and itemData.json.UserData.Played = true
```suggestion
    if isValid(itemData.json) and isValid(itemData.json.UserData) and isValid(itemData.json.UserData.Played) and itemData.json.UserData.Played
```

2024-01-01 18:37 UTC, 1hitsong approved these changes
These changes look good to me.

2024-01-02 03:48 UTC, cewert approved these changes

2024-01-02 03:49 UTC, merged

2024-07-23 05:03 UTC, chibiconsulting commented
There should be a user configuration setting to control the color & visibility of the new feature.

Having the ability to select the color of the unwatched counter and the color and/or visibility of the watched checkbox would be a great user experience improvement. With the current implementation, the library views are just a sea of blue boxes.

New settings should be in: Settings / User Interface / Libraries / General

Although could also be in: Settings / User Interface / Libraries / TV Shows as there is already a setting there to "Disable Unwatched Episodes" there; however, this should be a more global solution.

In either case, the settings would be .. / Unwatched Overlay and .. / Watched Overlay with the options being **various colors** or **no display**.