Fix default subtitle track selection
jellyfin-archive/jellyfin-roku-legacy pull request #1604
Opened 2023-12-30 00:25 UTC by 1hitsong

## Changes
Add code to determine which subtitle to select and enable by default - without the user needing to manually select it.

Several functions were copied from subtitles.bs. Once we're fully on the new global queue player, this file should no longer be needed.

## Issues
Fixes #1571

2024-01-02 05:17 UTC, cewert reviewed
This fixes #1571. Is there anything else that needs tested with the copied functions?

2024-01-02 19:54 UTC, 1hitsong commented
The big things is ensuring the selection paths work as expected, and that the language check works.

I had to update the language selection code because it was not selecting any subtitle by default because my SubtitleLanguagePreference is set to "Any Language" on the server, which equals "" in code. This caused the language check to never pass.

![image](https://github.com/jellyfin/jellyfin-roku/assets/3330318/8adc6b3d-a896-40af-86b5-d6c38128b99b)

2024-01-02 23:18 UTC, cewert commented on components/ItemGrid/LoadVideoContentTask.bs
> +        if m.global.session.user.configuration.SubtitleLanguagePreference <> ""
It's been a while so I don't have a link but one of the downsides to using global for the user settings is that we have to do a deep copy every time we access global. To minimize this, we can save a local copy of global whenever we need to check a lot of things i.e. `userConfig = m.global.session.user.configuration`

2024-01-03 02:00 UTC, 1hitsong commented on components/ItemGrid/LoadVideoContentTask.bs
> +        if m.global.session.user.configuration.SubtitleLanguagePreference <> ""
Code adjusted based on comment.

2024-01-03 04:10 UTC, cewert requested changes

2024-01-03 04:10 UTC, cewert commented on components/ItemGrid/LoadVideoContentTask.bs
> +            else if LCase(userConfig.SubtitlePlaybackMode) = "smart" and (item.isForced or item.IsDefault or item.IsExternal)
I got a crash because `SubtitlePlaybackMode` was invalid

![crash-subtitle](https://github.com/jellyfin/jellyfin-roku/assets/16514652/18d37a3c-a45a-4602-b6db-2abbb5e05e0a)

2024-01-03 12:54 UTC, 1hitsong commented on components/ItemGrid/LoadVideoContentTask.bs
> +            else if LCase(userConfig.SubtitlePlaybackMode) = "smart" and (item.isForced or item.IsDefault or item.IsExternal)
Fix added to code

2024-01-06 00:04 UTC, cewert approved these changes

2024-01-06 00:06 UTC, merged

2024-01-07 14:39 UTC, lakerssuperman commented
I just tried this and it didn't work unfortunately.  Watching a movie with a forced subtitled track results in the following:

1) The forced track is shown to be selected in the subtitle selection dialog.
2) The forced subtitles are not displayed during playback.

If I manually toggle subtitles off and then back on it will display the subtitles.  However, if I then go to another movie with standard English not forced subtitles those will be displayed as well despite the subtitle selection dialog indicating subtitles are off.  Clicking None, even if it is already selected and then clicking ok turns subtitles back off.

2024-01-08 01:02 UTC, 1hitsong commented
Can you post a screenshot of your subtitle settings on the server? Specifically the 1st 3 items, Preferred subtitle language, Subtitle mode, and Burn subtitles.

2024-01-08 14:00 UTC, lakerssuperman commented
> Can you post a screenshot of your subtitle settings on the server? Specifically the 1st 3 items, Preferred subtitle language, Subtitle mode, and Burn subtitles.

![Screenshot from 2024-01-08 08-59-48](https://github.com/jellyfin/jellyfin-roku/assets/18699905/ef526357-8a82-442e-b755-7f7ec549b564)

Let me know if you need anything else!  Thanks!