Display ending episode number for multi-part TV episodes
jellyfin-archive/jellyfin-roku-legacy pull request #1669
Opened 2024-01-26 05:31 UTC by photonconvergence

In the Episode List view, show the ending episode number for files that contain more than one episode.

## Issues
Fixes: https://github.com/jellyfin/jellyfin-roku/issues/1664

![multi](https://github.com/jellyfin/jellyfin-roku/assets/116527579/18063e7a-91f8-4481-9a7e-fcb29d8f432f)

2024-01-27 20:08 UTC, 1hitsong requested changes
Works great.

1 code style change. Not that we're using Brighterscript, we can simplify this line using template literals.

2024-01-27 20:08 UTC, 1hitsong commented on components/tvshows/TVListDetails.bs
> +            indexNumber = itemData.indexNumber.toStr() + "-" + itemData.indexNumberEnd.toStr() + ". "
```suggestion
            indexNumber = `${itemData.indexNumber}-${itemData.indexNumberEnd}. `
```

2024-01-29 04:55 UTC, photonconvergence commented on components/tvshows/TVListDetails.bs
> +            indexNumber = itemData.indexNumber.toStr() + "-" + itemData.indexNumberEnd.toStr() + ". "
That's much cleaner! Refactored line 31 as well to keep this section consistent. I think that's reasonably in scope?

2024-01-30 01:34 UTC, 1hitsong approved these changes

2024-01-30 01:35 UTC, 1hitsong commented on components/tvshows/TVListDetails.bs
> +            indexNumber = itemData.indexNumber.toStr() + "-" + itemData.indexNumberEnd.toStr() + ". "
Yep. Typically, I don't like to touch unrelated lines when making feature changes as it adds to the test burden, but since it's an either/or situation for this, both lines will get tested at the same time.

2024-01-30 01:36 UTC, merged

2024-06-02 17:05 UTC, RonJero commented
While this was merged into the master branch, as far as I can tell it has never made it into any of the subsequent releases...

2024-06-03 04:39 UTC, photonconvergence commented
It will be part of the 2.1 release at some point in the future, as it is a new feature. The 2.0.x release series is bug fixes only, and there's hasn't been a major point release since this was merged.