Add a new option to select preferred audio codec for transcodes
jellyfin-archive/jellyfin-roku-legacy pull request #1702
Opened 2024-02-12 20:01 UTC by chrisforte

## Changes
Add a new option that allows the user to select a preferred audio codec to use during transcoding. 

The user-selected preferred codec is added to the front of the codec list for video transcoding profiles. If a transcode is required, it will be selected first to use (assuming the server and stream type support it). If it is not supported (example: DTS is selected as preferred, but the device does not support it, like the Roku Streambar), the next codec in the list is used. 

Additionally, the wording of the existing **DTS** option has been updated to reflect that it applies to audio transcoding profiles _only_.

## Issues
Addresses #958 and #741, related to #1466

## Additional Context
While watching different movies on my Roku Ultra with image-based subtitles, I noticed that my AVR was only receiving PCM audio. Upon investigation, I realized that all transcodes were using AAC instead of EAC3. Because Roku doesn’t support multichannel AAC, it was being downmixed to stereo before being passed to the AVR.

By changing the preferred codec to AC3 in my setup, I was able to retain the channel layout of a transcoded file (DTS 5.1 -> AC3 5.1 instead of DTS 5.1 -> AAC 5.1 -> AAC 2.0)

2024-02-14 16:03 UTC, cewert requested changes
This is very similar to the DTS option but isn't tied to multichannel support. If that's something you or other users want then we should just get rid of the old DTS option completely. Especially because you are modifying the audio codec string right after the DTS option which effectively makes the DTS option useless when they are both turned on.

2024-02-14 19:52 UTC, chrisforte commented
> This is very similar to the DTS option but isn't tied to multichannel support. If that's something you or other users want then we should just get rid of the old DTS option completely. Especially because you are modifying the audio codec string right after the DTS option which effectively makes the DTS option useless when they are both turned on.

That was my initial change (before the PR), but I realized that the current DTS option only changes the codec list for audio profiles, and this change adjusts the video profiles. I didn't want to remove the current setting in case other users were expecting the current functionality to persist. If a combined setting would have the same result, that works for me.

2024-02-14 22:31 UTC, cewert commented
> ... I realized that the current DTS option only changes the codec list for audio profiles, and this change adjusts the video profiles.

I don't follow. Here's my understanding of things. Let me know if this makes sense to you.

By default we use AAC as the preferred audio codec because it is compatible with all stereo devices which is why it is hardcoded [here](https://github.com/jellyfin/jellyfin-roku/blob/ae4ddc6fd9cc4a8989a042cd8c1cef1392b2579b/source/utils/deviceCapabilities.bs#L190) to always be the first item in the audio transcode codec list.

A few lines below that is the only place that uses the DTS setting. All it does is change the order in which we test for multi channel support. Then down just above your current changes [here](https://github.com/jellyfin/jellyfin-roku/blob/ae4ddc6fd9cc4a8989a042cd8c1cef1392b2579b/source/utils/deviceCapabilities.bs#L427) we put the preferred audio codec in the front of the `tsArray.AudioCodec` and `tsArray.AudioCodec` strings just like you are doing in this PR.

The only difference between the two would be the transcoding profiles that get added for the preferred surround sound codec [here](https://github.com/jellyfin/jellyfin-roku/blob/ae4ddc6fd9cc4a8989a042cd8c1cef1392b2579b/source/utils/deviceCapabilities.bs#L409) but I forget what that does exactly 🤔 .

I'm suggesting that we remove the whole if statement [here](https://github.com/jellyfin/jellyfin-roku/blob/ae4ddc6fd9cc4a8989a042cd8c1cef1392b2579b/source/utils/deviceCapabilities.bs#L407), rework the `audioCodecs` string to include all the multichannel codecs [here](https://github.com/jellyfin/jellyfin-roku/blob/ae4ddc6fd9cc4a8989a042cd8c1cef1392b2579b/source/utils/deviceCapabilities.bs#L198), and then keep your changes to also copy the preferred codec to the front of the string.

2024-02-15 15:10 UTC, chrisforte reviewed
Changes made. I retained the settings menu structure, but this option could be moved up one level.

2024-02-23 02:04 UTC, cewert commented
@chrisforte looks great!

I agree, we should move the setting up. Can you move it up a level but keep the current `Preferred Audio Codec` title?

2024-03-16 12:55 UTC, cewert approved these changes

2024-03-17 15:55 UTC, merged