Fix sporatic crash when using ItemGrid
jellyfin-archive/jellyfin-roku-legacy pull request #1714
Opened 2024-02-14 18:12 UTC by cewert

Comes from roku.com crashlog:

```
'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/components/ItemGrid/GridItem.brs(36) Backtrace: #0  Function itemcontentchanged() As Void    file/line: pkg:/components/ItemGrid/GridItem.brs(36) Local Variables: global           Interface:ifGlobal m                roAssociativeArray refcnt=2 count:2 posterbackgrounds <uninitialized> itemdata         <uninitialized>
```
which points to this line in the bs file: `posterBackgrounds = m.global.constants.poster_bg_pallet`

## Changes
- Ensure global constant is valid before using

## Issues
Ref #1662

2024-02-14 22:51 UTC, 1hitsong requested changes

2024-02-14 22:51 UTC, 1hitsong commented on components/ItemGrid/GridItem.bs
> -        m.itemText.text = itemData.Title
Removing these lines causes the TV library to have no posters, no title text, etc. Was this mistakenly left over from testing?

2024-02-14 23:11 UTC, cewert commented on components/ItemGrid/GridItem.bs
> -        m.itemText.text = itemData.Title
Yea this was a mistake not sure how that happened.

2024-02-15 13:21 UTC, 1hitsong approved these changes

2024-02-15 17:40 UTC, merged