Replace Special episode number with "Special" in TvListDetails
jellyfin-archive/jellyfin-roku-legacy pull request #1726
Opened 2024-02-27 04:39 UTC by photonconvergence

## Changes

Indicate that Specials are specials when displayed in another season as well as in the Specials (Season 0) view.
-Any special episode displayed by TvListDetails will show "Special - " instead of the episode number.
-Add a translation string for "Special"

Before:
![before](https://github.com/jellyfin/jellyfin-roku/assets/116527579/9d98916e-b386-4c3b-9010-a9fd77168cf6)

After:
![after-special](https://github.com/jellyfin/jellyfin-roku/assets/116527579/18f4cf51-6bd3-4cd6-83b0-87fe62f301d7)

This PR mirrors the behavior of web. If this is merged, we may want to look at implementing something similar for #1672 
## Issues

Fixes: #1521

2024-02-28 20:24 UTC, photonconvergence commented
Closing at this is an incomplete implementation. Turns out the server allows the name of Season0 to be customized, so we shouldn't hard code it here. Will re-open if I can figure out a better way to do this.

2024-10-02 10:22 UTC, bravely-beep commented
> Turns out the server allows the name of Season0 to be customized, so we shouldn't hard code it here.

I'm not quite sure how this is relevant here. If the name of "Season 0" is customized on the server-side (e.g. changed from "Specials" to "Special Episodes"), the web client continues to show "Special" before each individual special episode. They're two different strings, one singular and one plural.

Therefore, I think this "incomplete implementation" would simply match the current behavior of the web client? Or is there another reason for it not to be merged?

2024-10-04 11:54 UTC, cewert commented
@bravely-beep makes sense to me

@photonconvergence anything to add? Seems like an improvement over what we have now. I'd like to approve and merge but I don't really use specials so maybe I'm missing something

2024-10-09 19:35 UTC, photonconvergence commented
@bravely-beep is correct. Looking into it a bit further, customizing the name of "Season 0" server side only has an effect on TVSeasonRow.bs and the equivalent view in web. All other places the "Season 0" name is used in web are hard coded to translation strings. I misunderstood how this worked. This PR matches the web implementation.

@cewert Feel free to merge.

2024-10-11 21:52 UTC, cewert commented
@photonconvergence nice thanks for looking into it!

2024-10-11 21:54 UTC, cewert requested changes
It looks like there was an issue resolving the merge conflict. The only file with changes is the translation file. https://github.com/jellyfin/jellyfin-roku/pull/1726/files

2024-10-17 02:33 UTC, cewert approved these changes

2024-10-17 02:34 UTC, merged