Update TV Season view data when user goes back to page from Video Player
jellyfin-archive/jellyfin-roku-legacy pull request #1749
Opened 2024-03-16 14:18 UTC by 1hitsong

## Changes
1. Updates resume point for last watched episode on TV Season view.
2. Re-evaluates episode watched check mark
3. Re-evaluates episode watched percentage bar
4. Re-evaluates season unwatched episode number

## Issues
Fixes #1748

2024-03-16 15:05 UTC, cewert requested changes

2024-03-16 15:05 UTC, cewert commented on components/tvshows/TVEpisodes.bs
> +sub OnScreenShown()
needs function definition

2024-03-16 15:05 UTC, cewert commented on components/tvshows/TVEpisodes.bs
> +    m.firstShow = true
```suggestion
    m.isFirstRun = true
```

this is what the home page uses. It would be nice if all views used the same naming

2024-03-16 15:05 UTC, cewert commented on components/tvshows/TVEpisodes.bs
> +    m.top.refreshSeasonDetailsData = not m.top.refreshSeasonDetailsData
What's the point of using `refreshSeasonDetailsData` and sending everything through main? Couldn't we just move all the main code here instead?

2024-03-16 19:43 UTC, 1hitsong commented on components/tvshows/TVEpisodes.bs
> +    m.top.refreshSeasonDetailsData = not m.top.refreshSeasonDetailsData
**(Mostly) Copied over from Chat**

Doing it this way would prevent me from needing to create a new task for each view refresh, since the event raising to main would already be outside the render thread.

Plus, if it were all centralized to main, I could try to share code between the various refreshes.

2024-03-17 21:24 UTC, cewert approved these changes

2024-03-19 19:15 UTC, merged