Display user profile image on overhang
jellyfin-archive/jellyfin-roku-legacy pull request #175
Opened 2020-04-04 19:41 UTC by thomabx

If there is a user profile for the currently logged in user, add the profile image next to the user name on the overhang.

2020-04-06 16:46 UTC, neilsb approved these changes

2020-04-07 17:35 UTC, cewert requested changes

2020-04-07 17:35 UTC, cewert commented on source/Main.brs
> +    userImage = UserImageURL(m.user.id, { "tag": m.user.PrimaryImageTag })
By default, `UserImageURL()` grabs a 300px by 300px image and then we are forcing that image into a 64px by 64px poster.

We should set `maxHeight `and `maxWidth `to 64:
`userImage = UserImageURL(m.user.id, { "tag": m.user.PrimaryImageTag, "maxHeight": 64, "maxWidth": 64 })`

2020-04-07 17:44 UTC, cewert requested changes

2020-04-07 17:44 UTC, cewert commented on components/JFOverhang.xml
>        <Label id="overlayTitle" font="font:LargeSystemFont" vertAlign="center" height="64" width="1100" />
The width of overlayTitle should be adjusted when displaying the user profile image. If not, they will overlap when displaying media with a long title

2020-04-07 17:57 UTC, cewert reviewed
Overall this looks good although I wonder if this is really needed and if there will be any performance hit.

By adding the user image we take away space for media with long titles and increase the chance of the title being cut off. The extra API call means a longer wait till the first two rows are rendered on startup. The performance hit should be minimal but for people with remote servers and/or crappy rokus it may have an impact

2020-04-07 19:18 UTC, thomabx commented
> Overall this looks good although I wonder if this is really needed and if there will be any performance hit.

I wouldn't say it's needed, but it does match the web client behavior of displaying the profile image.

> By adding the user image we take away space for media with long titles and increase the chance of the title being cut off. The extra API call means a longer wait till the first two rows are rendered on startup. The performance hit should be minimal but for people with remote servers and/or crappy rokus it may have an impact

We can add a task to load the image which would rely on the bandwidth to the server but allow rendering. We could additionally make it an option that defaults to off. What do you think?

2020-04-07 19:35 UTC, bisby commented
> We can add a task to load the image which would rely on the bandwidth to the server but allow rendering

I'll admit I've been absent lately and not following every PR closely... But currently,
for design simplicity, all the API requests are done synchronously. (ie, wait for the response
as the request is made, rather than letting it handle in the background).

This sounds like a great opportunity to actually start shifting towards properly
making async requests. Request the image, draw a default or empty box, load image
as it becomes available.

:man_shrugging:

2020-04-08 01:05 UTC, cewert commented
> I wouldn't say it's needed, but it does match the web client behavior of displaying the profile image.

Does it? The web client is showing a rounded image with no text for me right now(10.5.3) vs the square image + text in this PR.

> We can add a task to load the image which would rely on the bandwidth to the server but allow rendering. We could additionally make it an option that defaults to off. What do you think?

Loading the image using a task or async API call is a great idea as well as an option set to off by default but is it worth all the effort? How many people are really going to turn this feature on? (I wouldn't because of the drawbacks I've listed)

The web client is great and I agree we should be looking to it for direction but at the same time the roku app will never be the web client. The computers running the apps are different, the way you interact with the app is different (remote vs mouse), the UI is different(one is meant to be viewed from 2 feet away the other is meant to be viewed 6+ feet away) etc. etc. At some point we have to make our own path. For example, the web client doesn't show the time does that mean we should remove it from our app?

2020-04-08 01:31 UTC, closed without merging