Add option to hide community and critical ratings for movies
jellyfin-archive/jellyfin-roku-legacy pull request #1756
Opened 2024-03-22 04:01 UTC by photonconvergence

## Changes

Add setting to Library->Movies to hide community and critical ratings from Movie Presentation view and Movie details view.
Add translation strings for setting.

## Issues

Fixes: https://github.com/jellyfin/jellyfin-roku/issues/1290

2024-04-07 11:45 UTC, cewert requested changes

2024-04-07 11:45 UTC, cewert commented on components/ItemGrid/MovieLibraryView.bs
> +    if get_user_setting("ui.movies.disableRatings") = "false"
Please use the global syntax to access user settings. This will also convert the string to a boolean

```suggestion
    if m.global.session.user.settings["ui.movies.disableRatings"] = false
```

2024-04-07 11:45 UTC, cewert commented on components/movies/MovieDetails.bs
> +    if get_user_setting("ui.movies.disableRatings") = "false"
Same as above. Please use the global syntax to access user settings.

2024-04-07 13:36 UTC, cewert requested changes

2024-04-07 13:36 UTC, cewert commented on components/movies/MovieDetails.xml
> +          <LayoutGroup id="communityRatingGroup" layoutDirection="horiz" itemSpacings="[-5]" visible="true">
We can just remove the visible param at the end. `LayoutGroup` extends `Group` which is visible by default. 
```suggestion
          <LayoutGroup id="communityRatingGroup" layoutDirection="horiz" itemSpacings="[-5]">
```

2024-04-07 13:36 UTC, cewert commented on components/movies/MovieDetails.xml
> +          <LayoutGroup id="criticRatingGroup" layoutDirection="horiz" itemSpacings="[-5]" visible="true">
Same as above
```suggestion
          <LayoutGroup id="criticRatingGroup" layoutDirection="horiz" itemSpacings="[-5]">
```

2024-04-11 23:39 UTC, cewert requested changes
Tested this and it works great!

There's a couple of little things with how the setting is worded then we can get this merged.

2024-04-11 23:39 UTC, cewert commented on settings/settings.json
> +                                "title": "Disable Community and Critical Ratings",
```suggestion
                                "title": "Community and Critical Ratings",
```

2024-04-11 23:39 UTC, cewert commented on settings/settings.json
> +                                "default": "false"
```suggestion
                                "default": "true"
```

2024-04-11 23:39 UTC, cewert commented on settings/settings.json
> +                                "title": "Disable Community and Critical Ratings",
I think the title should be a vague descriptor of the UI elements we're talking about with the boolean value telling the user whether the UI elements are enabled or disabled.

2024-04-11 23:39 UTC, cewert commented on settings/settings.json
> +                                "description": "Hide the star, community rating, tomato, and critical rating for Movies.",
```suggestion
                                "description": "Things that describe how good the Movie is i.e. star, community rating, tomato, and critical rating",
```


There's probably a better way to word this

2024-04-11 23:40 UTC, cewert commented on settings/settings.json
> +                                "default": "false"
if you make this change you'll also need to update the code

2024-04-27 02:38 UTC, photonconvergence commented on settings/settings.json
> +                                "description": "Hide the star, community rating, tomato, and critical rating for Movies.",
Went with "Show ratings for how good a movie is." Open to suggestions.

2024-04-27 02:40 UTC, photonconvergence commented
Given the lasted feedback, a good followup for this would be a refactor of the same setting for TV Shows.

2024-04-27 14:47 UTC, cewert commented on settings/settings.json
> +                                "description": "Hide the star, community rating, tomato, and critical rating for Movies.",
In my mind the setting description describes the setting title so IMO  `Ratings for how good a movie is.` would be a little better but that might nitpicking.

2024-04-27 14:53 UTC, cewert requested changes

2024-04-27 14:53 UTC, cewert commented on components/ItemGrid/MovieLibraryView.bs
> +    if m.global.session.user.settings["ui.movies.showRatings"] = true
```suggestion
    if m.global.session.user.settings["ui.movies.showRatings"]
```

2024-04-27 14:53 UTC, cewert commented on components/movies/MovieDetails.bs
> +    if m.global.session.user.settings["ui.movies.showRatings"] = true
```suggestion
    if m.global.session.user.settings["ui.movies.showRatings"]
```

2024-04-27 14:53 UTC, cewert commented on locale/en_US/translations.ts
> +            <source>Disable Community and Critical Ratings</source>
Needs to be updated with new text

2024-04-27 14:53 UTC, cewert commented on locale/en_US/translations.ts
> +            <source>Hide the star, community rating, tomato, and critical rating for Movies.</source>
Needs to be updated with new text

2024-04-28 13:50 UTC, cewert approved these changes
Thank you for the PR and your patience! 🙏

2024-04-28 13:51 UTC, merged