Add setting to enable rewatching in the "Next Up" section
jellyfin-archive/jellyfin-roku-legacy pull request #1792
Opened 2024-05-01 19:40 UTC by Johnscaban

## Changes

Add setting to User Interface->General to enable the rewatching of episodes in the "Next Up" section.
Add translation strings for setting.
## Issues

Fixes #1778

2024-05-28 15:47 UTC, Johnscaban commented
Should this pull request be converted to a draft until it can get reviewed so that it doesn't get closed?

2024-07-19 15:39 UTC, Johnscaban commented
Should I submit a new pull request?

2024-07-19 17:12 UTC, cewert commented
Sorry this one slipped through the cracks. No need to remake

2024-07-19 21:06 UTC, Johnscaban commented
No problem. Thanks!

2024-07-20 02:09 UTC, cewert requested changes
This looks great.

Would you mind changing the user setting so that it uses the web client setting by default? The goal is to have all user settings use web client by default with options to override client side.

2024-07-20 19:22 UTC, Johnscaban commented
How should this be done? I'm currently not at my PC, but I would like to get an idea of how to implement your requested changes.

2024-07-20 19:43 UTC, cewert commented
First step is figuring out how to access web client setting. I don't know for sure but I think the web client setting for rewatched should already be saved to the global session in either `m.global.session.user.Policy` or `m.global.session.user.Configuration`.

Then you'd need to modify the user setting to a radio selector instead of a bool. That way you can add a third option to the setting - Use web client setting(default), enabled, and disabled.

Then you would have to tweak your code to use the web client setting from `m.global.session.user` as needed based on the user setting.

Does that make sense?

2024-07-20 21:21 UTC, Johnscaban commented
Okay, so I searched in both `m.global.session.user.Policy` and `m.global.session.user.Configuration` when they get printed to the console when a user logs in, and there is no field for the rewatched setting. Am I looking in the right place?

2024-07-20 21:54 UTC, cewert commented
I forgot the display settings come from a different API endpoint and aren't saved to the session var https://github.com/jellyfin/jellyfin-roku/blob/master/source/utils/session.bs#L232


but there still isn't a setting for rewatched so it looks like we don't have access to the web client setting :(

![jellyfin-api-user-displayprefs-](https://github.com/user-attachments/assets/7c739266-fb1b-494b-bd55-6f5bb1e965ef)

2024-07-20 22:06 UTC, cewert requested changes

2024-07-20 22:06 UTC, cewert commented on settings/settings.json
> +                        "title": "Enable Rewatching Next Up",
Can we change the wording to match the other next up setting above it? Renaming this would also make the list alphabetical again.

```suggestion
                        "title": "Rewatching Next Up",
```

2024-07-20 22:06 UTC, cewert commented on settings/settings.json
> +                        "description": "Enable showing already watched episodes in 'Next Up' sections.",
Remove `enable` to match the new title
```suggestion
                        "description": "Show already watched episodes in 'Next Up' sections.",
```

2024-07-21 12:50 UTC, cewert requested changes

2024-07-21 12:50 UTC, cewert commented on locale/en_US/translations.ts
> +            <source>Enable Rewatching Next Up</source>
Translation strings need updated to match the new titles

2024-07-21 13:45 UTC, Johnscaban commented
Sorry, I forgot about the translations.

2024-07-21 14:35 UTC, cewert approved these changes
Thanks for the PR!

2024-07-21 14:36 UTC, merged