Store release issues
jellyfin-archive/jellyfin-roku-legacy pull request #180
Opened 2020-04-21 18:41 UTC by neilsb

Addressed issues detected by Static Channel Analysis tool

**Changes**
- Removed TrackerTask Component
- Change deprecated BookmarkPosition to PlayStart
- Accept roInput Commands
- Updated Icon Image sizes
- Added required Signal beacons

**Issues**
References #122

2020-04-21 18:48 UTC, neilsb commented
Points to note:

- There appear to be [issues with the roInput certification in Static Analysis](https://community.roku.com/t5/Roku-Developer-Program/Issue-with-Deep-Link-certification-in-Static-Analysis-publishing-step/td-p/510464).  So for now I have added the Task from the example, but not hooked it up (i.e. Task will never run).  This is something that should be looked at in more detail as part of #42 
- For the signal beacons, have also added the ones for Startup Dialogs that are available in RokuOS v9.3.  At the moment they output to the logs that it is an invalid beacon.  Can add a check on the OS version if preferred.
- For the AppLaunchComplete signal beacon, it will currently fire when the Home screen has fully rendered.  However, given the certification requirements say that it should load within 20 seconds this could be problematic if the user has a slow JellyFin server (or slow connection to it), or has a large number of libraries to load.

2020-04-22 03:53 UTC, anthonylavado submitted a review, later dismissed
You’ll want to take out the two PNGs you made. You’ve run in to the same issue that I and many others have.

The default filter for SVG in ImageMagick is dumb and can’t handle the gradient in the logo. If you compile IM with the alternate SVG filter, it will render correctly. I have yet to be able to do this on my Mac or Debian machine, but I haven’t tried in a while.

I might just make the artwork myself at the newer resolutions directly in GIMP, and upload it here and to our Jellyfin-UX repo.

2020-04-22 07:32 UTC, neilsb commented
> You’ll want to take out the two PNGs you made. You’ve run in to the same issue that I and many others have.

Yes, I see what you mean.  Not sure how I missed that.  I've manually done the ImageMagick steps in Gimp and re-uploaded those images, so hopefully that should be them now.

2020-04-22 15:08 UTC, anthonylavado commented
Thank you! I’ll clear my review for now and test this tonight.

2020-04-23 17:06 UTC, cewert requested changes

2020-04-23 17:06 UTC, cewert commented on components/home/HomeRows.brs
> +  m.libariesLoaded = 0
Does `m.libariesLoaded` ever get used?

2020-04-23 17:06 UTC, cewert commented on components/home/HomeRows.brs
> +  end if
Looks like the beacon will also get called after the home page is "refreshed".

We could add a var to track whether or not the app has launched yet

2020-04-23 17:20 UTC, cewert reviewed
Are we sure we want to remove RALE? Some of the devs don't use VSCode but I'm not sure how much it gets used. If all we care about is passing certification we could have the make file remove the RALE code when we deploy.

> For the AppLaunchComplete signal beacon, it will currently fire when the Home screen has fully rendered. However, given the certification requirements say that it should load within 20 seconds this could be problematic if the user has a slow JellyFin server (or slow connection to it), or has a large number of libraries to load.

That shouldn't be an issue since the demo server (and content) will be used to pass certification.

2020-04-24 09:57 UTC, neilsb commented on components/home/HomeRows.brs
> +  m.libariesLoaded = 0
No - I changed how I was planning to do but left that in.    Will get it removed.

2020-04-24 09:58 UTC, neilsb commented on components/home/HomeRows.brs
> +  end if
True.  I don't _think_ it matters, but makes sense to have a flat to say if we are loaded.  Will also add it to the Server and User dialogs so they only issue the signals on app start up too, rather than if the user switches account.

2020-04-24 10:08 UTC, neilsb commented
Regarding RALE, since it's a development tool I don't think the RALE component (TrackerTask) should be included in the "final" build.  So as you suggested, the make file could remove it as part of the deployment, and we could wrap the creation of the Tracker Trask in an if statement depending if we're in _development mode_ or not.

Potentially we add a command to the the make file to download the latest version of the RALE component.  This means we could add it to git ignore and don't have to have it checked it?

2020-04-27 07:48 UTC, anthonylavado commented
I'm okay with this as it stands.

2020-04-29 09:00 UTC, neilsb commented on components/home/HomeRows.brs
> +  end if
That should be it using a global variable to store app loaded status

2020-04-29 09:43 UTC, neilsb commented
Might be worth enabling the Wiki for the project, and we can have some more details in there, specifically about development setups, etc.  Then we can have a guide for enabling RALE via VSCode as well as manually?

2020-04-29 14:42 UTC, cewert commented
Well it's been a while and no other devs have showed up to save RALE. I say we get rid of it. We can always add it back in and it needed updated anyway.

2020-04-29 14:43 UTC, cewert commented on source/Main.brs
> +    end if
Looks like you're missing some code on line 398

2020-04-29 16:11 UTC, neilsb commented on source/Main.brs
> +    end if
Sloppy sloppy sloppy.  Sorry about that.  Thank goodness for code reviews...

2020-04-29 16:12 UTC, neilsb commented
Just as an aside, given the number of changes (including multiple revisions to the image files) might be worth Squashing the commits during the merge.

2020-04-29 16:15 UTC, neilsb commented on source/Main.brs
> +    end if
This was added before I thought it was wise to move it to its own function

2020-04-29 16:22 UTC, cewert approved these changes

2020-04-29 16:26 UTC, merged