Add View All for Next Up
jellyfin-archive/jellyfin-roku-legacy pull request #1846
Opened 2024-07-21 04:43 UTC by jimdogx

Add "View All Next Up".

## Changes
Adds a new "View All Next Up" on the Next Up home screen row. This adds parity to the web client and allows the user to see items that are Next Up that don't fit within the Roku's max column count or items that might be greater than 365 days old.

## Issues
Fixes #1481

2024-07-24 13:29 UTC, cewert requested changes
Home page crashed with one of my test users. `datum.CollectionType` was invalid

![roku1481-crash](https://github.com/user-attachments/assets/0c37a54b-46df-41e9-b249-85c9446acb65)

2024-07-24 13:34 UTC, cewert reviewed
The option menu opens as expected  on the new View All Next Up page but there are no options to choose from. Maybe we should disable the options button for now?

2024-07-25 16:51 UTC, cewert commented on components/home/LoadItemsTask.bs
> +            if data.Items.Count() > 0
I tested this PR with the demo server and I couldn't figure out why the View All button was missing. Then I realized all the episodes are over a year old and our default next up client settings only show episodes from the last 365 days.

IMO that would be the perfect scenario for the button to show up - that way only recently aired episodes show up on the home screen but the user always has easy access to older episodes as well. The home page is also the only way to access the new view you created so I think it makes sense to let users always have access to it.

We could also consider hiding the View All link when the home page is already displaying everything there is to show but eventually the View All Next Up view may have features the home screen doesn't such as sorting, filters, alpha menu etc. So in that case it wouldn't make sense to ever hide the button unless Next Up is completely empty.

2024-07-25 17:13 UTC, cewert requested changes
Episodes without a widescreen image are in the shape of the folder icon when viewing the View All Next Up view. I sent you a screenshot on matrix

2024-07-25 18:39 UTC, jimdogx commented on components/home/LoadItemsTask.bs
> +            if data.Items.Count() > 0
Yeah, that's how I had it originally (always show the button).

Then I thought, let me try to avoid an extra call on the home page to see if there are "hidden next up" items to then show the button.

That's when I added the "only show if at least 1 item on the home page".  But I don't think there is a way around the extra call on the home page if we want it to be smarter 🙃 

I can add that in when I get back to this PR 👍

2024-07-25 18:46 UTC, jimdogx commented
> Episodes without a widescreen image are in the shape of the folder icon when viewing the View All Next Up view. I sent you a screenshot on matrix

Do you know off the top of your head what the home screen does in this case?  I was trying to make the "View All" page work exactly like the "Next Up" row on the home screen.  And on my setup, they are all wide screen posters 😄

2024-07-25 19:11 UTC, cewert commented on components/home/LoadItemsTask.bs
> +            if data.Items.Count() > 0
I didn't think about the extra API call that's fair because ideally it would be in a task which can be complicated

2024-07-25 19:15 UTC, cewert commented
> Do you know off the top of your head what the home screen does in this case? I was trying to make the "View All" page work exactly like the "Next Up" row on the home screen. And on my setup, they are all wide screen posters 😄

Home page uses `scaleToZoom` for the Poster node's `loadDisplayMode` property. https://developer.roku.com/en-ca/docs/references/scenegraph/renderable-nodes/poster.md#fields

2024-07-27 22:29 UTC, jimdogx commented
> > Do you know off the top of your head what the home screen does in this case? I was trying to make the "View All" page work exactly like the "Next Up" row on the home screen. And on my setup, they are all wide screen posters 😄
> 
> Home page uses `scaleToZoom` for the Poster node's `loadDisplayMode` property. https://developer.roku.com/en-ca/docs/references/scenegraph/renderable-nodes/poster.md#fields

Took me all day to figure this one out... turns out it was the frigging "PosterMask" that was causing the clipping.

2024-07-27 22:30 UTC, jimdogx commented on components/home/LoadItemsTask.bs
> +            if data.Items.Count() > 0
Should we leave it as is?  You must have at least one item in Next Up for the View All to show up?

Do we want the extra API call to make it smarter?

I'm leaning towards leave it as is for now, and maybe in another revision we can make it smarter.

Thoughts?

2024-07-28 03:30 UTC, cewert commented on components/home/LoadItemsTask.bs
> +            if data.Items.Count() > 0
Yea we can leave it "dumb" for now 😆 

I like the idea of it always being there but I don't think it's a big deal especially if it gets reworked later

2024-07-28 22:04 UTC, jimdogx commented
@cewert it occurred to me that making it smarter wouldn't be that hard after all.  Plus I coded it so that it's an extra API call if (and only if) there really isn't anything to show in the Next Up home row. 👍 

Ready for review again 😄

2024-07-29 12:02 UTC, cewert approved these changes
Works well with no crashes 👍

Some observations:
- The episode posters are still using `slaceToFit` instead of `scaleToZoom` like the home page.
- The View All button color is randomly grabbed every time the page is refreshed.

2024-07-29 12:44 UTC, merged

2024-07-29 19:15 UTC, p37307 commented
Thank you for working on this. Will make using Roku app better with my Parkinsons. I won't have to go hunt for episodes that dropped off the list. I've been hoping for this for a long time! https://github.com/jellyfin/jellyfin-roku/issues/1481#event-13679835569