New Features
jellyfin-archive/jellyfin-roku-legacy pull request #1987
Opened 2024-10-11 20:22 UTC by Renbo2024

## Changes
Added 2 new features:

1. New setting **Episode Next Up Behavior** which controls the behavior when a Next Up show episode is clicked from the home screen.  It may either play the episode immediately (current default behavior), navigate to a description page of the episode, or navigate to the season that episode is in, and select the episode.
2. New setting **OSD Remaining Time** which controls what information is shown in the video player bottom OSD (when visible) on the right side.  It may either show Remaining Time (current default behavior), completion Time of Day, or both.

2024-10-11 22:14 UTC, cewert commented
> New setting Episode Next Up Behavior... It may either play the episode immediately (current default behavior), navigate to a description page of the episode, or navigate to the season that episode is in, and select the episode.

IMO we should leave the "play the episode" behavior to the play button and just pick one of the two remaining options as the default behavior for everyone. That way if the user wants default audio tracks, subtitle tracks etc they hit the play button. If they want to read description, select audio track, see what time the episode ends etc. they hit the OK button.

The episode description page is just cramming an episode into the movie detail view (which itself still needs lots of work). I vote for episode list as default behavior for the OK button. Once we actually have a proper episode detail page we could revisit this and possibly change default behavior to use that instead.

edit: on second thought the episode page is better than I remember with features the episode list doesnt have. I could go either way. I still vote we pick one as default for eveything and if there's a desire make a user setting to allow either episode page or episode list

2024-10-11 23:27 UTC, Renbo2024 commented
> > New setting Episode Next Up Behavior... It may either play the episode immediately (current default behavior), navigate to a description page of the episode, or navigate to the season that episode is in, and select the episode.
> 
> IMO we should leave the "play the episode" behavior to the play button and just pick one of the two remaining options as the default behavior for everyone. That way if the user wants default audio tracks, subtitle tracks etc they hit the play button. If they want to read description, select audio track, see what time the episode ends etc. they hit the OK button.

So then your suggestion is to differentiate the behavior of the Play and OK button? If that is the suggestion, that is what this feature does, only it allows for a customization of what to do on OK.

> The episode description page is just cramming an episode into the movie detail view (which itself still needs lots of work). I vote for episode list as default behavior for the OK button. Once we actually have a proper episode detail page we could revisit this and possibly change default behavior to use that instead.

OK, so looking like your suggestion is to differentiate the OK and Play button, with OK to season episode list, and leave out the setting for default behavior entirely? 

> edit: on second thought the episode page is better than I remember with features the episode list doesnt have. I could go either way. I still vote we pick one as default for eveything and if there's a desire make a user setting to allow either episode page or episode list

OK, so just remove the "Play" option in the settings?

Side note:  Be aware this is my VERY FIRST ever attempt at working in Brightscript.  I tested as best I can, and do not see any exceptions, but if anyone has comments on how I might improve code, let me know.

2024-10-15 13:57 UTC, Renbo2024 commented
Just pinging again.

If I remove the "Play" option from the setting, does this seem like an acceptable modification for approval?

2024-10-18 13:04 UTC, Renbo2024 commented
I have removed "Play" from the OK button options for home screen next up show episodes.  I have also resolved conflict.  Please let me know if there's anything else needed.

2024-10-22 04:30 UTC, Renbo2024 commented
Just pinging.  I do not know if I missed a step, or perhaps it's just taking a while.  Please let me know if there's anything else I need to do.

2024-10-22 13:08 UTC, jimdogx commented
> Just pinging. I do not know if I missed a step, or perhaps it's just taking a while. Please let me know if there's anything else I need to do.

I like the idea here.  However, while testing it, I noticed that the Episode Details page still has the "extra info" popup available (where you'd normally see the "Cast" and "More like this"), except it's empty.  Also when hitting "Back" from this popup, it takes you to the Home Screen (instead of back to the Episode).

I would recommend we hide that popup altogether if we don't have anything to show.  I will test the OSD stuff next.

2024-10-22 13:19 UTC, jimdogx commented
Love the OSD updates.

Regarding the Episode Detail page again... I'm wondering how people will feel about having to click twice to get back to the Home Screen from the middle of an episode now (the first back takes you to the Episode Details page).  Same when an episode finishes.  It takes you back to the Episode details page of the episode you just watched.

If I'm not mistaken originally there was a third option in your new settings to just "Play"?  If so, I would add that back.  In other words, let people choose to leave it as it currently works if they want.

2024-10-22 13:24 UTC, jimdogx requested changes

2024-10-22 13:24 UTC, jimdogx commented on locale/en_US/translations.ts
> +            <source>What should clicking OK on a Next Up episode do.</source>
I would either add a "?" since this is a question, or even better change it to a statement:

"Home screen next up OK button behavior"

2024-10-22 13:31 UTC, Renbo2024 commented
> Love the OSD updates.
> 
> Regarding the Episode Detail page again... I'm wondering how people will feel about having to click twice to get back to the Home Screen from the middle of an episode now (the first back takes you to the Episode Details page). Same when an episode finishes. It takes you back to the Episode details page of the episode you just watched.

It's going back up the navigation history/stack.  I am not sure how to override this.  Do you know of examples elsewhere that sidestep the stack?

> If I'm not mistaken originally there was a third option in your new settings to just "Play"? If so, I would add that back. In other words, let people choose to leave it as it currently works if they want.

I removed this in response to an earlier PR comment, suggesting the Play button on the roku remote already handles the play-immediately behavior.

2024-10-22 13:32 UTC, cewert commented
This should really be two separate PRs. That would make it easier for us to discuss, review, and test.

We have a user setting that hides all the clocks and references to time for people with insomnia (right next to your new setting in `settings.json`). If possible, your OSD setting should respect it as well and hide it as necessary.

2024-10-22 13:34 UTC, Renbo2024 commented on locale/en_US/translations.ts
> +            <source>What should clicking OK on a Next Up episode do.</source>
Committed this change.

2024-10-22 13:38 UTC, jimdogx commented
> I removed this in response to an earlier PR comment, suggesting the Play button on the roku remote already handles the play-immediately behavior.

I didn't think about that.  Since the Play button handles the "default", customizing just the OK button makes sense.  Sorry for the confusion.

2024-10-22 13:41 UTC, Renbo2024 commented
> We have a user setting that hides all the clocks and references to time for people with insomnia (right next to your new setting in `settings.json`). If possible, your OSD setting should respect it as well and hide it as necessary.

Updated and pushed.

2024-10-22 13:43 UTC, Renbo2024 commented
> This should really be two separate PRs. That would make it easier for us to discuss, review, and test.

I apologize for the bundling.  This all started as a "deal-breaker" feature requirement list for my wife, but then I thought these changes might be useful to others.

2024-10-22 13:46 UTC, jimdogx commented
> > This should really be two separate PRs. That would make it easier for us to discuss, review, and test.
> 
> I apologize for the bundling. This all started as a "deal-breaker" feature requirement list for my wife, but then I thought these changes might be useful to others.

No worries.  To be honest, there have been several times I wished I could "Set Watched" on an episode, this PR allows me to do that :smile: 

Unfortunately, I gotta get to work now.  It's one of the reasons testing PRs takes time around here.  Not sure if you are on The Matrix (see roku client github home page)...  but it can be a good place to bounce ideas off of other Roku users and even get others to help with testing.

2024-10-22 14:24 UTC, Renbo2024 commented
> I like the idea here. However, while testing it, I noticed that the Episode Details page still has the "extra info" popup available (where you'd normally see the "Cast" and "More like this"), except it's empty. 

I am having a hard time duplicating this behavior.  When you have a chance, can you take a screen shot of the issue?  Perhaps I can find a way to see it happen on my system, and then can address.

2024-10-22 21:35 UTC, jimdogx commented
> I am having a hard time duplicating this behavior. When you have a chance, can you take a screen shot of the issue? Perhaps I can find a way to see it happen on my system, and then can address.

When you're on the screen, just push the down arrow.  Do you have info filled out on your popup?  Maybe I just have missing info on my Episodes?

2024-10-23 03:58 UTC, Renbo2024 commented
> > I am having a hard time duplicating this behavior. When you have a chance, can you take a screen shot of the issue? Perhaps I can find a way to see it happen on my system, and then can address.
> 
> When you're on the screen, just push the down arrow. Do you have info filled out on your popup? Maybe I just have missing info on my Episodes?

I do have data there.

2024-10-23 12:12 UTC, Renbo2024 commented
Per discussion on the matrix chat, we'll be leaving the back behavior in place, and leaving the scene stack untouched for now.

2024-10-23 12:23 UTC, jimdogx approved these changes

2024-10-23 12:24 UTC, merged