Hide blue background placeholder when Home Item Poster Loaded
jellyfin-archive/jellyfin-roku-legacy pull request #322
Opened 2020-12-02 21:36 UTC by neilsb

Update HomeItem to automatically hide the placeholder blue box and icon when the Poster Image is loaded and displayed.

**Changes**
 * Add function to fire on Image Loading Status Event to hide blue box
 * Ensure Blue Box is made visible again when Item Content changed (to handle recycling of nodes)

**Issues**
fixed #321

2020-12-03 17:40 UTC, cewert requested changes
Go down to one of the "latest in" rows, scroll left(to wrap the screen) and I get his error


```Current Function:
163:  sub focusChanged()
164:  
165:    if m.top.itemHasFocus = true then
166:*     m.itemText.repeatCount = -1
167:    else
168:      m.itemText.repeatCount = 0
169:    end if
170:  
Source Digest(s): 
pkg: dev 1.3.5 f41bd951281da39536aedcefd3e398ba Jellyfin

Invalid value for left-side of expression. (runtime error &he4) in pkg:/components/home/HomeItem.brs(166)```

2020-12-04 08:20 UTC, neilsb commented
> Go down to one of the "latest in" rows, scroll left(to wrap the screen) and I get his error

m.ItemText is invalid.  I guess it could be a timing issue in that the focus changing at the same time as the "ItemContent" is being changed (through node recycling), and trying to re-set the m.ItemText property using FindNode().  If it is a timing issue, it's happening very consistently though.

Moving the setting of these field to an init function means they'll only be set once, so if the node is recycled it's also a little more efficient.   I've not been able reproduce the issue after making this change.

2020-12-04 15:32 UTC, cewert commented on components/home/HomeItem.brs
> +    print m.itemText.text + " image ready - hiding blue"
forgot to remove print statement

2020-12-04 15:44 UTC, cewert reviewed
I'm no longer able to reproduce the crash but I'm seeing a new bug. After scrolling around a bunch on a couple "latest in" rows, I'm seeing several movie titles scroll even though they are no longer focused

2020-12-06 09:28 UTC, neilsb commented
> I'm no longer able to reproduce the crash but I'm seeing a new bug. After scrolling around a bunch on a couple "latest in" rows, I'm seeing several movie titles scroll even though they are no longer focused

It appears that the `itemHasFocus` property (set automatically by the Roku Component) is not always being set to false (or at least an observer is not firing on its change) when there  a lot of scrolling around.  I've only seen this on the older device currently, and since this is a cosmetic issue whereas there are other changes in this PR that prevent crashing - can we create a new issue for this and get this PR merged?

Just with the Rokus Store Blackout for the festive period happening in a few days we need to get a release published on Monday to let it get through the approval process by the blackout.  I think the fix for the crash (and more visible blue line issue) would be beneficial to get in before this happens.

2020-12-06 16:01 UTC, cewert commented
>  can we create a new issue for this and get this PR merged?

That works for me just need to test your new commit

2020-12-06 16:31 UTC, neilsb commented
I should have mentioned.  Reason for moving the itemExtraText in there was twofold:

- Missed it when I did the same with the other ones
- When the node was recycled, the "ItemExtraText" was not hidden by default.  The result was if you browsed down and along a few libraries, sometimes when going back up to the My Media top row or libraries, they had some text under the main title (e.g. Episode Names, release years, etc

2020-12-06 17:34 UTC, cewert approved these changes
Blue borders are gone and I can't reproduce the crash

2020-12-06 17:35 UTC, merged