Revert change in #311 which causes loss of focus
jellyfin-archive/jellyfin-roku-legacy pull request #325
Opened 2020-12-06 16:40 UTC by neilsb

The issue listed in #323 seems to appear when you get the "Continue / From Start" popup, whether it's from the home screen or from the Movie Detail screen.

Reverting this change made in #311 seems to fix the problem, although I cannot see why.  It should be the same object being pointed to in both cases.   Would like to investigate more, but better to get it fixed first I think.

**Issues**
fixes #232

2020-12-06 19:11 UTC, cewert requested changes
I'm still getting a crash that didn't exist before the lastfocus change - from `show_dialog()`

to reproduce: resume an episode from the home screen, hit back, resume a different episode, crash before video loads with

```
134:*   lastFocus.setFocus(true)
135:    m.scene.observeField("backPressed", m.port)
136:  
137:    return result
138:  end function
Source Digest(s): 
pkg: dev 1.3.5 60c2976c1f1a59bd11eff810f1ef4b22 Jellyfin

'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/source/utils/misc.brs(134)
```

2020-12-06 23:03 UTC, neilsb commented
Have now removed all updates to the focus logic with the exception of when a TV Show is selected.  The difference with TV shows if when the focus is returned to this screen it can either be the main ItemGrid, or the TV Guide that was displayed right before the TV Show was played.  In this case we want the focus to return the correct instance, stored in the `lastFocus` member variable.

The added code should be checking if this is set on a per-screen basis, and if not just do what would normally be done.  Since the Live TV Screen was the only screen that was setting this, it shouldn't have affected any other screens.  The change in the main loop had just been done for all screens to allow for this on any other screen in the future.  So not needed, but shouldn't have caused any problems.   Yet it did.   Plainly a lesson is not to change things that don't directly need changing.

Spent a fair but of time playing with selecting TV channels from both the TV Guide and the Channel List, and seems to be working without any crashed.   Been unable to replicate the one you listed above since reverting those changes too.

2020-12-07 04:15 UTC, cewert approved these changes

2020-12-07 04:17 UTC, cewert commented
I'm no longer seeing any crashes or loss of focus. I don't have a proper setup to test livetv but considering the testing you've done now plus all the testing from the original PR I'm sure it's fine.

2020-12-07 04:18 UTC, merged