Updated Search functions
jellyfin-archive/jellyfin-roku-legacy pull request #452
Opened 2021-06-09 14:27 UTC by candry7731

Updated search funstions to include tv Channels and Persons. 

**Changes**
Added inculdedtypes to the api so it would get Live TV Channels and persons.

**Issues**
The search function would not load TvChannels or actors and actresses. This change allows the api to get all of those items. 
There is 0 preformance lag when searching 
We still need to add a busy spinner to the pages while loading

2021-06-10 20:38 UTC, neilsb requested changes
The main change to TV Channels in the search results seems to work fine, but I'm just wary of providing search results for items that we don't yet handle in the client.

2021-06-10 20:38 UTC, neilsb commented on components/search/SearchRow.brs
> +    type_array = ["TvChannel", "Movie", "Series", "Episode", "AlbumArtist", "Album", "Audio", "Person"]
```suggestion
    type_array = ["Movie", "Series", "TvChannel", "Episode", "AlbumArtist", "Album", "Audio", "Person"]
```
I suspect that there are more users that use Jellyfin for watching Movies and TV Series than use the Live TV functionality, so I think it may be better (as well as keeping more in line with the Web Results) that the matching Movies and TV Series are displayed before the TV Channels in the search results.

2021-06-10 20:38 UTC, neilsb commented on source/api/Items.brs
> +    "IncludeItemTypes": "TvChannel,Movie,BoxSet,Series,Episode,Trailer,Video,AdultVideo,MusicVideo,Genre,MusicGenre,MusicArtist,Person"
I'm not 100% how the `IncludeItemTypes` is interpreted at the moment.  Without this change the results still include "Series" and "Episodes" in the results.  So I think it's safe to keep `TvChannel`, `Movie`, `Series`, `Episode` and `Video`

As for the others, the individual types need to be supported in the Roku client before they can be played or viewed.  So if they _do_ appear in the results (which I don't think they will) then selecting them from the results would just give the user an error.  I would suggest the returned search items can be updated as the Roku client supports more media types.

2021-06-10 21:01 UTC, candry7731 commented
I agree!

On Thu, Jun 10, 2021, 3:39 PM Neil Burrows ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The main change to TV Channels in the search results seems to work fine,
> but I'm just wary of providing search results for items that we don't yet
> handle in the client.
> ------------------------------
>
> In components/search/SearchRow.brs
> <https://github.com/jellyfin/jellyfin-roku/pull/452#discussion_r649502721>
> :
>
> > @@ -46,8 +46,9 @@ function getData()
>
>      ' todo - Or get the old data? I can't remember...
>
>      data = CreateObject("roSGNode", "ContentNode")
>
>      ' Do this to keep the ordering, AssociateArrays have no order
>
> -    type_array = ["Movie", "Series", "Episode", "AlbumArtist", "Album", "Audio", "Person"]
>
> +    type_array = ["TvChannel", "Movie", "Series", "Episode", "AlbumArtist", "Album", "Audio", "Person"]
>
>
> ⬇️ Suggested change
>
> -    type_array = ["TvChannel", "Movie", "Series", "Episode", "AlbumArtist", "Album", "Audio", "Person"]
>
> +    type_array = ["Movie", "Series", "TvChannel", "Episode", "AlbumArtist", "Album", "Audio", "Person"]
>
>
> I suspect that there are more users that use Jellyfin for watching Movies
> and TV Series than use the Live TV functionality, so I think it may be
> better (as well as keeping more in line with the Web Results) that the
> matching Movies and TV Series are displayed before the TV Channels in the
> search results.
> ------------------------------
>
> In source/api/Items.brs
> <https://github.com/jellyfin/jellyfin-roku/pull/452#discussion_r649514945>
> :
>
> > @@ -39,11 +39,12 @@ function SearchMedia(query as string)
>
>      "IncludeGenres": false,
>
>      "IncludeStudios": false,
>
>      "IncludeArtists": false,
>
> -    ' "IncludeItemTypes: "Movie",
>
> +    "IncludeItemTypes": "TvChannel,Movie,BoxSet,Series,Episode,Trailer,Video,AdultVideo,MusicVideo,Genre,MusicGenre,MusicArtist,Person"
>
>
> I'm not 100% how the IncludeItemTypes is interpreted at the moment.
> Without this change the results still include "Series" and "Episodes" in
> the results. So I think it's safe to keep TvChannel, Movie, Series,
> Episode and Video
>
> As for the others, the individual types need to be supported in the Roku
> client before they can be played or viewed. So if they *do* appear in the
> results (which I don't think they will) then selecting them from the
> results would just give the user an error. I would suggest the returned
> search items can be updated as the Roku client supports more media types.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/452#pullrequestreview-681225468>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRFCQCLDEHIEY2ANBXLTSEPG5ANCNFSM46MFEJ3Q>
> .
>

2021-06-11 19:34 UTC, candry7731 reviewed
updated code based on Neils suggestion 
type_array = ["Movie", "Series", "TvChannel", "Episode", "AlbumArtist", "Album", "Audio", "Person"]

2021-06-12 15:52 UTC, neilsb commented on source/api/Items.brs
> +    "IncludeItemTypes": "TvChannel,Movie,BoxSet,Series,Episode,Trailer,Video,AdultVideo,MusicVideo,Genre,MusicGenre,MusicArtist,Person"
Looks like this change wasn't added to the PR yet.

2021-06-14 20:03 UTC, neilsb commented on source/api/Items.brs
> +    "IncludeItemTypes": "TvChannel,Movie,BoxSet,Series,Episode,Trailer,Video,AdultVideo,MusicVideo,Genre,MusicGenre,MusicArtist,Person"
```suggestion
    "IncludeItemTypes": "TvChannel,Movie,BoxSet,Series,Episode,Video,"
```

2021-06-14 20:04 UTC, neilsb approved these changes

2021-06-14 20:04 UTC, merged