Add Jellyfin server picker UI
jellyfin-archive/jellyfin-roku-legacy pull request #465
Opened 2021-07-09 19:25 UTC by TwitchBronBron

**Changes**
Display a list of jellyfin servers detected on the local network during the login process. Uses SSDP under the hood to scan for all DLNA servers having the "jellyfin" manufacturer.
![image](https://user-images.githubusercontent.com/2544493/125126376-0319c180-e0c9-11eb-937a-f34b8443eb05.png)

https://user-images.githubusercontent.com/2544493/125126690-791e2880-e0c9-11eb-9fd9-45876bf65190.mp4

2021-07-09 19:26 UTC, TwitchBronBron commented on components/JFButton.brs
> +sub init()
The default `<Button` is quite frustrating to style. This custom button element removes the left images, and also pads the text left and right with whitespace so the text can actually be centered in the button!

2021-07-09 19:27 UTC, TwitchBronBron commented on components/Spinner.xml
> +<?xml version="1.0" encoding="utf-8" ?>
This is a small spinner component that can be added to a page to show that a section is loading without blocking the entire screen with a dialog/popup loader.

2021-07-09 19:28 UTC, TwitchBronBron commented on components/Spinner.brs
> +  m.top.poster.uri = "pkg:/images/spinner.png"
This image was copied from Roku's [SimpleBusySpinner](https://github.com/rokudev/samples/tree/master/ux%20components/widgets) example. The images are licensed as MIT as seen [here](https://github.com/rokudev/samples/blob/master/LICENSE)

2021-07-09 19:29 UTC, TwitchBronBron commented on components/config/JFServer.xml
> +<?xml version="1.0" encoding="utf-8"?>
This component is used inside the `SetServerScreen` `<MarkupList` for each server found on the network:
![image](https://user-images.githubusercontent.com/2544493/125127422-812a9800-e0ca-11eb-818b-fd409f816786.png)

2021-07-09 19:32 UTC, TwitchBronBron commented on components/config/SetServerScreen.xml
> +        <Rectangle id="submitSizer" width="1920" height="0" color="#00000000" />
The LayoutGroup can't directly have its width or height set. So this invisible rectangle is added so that the LayoutGroup will fill that size, and then allow our button to be centered horizontally.

2021-07-09 19:34 UTC, TwitchBronBron commented on components/config/SetServerScreen.xml
> +        <Poster id="serverUrlOutline" visible="false" uri="pkg:/images/hd_focus.9.png" />
This 9patch (`pkg:/images/hd_focus.9.png`) adds a white border around the text box when it's focused.

2021-07-09 19:34 UTC, TwitchBronBron commented on components/config/SetServerScreen.xml
> +    <field id="serverWidth" alias="serverUrlOutline.width,serverUrlTextbox.width,serverUrlContainer.width,submitSizer.width" value="1620" />
This is a neat trick, the alias will keep all of the listed properties in sync!

2021-07-09 19:36 UTC, TwitchBronBron commented on package.json
> +    "brighterscript": "^0.39.4",
Upgraded to the latest version of brighterscript which adds a few bugfixes and improvements. (I'm the primary maintainer of `brighterscript` so let me know if you have any concerns about this version bump).

2021-07-09 19:37 UTC, TwitchBronBron commented on source/ShowScenes.brs
> +        serverUrl = standardize_jellyfin_url(screen.serverUrl)
Moved the URL sanitizing logic into a utility function so this function can be a little cleaner.

2021-07-09 19:37 UTC, TwitchBronBron commented on source/ShowScenes.brs
> +            set_setting("server", serverUrl)
I'm not sure if this is the right thing to do here. I got a merge conflict so I just guessed.

2021-07-09 19:43 UTC, TwitchBronBron commented
There are a few whitespace/formatting changes in this PR too (vscode auto-trim whitespace, code formatting, etc...). If you would prefer me to revert those, let me know.

2021-07-09 19:44 UTC, TwitchBronBron commented on source/ShowScenes.brs
> +  screen = CreateObject("roSGNode", "SetServerScreen")
This used to be driven by the `ConfigScene` component. However, I created a separate custom `SetServerScreen` component to handle this specific flow now, so that's why most of this function has changed. I left the `ConfigScene` unchanged so the other areas of code using it should be unaffected.

2021-07-10 07:43 UTC, neilsb commented
Firstly, this is great.  Thankyou very much.   

I've done some functional testing on it, and will go through the code shortly.  Seems to work well as long as there is a server found, but if there are no discoverable servers then there seems to be a focus issue, in that you can't navigate on the server connection page.

2021-07-10 08:33 UTC, neilsb commented
As well as SSDP, Jellyfin also has it's own server discovery.  While in many cases this may be redundant, it can be useful when using Docker and users host other applications that use SSDP (e.g. Plex).  This is mainly for information, as I'm not suggesting the PR should be changed at the moment, but the way you've put things together would be it relatively straightforward to have another task that performs the other discovery method, and the results can then be combined (removing duplicates)

Jellyfin server listens on UDP/7359 (by default) for messages, and if it receives `who is JellyfinServer?` it responds with JSON data in the format below 

``` json
{
"Address" : "http://192.168.x.xx:8096",
"Id" : "120.....160b",
"Name" : "ServerName",
"EndpointAddress":null
}
```

2021-07-10 11:25 UTC, TwitchBronBron commented
> Firstly, this is great. Thankyou very much.
> 
> I've done some functional testing on it, and will go through the code shortly. Seems to work well as long as there is a server found, but if there are no discoverable servers then there seems to be a focus issue, in that you can't navigate on the server connection page. So can't enter a manual server address.

Oof. I totally forgot to test that scenario! Should be an easy fix, I'll get to that today.

2021-07-10 11:30 UTC, TwitchBronBron commented
> As well as SSDP, Jellyfin also has it's own server discovery. While in many cases this may be redundant, it can be useful when using Docker and users host other applications that use SSDP (e.g. Plex). This is mainly for information, as I'm not suggesting the PR should be changed at the moment, but the way you've put things together would be it relatively straightforward to have another task that performs the other discovery method, and the results can then be combined (removing duplicates)
> 
> Jellyfin server listens on UDP/7359 (by default) for messages, and if it receives `who is JellyfinServer?` it responds with JSON data in the format below
> 
> ```json
> {
> "Address" : "http://192.168.x.xx:8096",
> "Id" : "120.....160b",
> "Name" : "ServerName",
> "EndpointAddress":null
> }
> ```

I don't mind changing the PR now to support it all. Is this Jellyfin discovery more accurate (i.e. does every jellyfin server respond to this discovery info)? The downside to my current implementation is that DLNA needs to be enabled in the jellyfin server, which I don't think everyone does.

So, my question really is: should I scrap the DLNA scanning logic in favor of the `who is jellyfin`?

2021-07-10 15:28 UTC, neilsb commented
> I don't mind changing the PR now to support it all. Is this Jellyfin discovery more accurate (i.e. does every jellyfin server respond to this discovery info)? The downside to my current implementation is that DLNA needs to be enabled in the jellyfin server, which I don't think everyone does.

The server team say that the "who is jellyfin?" is likely to be more reliable than DNLA scanning.  Out of the box, the server will respond to these requests with no configuration changes.

That said, it is an additional port to be opened/mapped if there's a firewall or the user is running in docker.  So I'm sure that it's not the silver bullet.

> So, my question really is: should I scrap the DLNA scanning logic in favor of the `who is jellyfin`?

I'm in two minds, honestly.  I'm happy to for it to be left in, and it can catch any edge cases of users who have set up DNLA but haven't opened that custom discovery port.  But also happy to remove it if it's a hassle to have both methods and dealing with the de-duping.

2021-07-12 02:07 UTC, TwitchBronBron commented
> Firstly, this is great. Thankyou very much.
> 
> I've done some functional testing on it, and will go through the code shortly. Seems to work well as long as there is a server found, but if there are no discoverable servers then there seems to be a focus issue, in that you can't navigate on the server connection page. So can't enter a manual server address.

Fixed this in commit https://github.com/jellyfin/jellyfin-roku/pull/465/commits/4ddfec422b4cd3b740a04c458952771d6e7f6220 . Can you test again?

2021-07-12 19:32 UTC, neilsb commented
> Fixed this in commit [4ddfec4](https://github.com/jellyfin/jellyfin-roku/commit/4ddfec422b4cd3b740a04c458952771d6e7f6220) . Can you test again?

You great.  Works brilliantly now.

2021-07-12 19:36 UTC, neilsb commented on components/JFButton.brs
> +sub init()
Think this will come in handy throughout the app.

2021-07-12 19:40 UTC, neilsb commented on components/config/SSDPTask.brs
> +    maxTimeMs = 2200
Just curious as to why the time in 2.2s?  Seems quite short, and pretty specific.  Is it a recommended value?

2021-07-12 19:44 UTC, neilsb commented on components/config/SetServerScreen.brs
> +  dialog.title = "Enter the server name or ip address"
Could any text that's displayed to the user be wrapped in `tr()` to allow translation.   And entry matching the string will also need to be added to the `\locale\en_US\translation.ts` file which is the _master_ file Weblate (the translation platform we use) will use

2021-07-12 19:46 UTC, neilsb commented on components/config/SetServerScreen.xml
> +        <label text="Pick a Jellyfin server from the local network" />
The text "Pick a Jellyfin server from the local network" will also need to go in the en_US translation file for Roku to localise it.

2021-07-12 19:47 UTC, neilsb commented on components/config/SetServerScreen.xml
> +      <label text="...or enter server URL manually:" translation="[0, 690]" />
Think this is the last bit of text needing added to the translation file

2021-07-12 19:50 UTC, neilsb commented on source/ShowScenes.brs
> +  screen = CreateObject("roSGNode", "SetServerScreen")
Makes sense.  Screen management in general is something that we're needing to tackle soon.

2021-07-12 20:05 UTC, neilsb commented on source/ShowScenes.brs
> +            set_setting("server", serverUrl)
Yup, this is correct and works.  Just allows server redirects to work, and the Roku will follow them.

2021-07-12 20:07 UTC, neilsb requested changes
All looks good, and works as expected.  A few tricks in there that will be useful for other places in the app too.  👍 

Good to merge once the translation string are in for the Weblate volunteers to work on

2021-07-12 20:08 UTC, TwitchBronBron commented on components/config/SSDPTask.brs
> +    maxTimeMs = 2200
I copied this code from the internet...no specific reason it needs to be this value. Just that, whatever value we pick will be how long the users will need to wait before they can interact with the server picker screen.

2021-07-12 20:09 UTC, TwitchBronBron commented
> All looks good, and works as expected. A few tricks in there that will be useful for other places in the app too. 👍
> 
> Good to merge once the translation string are in for the Weblate volunteers to work on

I'll get these translations handled soon. 

Also, I have the logic for the client discovery network servicing almost done too, so I figure that can be included in this PR Too.

2021-07-12 20:20 UTC, neilsb commented on components/config/SSDPTask.brs
> +    maxTimeMs = 2200
That's fine, thanks.  Was just curious.  Value can always be tweaked later based on user feedback if required.

2021-07-13 02:38 UTC, TwitchBronBron commented on components/config/SetServerScreen.xml
> +        <label text="Pick a Jellyfin server from the local network" />
Done

2021-07-13 02:38 UTC, TwitchBronBron commented on components/config/SetServerScreen.xml
> +      <label text="...or enter server URL manually:" translation="[0, 690]" />
Done.

2021-07-13 02:38 UTC, TwitchBronBron commented on components/config/SetServerScreen.brs
> +  dialog.title = "Enter the server name or ip address"
Done.

2021-07-13 02:41 UTC, TwitchBronBron commented
I just pushed two commits:
- Scan the local network using ClientDiscovery (port 7359) and merge+dedupe these results with the SSDP/DLNA results (https://github.com/jellyfin/jellyfin-roku/pull/465/commits/65f56e8b5607580a7db94b86d7d0a5ea7f4c8b29)
- Add translation support (https://github.com/jellyfin/jellyfin-roku/pull/465/commits/af8db646ff115c2fe1f51971ea44a2c057fc1a1e)

At this point, I believe everything has been addressed. Let me know if there's anything else you need.

2021-07-13 20:40 UTC, neilsb commented
Those latest changes look great, and looks to be detecting server reliably  😃.   However, I've found another bug that I missed earlier I'm afraid.   If you enter an invalid (or blank) manual server URL, the app hangs when you hit submit.

2021-07-14 01:01 UTC, TwitchBronBron commented
> Those latest changes look great, and looks to be detecting server reliably 😃. However, I've found another bug that I missed earlier I'm afraid. If you enter an invalid (or blank) manual server URL, the app hangs when you hit submit.

Another good catch! I'll work on this and let you know when it's finished.

2021-07-16 02:33 UTC, TwitchBronBron commented
I have resolved the issue when the server url is invalid. I had forgotten to add support for showing the error message. Here's the commit: 30377d3ebd585b9cd6490ba768a46d3fd4a7fbce

2021-07-18 13:38 UTC, neilsb approved these changes
Work great now!  👍

2021-07-18 13:51 UTC, merged