Support MPEG2 codec when available
jellyfin-archive/jellyfin-roku-legacy pull request #481
Opened 2021-08-30 18:41 UTC by jdlayman

**Changes**

Support playing video using the MPEG-2 codec when supported by the device. Enabled by option since MPEG-2 requires high bandwidth and some users report issues with MPEG-2 decoding on some Roku models.

**Issues**

2021-08-31 16:45 UTC, neilsb requested changes
Looks great, and works a treat.  Thanks.

Just a couple of formatting issues picked up by the formatter.  If you've done a `npm install` you can then run `npm run format` and check the changes it made before committing.  It's a new process so still getting to grips with it.

2021-09-01 01:04 UTC, jdlayman commented
Whoops. I will make sure to run `npm run format` in the future before I push. I went ahead and force pushed since the changes were small and I wanted to keep the log clean.

2021-09-01 08:40 UTC, neilsb approved these changes

2021-09-01 08:41 UTC, neilsb commented
> Whoops. I will make sure to run `npm run format` in the future before I push. I went ahead and force pushed since the changes were small and I wanted to keep the log clean.

Perfect - thanks.   The formatting requirement is brand new, so we'll see how it goes in the short term.  Thanks again.

2021-09-01 08:41 UTC, merged