Update ShowScenes.brs
jellyfin-archive/jellyfin-roku-legacy pull request #557
Opened 2022-04-10 05:48 UTC by candry7731

Commit out the Title as this was causing the app to crash when coming from the home screen episode navigation

**Changes**

**Issues**

2022-04-12 23:27 UTC, jimdogx commented
The title appears to work for me with 1.4.12.  However it does crash with the Updated-Episode-Nav branch.  I'm wondering if there is something slightly off with the way you're querying the server for the series / season info?

2022-04-19 16:47 UTC, neilsb commented
It's my understanding that this is an additional commit for #556.  Since there is a comment on this PR I've merged #556 into this branch and updated the description.

2022-04-24 16:47 UTC, neilsb requested changes

2022-04-24 16:47 UTC, neilsb commented on source/ShowScenes.brs
> +    'group.overhangTitle = series.title
```suggestion
```
Better to remove redundant code than just commenting it out.  It will always be in the git history for people to see what was there if required.

2022-04-24 16:47 UTC, neilsb commented on source/ShowScenes.brs
> +    'group.overhangTitle = series.title + " " + season.title
```suggestion
```
Better to remove redundant code than just commenting it out.  It will always be in the git history for people to see what was there if required.

2022-04-24 16:47 UTC, neilsb commented on source/VideoPlayer.brs
> +        return option_dialog(["Resume playing at " + ticksToHuman(time) + ".", "Start over from the beginning.", "Watched", "Go to series", "Go to season", "Go to episode"])
I think "Watched" has been added to this list by mistake. Also, we don't want these new items shown when the popup appears anywhere else other than the home screen.

The same popup is used when:

- a part-watched episode is selected from the Episode List (Go into a TV Show, then select a season, then select a part-played episode).
- a part-played movie is played from the movie detail screen

2022-04-24 16:47 UTC, neilsb commented on source/VideoPlayer.brs
> +        return option_dialog(["Resume playing at " + ticksToHuman(time) + ".", "Start over from the beginning.", "Watched", "Go to series", "Go to season", "Go to episode"])
```suggestion
        return option_dialog([tr("Resume playing at ") + ticksToHuman(time) + ".", tr("Start over from the beginning."), tr("Watched"), tr("Go to series"), tr("Go to season"), tr("Go to episode")])
```

We should be ensuring that any UI string that are displayed are translated into the user selected language using the `tr()` function.  The strings will also need added to the `locale\en_US\translations.ts` file for translation.

2022-04-24 16:51 UTC, neilsb commented
> The title appears to work for me with 1.4.12. However it does crash with the Updated-Episode-Nav branch. I'm wondering if there is something slightly off with the way you're querying the server for the series / season info?

@jimdogx  Looks like this is working now.  The removal of the 2 lines setting the overhang title appears to be a better user experience.  In the current client, when selecting a TV Show or Season, it looks like the title is set once, then quickly overwritten.  This looks to have fixed that too.

2022-04-24 20:22 UTC, candry7731 commented
Thank you for all the feedback and suggestions!

I'm still learning as we go!

On Sun, Apr 24, 2022, 11:51 AM Neil Burrows ***@***.***>
wrote:

> The title appears to work for me with 1.4.12. However it does crash with
> the Updated-Episode-Nav branch. I'm wondering if there is something
> slightly off with the way you're querying the server for the series /
> season info?
>
> @jimdogx <https://github.com/jimdogx> Looks like this is working now. The
> removal of the 2 lines setting the overhang title appears to be a better
> user experience. In the current client, when selecting a TV Show or Season,
> it looks like the title is set once, then quickly overwritten. This looks
> to have fixed that too.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/557#issuecomment-1107877527>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRAIIEEITSAK2FBP4PLVGV3YHANCNFSM5TAKMAHQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-05 15:09 UTC, candry7731 commented on source/VideoPlayer.brs
> +        return option_dialog(["Resume playing at " + ticksToHuman(time) + ".", "Start over from the beginning.", "Watched", "Go to series", "Go to season", "Go to episode"])
I believe "watched" will set the episode to "watched". Meaning if it didn't report correctly to the server you can reset it as watched.

2022-05-07 12:06 UTC, neilsb commented on source/VideoPlayer.brs
> +        return option_dialog(["Resume playing at " + ticksToHuman(time) + ".", "Start over from the beginning.", "Watched", "Go to series", "Go to season", "Go to episode"])
It's just that when viewing a partially viewed movie, you get the Menu Option related to TV Series (which don't make sense) and I don't think the **watched** item should appear in this list here, since movies have a button to toggle the watched status on this screen already.

![image](https://user-images.githubusercontent.com/5013482/167253568-34fc97bb-a519-43d9-9f43-152fa640574c.png)

2022-05-11 02:46 UTC, candry7731 commented
This has been updated to only show the extra options for Episodes/Series on "Continue Watching"

2022-05-11 21:40 UTC, neilsb approved these changes
All seems to work fine for me in my testing.  @jimdogx Would you be able to check if you can reproduce the error you mentioned earlier in this PR?  If you're not able to, I think we're OK to merge.

2022-05-11 23:13 UTC, jimdogx commented
> All seems to work fine for me in my testing. @jimdogx Would you be able to check if you can reproduce the error you mentioned earlier in this PR? If you're not able to, I think we're OK to merge.

My server issues have been resolved, but I probably won't get to test anything until tomorrow evening (my time) at the earliest.

2022-05-12 13:04 UTC, jimdogx commented
Looks to be working, not seeing any crashes. 👍

2022-05-12 18:11 UTC, merged

2022-07-09 19:15 UTC, tremby commented
I'm not sure if this is the place or if a separate ticket would be better, but I have noticed an issue with the new menu which appears which choosing an item from the "continue watching" list.

If the "watched" option is chosen, nothing appears to happen; the thumbnail is still there. Selecting it again does not produce the menu again, it just plays from the start.

I think the episode *is* being marked as watched, there's just no UI update so it's a confusing experience.. If I choose "watched" then exit the app and reopen, the item is gone from "continue watching".