Allow selection of different audio tracks for tv shows
jellyfin-archive/jellyfin-roku-legacy pull request #575
Opened 2022-04-24 15:16 UTC by jimdogx

Allow selection of different audio tracks for TV shows.

When selecting "option" on an episode with more than one audio track, the user can now select a different audio track.

This PR will also add text ("+1", "+2", etc) to the audio codec if more than one audio track is found.  Because of this, I've noticed that loading the rows takes a smidge longer.  So the Season Title will now say "Loading..." until the rows are done.

**Issues**
Fixes: #478

2022-04-24 19:35 UTC, neilsb commented
Looks good.  I'll try to give it a proper test over the next few days.  👍

2022-04-25 15:04 UTC, neilsb commented
Couple of minor things I found during functional testing

From the episode list, if you press * to open the options, then press * again (I assumed that's how to close them) focus gets lost and there doesn't appear to be a way to get it back
If you start playing an episode, then hit "Back" to stop and return to then episode list, press * and choose a different track then back out of the options, the episode starts playing again automatically. Doesn't do it if you don't select a different track. Not saying this is necessarily an issue, just maybe a little odd?

2022-04-25 15:45 UTC, jimdogx commented
Thanks!

I did run in to the issue where the RowList loses focus, but I added some logic so that if the user hits "up" or "down" it regains focus.  However, I don't think I ever tried hitting "*" to go back (only "back").  So you might have found another case.

I'll take a look at that and the un-intended autoplay when I get a chance 👍

2022-04-26 12:27 UTC, jimdogx commented
I think I fixed the "*" issue.

Will have to spend some time looking in to the autoplay issue later.  Although it is a nice "feature" wouldn't you say? 😄

2022-04-26 13:24 UTC, neilsb commented
> Will have to spend some time looking in to the autoplay issue later. Although it is a nice "feature" wouldn't you say? 😄

Genuinely I don't think it's bad.  If someone is going into that menu and selects an audio track, it's logical that they want to play it.  Making it autoplay if they choose one on a non-started episode would be just as valid since it would be consistent  😄

2022-04-30 11:09 UTC, neilsb requested changes
If you have an episode that is part way played, and go into the TV Show and Season, and select it from the episode list then you get the popup about starting over or resuming.   If you select one the episode starts.  If you then press back you end up back on the episode list, but none of the episodes have focus.   Pressing * at this point causes a crash.

I realise the root cause of this is that focus is not set properly after the Resume/Restart appears, but probably worth catching this.

2022-04-30 11:09 UTC, neilsb commented on source/Main.brs
> +                if selectedItem.selectedAudioStreamIndex > 1
```suggestion
                if selectedItem.selectedAudioStreamIndex <> invalid and selectedItem.selectedAudioStreamIndex > 1
```

Trying to play a TV Episode directly from the home screen (in Next up, for example) causes a crash here, as `selectedItem.selectedAudioStreamIndex` is not set

2022-04-30 13:03 UTC, jimdogx commented on source/Main.brs
> +                if selectedItem.selectedAudioStreamIndex > 1
Thanks... Spent another hour working on the "auto play" issue and as part of that I had added invalid checks.  However, I did not test the resume/restart then back flow; so great catch!

2022-04-30 14:27 UTC, neilsb approved these changes
All looks good 👍

2022-04-30 14:37 UTC, merged