Update live tv buffer timer
jellyfin-archive/jellyfin-roku-legacy pull request #582
Opened 2022-04-29 18:50 UTC by candry7731

Update Live tv stream buffer timer so that streams do not fail while buffering. 

**Changes**
removed buffertimer duration from the xml file
added duration to the brs file to 10 seconds for all files and 30 seconds for live streams. 

**Issues**
Helps stop buffer fails on live tv streams.

2022-04-29 19:01 UTC, jimdogx commented on components/JFVideo.brs
> +print m.bufferCheckTimer.duration
Don't forget to remove debug statements 😄

2022-04-30 05:17 UTC, candry7731 commented
Damit, I though I removed them all! I'll get better ;)

On Fri, Apr 29, 2022, 2:01 PM Jimi ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In components/JFVideo.brs
> <https://github.com/jellyfin/jellyfin-roku/pull/582#discussion_r862073274>
> :
>
> >      end if
>
> -
>
> +print m.bufferCheckTimer.duration
>
>
> Don't forget to remove debug statements 😄
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/582#pullrequestreview-958132497>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRBTB5V645EH5FNORTTVHQWYRANCNFSM5UW5X7SQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-05-09 15:28 UTC, neilsb commented
Looks like something has gone wrong in the merge.  **TVShowDetails.brs** now reverts some of the changes made in a recent PR

2022-05-11 06:54 UTC, neilsb requested changes
There are changes to `TVShowDetails.brs` and `VideoPlayer.brs` in this PR.

If they should be included and are related to the buffer time (which they're not) can you please update the PR description to describe the changes?  If they should be included but are not related to Live TV Buffer Time can you please move them to their own PR?  Otherwise revert the changes in these files.

2022-05-11 14:27 UTC, candry7731 commented
> There are changes to `TVShowDetails.brs` and `VideoPlayer.brs` in this PR.
> 
> If they should be included and are related to the buffer time (which they're not) can you please update the PR description to describe the changes? If they should be included but are not related to Live TV Buffer Time can you please move them to their own PR? Otherwise revert the changes in these files.

This has been fixed and `TVShowDetails.brs` and `VideoPlayer.brs` have been reverted.

2022-05-11 15:55 UTC, neilsb approved these changes

2022-05-11 15:56 UTC, merged