Add Music Library Support
jellyfin-archive/jellyfin-roku-legacy pull request #597
Opened 2022-05-14 22:59 UTC by 1hitsong

Add support for music libraries and audio playback.

**Changes**
Add support to view list of music Artists, Albums, and Songs. Link albums listed in "Latest in Music" section to corresponding album pages.

**Issues**
Fixes #124

2022-05-15 00:22 UTC, jimdogx commented on source/Main.brs
> +    if (m.audio.state = "finished")
```suggestion
    if m.audio.state = "finished"
```

2022-05-22 00:17 UTC, candry7731 commented
GREAT WORK!

1. The background image on the "Now Playing Screen" Does not fill the entire screen.
![image](https://user-images.githubusercontent.com/83685828/169673046-6083d726-d324-459d-b916-33c60fe25012.png)

2. The next button restarts the current song when user selects a song to play in the song list, However "next" does work when selecting "Play Album".

2022-05-26 00:40 UTC, cewert requested changes
Great job on this.

I was playing an album and noticed the album image sort of flickers when changing songs. We should only pull in new images when needed. That would fix the flicker when switching songs on albums but I assume the problem would persist when playing playlists (I haven't tested).

When the images do change we should update them using a task node. Task nodes run on a different thread. That way the overhang could be updated immediately and the song would start playing much sooner on the main thread.

2022-05-26 00:40 UTC, cewert commented on components/music/NowPlaying.brs
> +    setBackdropImage()
When playing an album we know the artist(bg image) and album images won't be changing, it would be great if we could track the artist and album somehow. Then only pull in new images when those values change. 

Maybe string fields in the NowPlaying.xml? then you'd just have to set those values somewhere in the CreateAudioPlayerGroup() function in ShowScenes.brs. And then update those values here in this function when the new value doesn't equal the old one. Think that would work?

2022-05-26 01:00 UTC, cewert commented on components/music/NowPlaying.brs
> +        m.top.findNode("backdrop").uri = m.top.backgroundContent[m.top.audio.contentIndex]
Best practice would be calling `m.top.findNode()` on `init()` and then saving the node reference as a variable on m to be used later by other functions in the same file. This is because its more efficient to use the node reference than to lookup the node every time. So `m.backdrop = m.top.findNode("backdrop")` in `init()` then this line would be `m.backdrop.uri = m.top.backgroundContent[m.top.audio.contentIndex]`

If you end up making a task node to update the images this wouldn't be needed but thought I'd mention it anyway.

2022-05-26 01:01 UTC, cewert commented on components/music/NowPlaying.brs
> +    if m.top.findNode("buttons").hasFocus()
same as line 109 although this one has nothing to do with images

2022-05-26 01:02 UTC, cewert commented on components/music/NowPlaying.brs
> +        m.top.findNode("albumCover").uri = posterURL
Same as line 109

2022-05-26 11:47 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    setBackdropImage()
Thanks! This is my first time working in Brightscript. It's been fun learning.

I did a rework of how I get the metadata for the song and used a task node for it. My hope was it would make playback quicker. It turns out the load time for the audio far exceeds the load time for the metadata and image. /shrug

However, beyond just the raw load time, I do like only making calls when needed. I have many albums that are compilations and will load new artist images each play, and future thinking, playlists will load new album images each time, but if we can save trips on album plays, I'm in!

I'll see what I can some up with.

2022-05-26 11:53 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +        m.top.findNode("albumCover").uri = posterURL
:+1:

2022-05-26 11:53 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    if m.top.findNode("buttons").hasFocus()
:+1:

2022-05-26 11:53 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +        m.top.findNode("backdrop").uri = m.top.backgroundContent[m.top.audio.contentIndex]
:+1:

2022-05-26 13:02 UTC, cewert commented on components/music/NowPlaying.brs
> +    setBackdropImage()
> This is my first time working in Brightscript. It's been fun learning.

Well you're doing great. Better than I was first starting. Hopefully you're still having fun after a few PRs :smile:

> I did a rework of how I get the metadata for the song and used a task node for it. My hope was it would make playback quicker. It turns out the load time for the audio far exceeds the load time for the metadata and image. /shrug

Do you still have this code laying around so I can take a look? or could you expand a little bit here about the approach you took?

2022-05-26 13:32 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    setBackdropImage()
I don't have it. I did it on a test branch, and when it didn't affect anything, I discarded it thinking it needs a fresh approach.

My focus was on reducing the start time when playing large albums. I have several self-made albums with 300+ songs and when playing the album it takes several seconds before audio plays. 

With my current approach, when the user clicks on Play Album, we fetch metadata for every song and hold it until needed. Thinking this was the bottleneck, I created a new loadtask to only fetch metadata on playback. This way it was ondemand. But it didn't affect playback speed. Instead, I now believe the bottleneck is how we generate the audio playlist content. When I have time, I'd like to try not using playlist content for the audio node and instead handle the playlist in code so we only load the audio data for the current song and not the entire album. Perhaps this will speed things up.

2022-05-27 01:22 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    setBackdropImage()
Here's my thought. In the end I want to follow through what I proposed above. I believe it'll speed up playback, but I want to rework all of that logic together, so for this first MVP push, I'll add a check to not change overhangTitle, backdropImage, and albumArt if their values don't change. That way we only update when needed.

Then this gives us further time to do it right, while gathering feedback for this first pass.

How does that sound?

2022-05-27 01:26 UTC, 1hitsong commented
@cewert Changes made and pushed.

2022-05-27 01:46 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    setBackdropImage()
Sorry to pile on, but I I added the "change check" and it was successful in preventing flicker between songs.

2022-05-27 03:41 UTC, cewert commented on components/music/NowPlaying.brs
> +    setBackdropImage()
Thanks for expanding.

I've never used the audio node so I'm not sure the best way to go about that as far as playlists and whatnot. I've just been bit by the main(UI) thread being blocked by api calls and things like that. Took me a while to wrap my head around the two different threads and what they should be used for. Then there's the whole [thread rendezvous  stuff](https://developer.roku.com/en-ca/docs/developer-program/core-concepts/threads.md#thread-rendezvous) there's even a special debug command for debugging them 😅

So yea I just want to make sure you're using the right approach with threads because they can be a PITA and don't want to see you get burnt out writing it out 5 different ways.

I like the MPV route and testing along the way. I guess the question becomes what should be in the MVP? as far as pushing to stable. Once it's out there and "enabled" people will start to have expectations. Feedback is great but it's not always constructive feedback plus more reddit/github support work for us. I'd like to hear the rest of the team weigh in on this one.

PS: I should have told you about this before but check out the [brightscript profiler](https://developer.roku.com/en-ca/docs/developer-program/dev-tools/brightscript-profiler.md). That should help you track down your bottleneck. The rest of the roku apps for development are [here](https://devtools.web.roku.com/). RALE is another good one.

2022-05-28 00:27 UTC, cewert commented on components/music/NowPlaying.brs
> +    setBackdropImage()
Looked at this again with fresh eyes. Couple things to add.

> ...but I want to rework all of that logic together, so for this first MVP push...

So maybe I'm misunderstanding but shouldn't the MVP be something stable you can build off of? Or in other words, what's the point of pushing an MVP to get feedback, when all the feedback will be on the old code?

As far as pushing too soon to stable, the overall point I was trying make is doing so will add support work for the roku guys (you included). We're all volunteers and can come and go as we please. So even though I love the way you want to do it with the MVP you could disappear next week and it would be up to everyone else on the team to maintain and support whatever you wrote. The whole bus factor thing. Which is another great reason to start with a stable well-tested MVP. I'm not saying it would be the end of the world but it's definitely something that needs to be considered before jumping in with both feet.

Speaking of testing, do you think the MVP has been tested enough to get pushed? I've only tested it twice and used it for 5min each time. I haven't found an album to test with different artists. I made some playlists on web but couldn't figure out how to play them on roku. They weren't in the "Playlists" library like I expected them to be.

And what exactly do you even want me testing? Whats the Minimum functionality required for this MVP? Usually MVP's have very specific goals but I don't see yours written anywhere.

2022-05-28 01:04 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    setBackdropImage()
Thanks for the links to the brightscript profiler. I'm using it now to investigate ways to use load tasks to speed up song load time. As suspected, the audio node playlist generation was the bottleneck. I'm currently in the process of reworking the audio node playlist functionality so we can load audio data on-demand. It has majorly sped up the time to audio playback.

In my experience, the point of an MVP product is to generate what we believe is the minimum viable product that solves at least part of some problem. As stated in the roadmap, I've personally defined that as "Basic functionality to get single song and album playback working." Likewise, I posed the question in the Jellyfin Roku Developer chat and others agreed with this being a good first step. This is why your Playlists aren't showing. This change only activates the Music library and gives users the ability to play songs and albums of songs, both of which are not possible right now.

Playlists will be a project of their own, ESP since they can have mixed content :laughing: 

As for if I believe it's been test enough to get pushed, I'm unsure how to answer that. This is my first time working on this project. How many people typically test? What's your typical reviewer count when reviewing PRs? Personally, I've played ~1000 songs while testing this; however, with the new loadtasks rework I'm finishing up now, I'll be doing more testing and be asking others in the chat to retest with me.

2022-05-28 02:45 UTC, cewert commented on components/music/NowPlaying.brs
> +    setBackdropImage()
> Thanks for the links to the brightscript profiler. I'm using it now to investigate ways to use load tasks to speed up song load time. As suspected, the audio node playlist generation was the bottleneck. I'm currently in the process of reworking the audio node playlist functionality so we can load audio data on-demand. It has majorly sped up the time to audio playback.

Very nice. Great job 👍 

> I've personally defined that as "Basic functionality to get single song and album playback working."

OK fair enough. Does that include showing songs and albums in search results? I don't see that listed in your roadmap.

> This is why your Playlists aren't showing.

So if we don't support playlists why are we showing the playlist library on the home screen? The only time I use playlists is for music and I use a different app for that currently. So when I made my first playlist then saw the playlist library listed in My Media I figured it would work. We should probably remove the playlists library until we support them

> Playlists will be a project of their own, ESP since they can have mixed content 😆

That's fair. Me personally, I listen to playlists 99% of the time when I'm listening to my music. So, I would've considered that part of an MVP but since we don't support playlists and you said they can have multiple types, which I didn't know, I totally get it.

> As for if I believe it's been test enough to get pushed, I'm unsure how to answer that. This is my first time working on this project. How many people typically test? What's your typical reviewer count when reviewing PRs?

There's been several times over the years where you'd be lucky to get one reviewer 😄 You seem to have a pretty good understanding of the code base and brightscript. You're the only one who's worked on audio nodes. You seemed like a good person to ask.

> with the new loadtasks rework I'm finishing up now, I'll be doing more testing and be asking others in the chat to retest with me.

Nice so that will be part of the MVP? I assume by chat you mean matrix? I'm hardly ever on there, can you do me a favor and make sure people like me stay in the loop? This PR title is "Add Music Library Support" and text is "Add support for music libraries and audio playback." so that's what I started reviewing.

2022-05-28 11:32 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +    setBackdropImage()
> OK fair enough. Does that include showing songs and albums in search results? I don't see that listed in your roadmap.

It doesn't, but I'll add it to the roadmap. Thanks!

> So if we don't support playlists why are we showing the playlist library on the home screen?

Excellent question that I don't know the answer to. 

It's similar to why I got involved with this code in the first place. Music has been on the Jellyfin Roku for as long as I can remember, both in library selection and a Latest Music selection on the Home screen, but both lead to a popup stating it's unsupported. My base level goal for this was to make a path for both of these sections that end up with the user hearing music :)

> We should probably remove the playlists library until we support them

I 100% support this.

> There's been several times over the years where you'd be lucky to get one reviewer smile You seem to have a pretty good understanding of the code base and brightscript. You're the only one who's worked on audio nodes. You seemed like a good person to ask.

At work we have at least 2 sets of eyes look at our tickets before it gets merged. 

1 is focused at the code level (does it follow code standards, is it maintainable, is it testable, does it have test coverage, etc.) and the other is focused on the result level (does it meet the stated goals, how does it fit into upcoming ticket goals, how easy is it for the user to use, does it mess with anything else on page, etc.)

Perhaps we can adopt an adapted version of this, because to be honest your statement "There's been several times over the years where you'd be lucky to get one reviewer" scares me :laughing: 

> Nice so that will be part of the MVP? I assume by chat you mean matrix? I'm hardly ever on there, can you do me a favor and make sure people like me stay in the loop? This PR title is "Add Music Library Support" and text is "Add support for music libraries and audio playback." so that's what I started reviewing.

Yes, the task rework will be part of MVP. I've completed the load tasks and the app functionality is back where it was before - just much faster :smiley:  I have 1 annoying thing I want to figure out before I commit the code and the PR is updated.

Yes, I joined the matrix chat at the suggestion of Anthony Lavado. I first started working on my own personal Roku audio player that linked up with Jellyfin using the API, but decided it made more sense to apply the functionality to the Roku app.

I updated the PR title to include the goals the PR aims to hit.

2022-05-28 13:24 UTC, cewert commented on components/music/NowPlaying.brs
> +    setBackdropImage()
> Perhaps we can adopt an adapted version of this, because to be honest your statement "There's been several times over the years where you'd be lucky to get one reviewer" scares me

We've wanted to have two reviewers required for years but there was never enough Roku devs for it to work. At times there was only one roku dev and we'd have anthony or jellyfin guys from other projects who don't know brightscript approve our PRs just so we could push code. Those were the days 😅 

> Yes, the task rework will be part of MVP. I've completed the load tasks and the app functionality is back where it was before - just much faster 😃 I have 1 annoying thing I want to figure out before I commit the code and the PR is updated.

Very nice. I'll mark this as resolved and take another look once it's ready

2022-05-29 18:45 UTC, 1hitsong commented
@cewert PR updated with discussed audio load speed improvements.

2022-05-31 01:44 UTC, candry7731 commented
Love the buffer/progress bar. I also like the icons instead of the button names. 

I'm getting an error when switching albums and pressing a remote key before the album info is loaded. the reason I pressed a key is because the "Play Album" button is visible before the album data is loaded and rendered on the screen. 

Maybe you can hide the "Play Album" button until the album data is fully loaded. Below is a screen shot of my error.  

![image](https://user-images.githubusercontent.com/83685828/171076267-212c9644-f36f-4fdd-86c3-aebb2336edf7.png)

2022-05-31 03:25 UTC, jimdogx commented
I noticed that if an album has a long description it gets cut off.  It's the same problem that happened on "Movie Extras" (cast and crew info).  It was solved with an "Ok for more" and then it pops up a modal.  Just a thought.

2022-05-31 11:46 UTC, 1hitsong commented
@candry7731 Latest push should fix your issue, please retest.

2022-05-31 12:28 UTC, 1hitsong commented
> I noticed that if an album has a long description it gets cut off. It's the same problem that happened on "Movie Extras" (cast and crew info). It was solved with an "Ok for more" and then it pops up a modal. Just a thought.

Same with artist description. I'll implement an overflow popup for both.

2022-05-31 19:57 UTC, 1hitsong commented
@jimdogx Newest push should address description overflow for artists and albums. Please review.

2022-06-01 03:36 UTC, cewert reviewed
Great job on this. My server is local but albums and songs loaded noticeably faster. The now playing screen looks great and the buffering bars improve UX a ton. It was fun to use.

- fast forward and rewind buttons are being using as last song and next song. I think it's cool to have that functionality but my brain (and I assume everyone else who uses a roku remote in the dark) is so used to that being rewind and ff from watching videos it just feels wrong. Maybe use left and right arrow instead? Plus if we implement rewind and ff for audio, how would that work with the current setup?
- if the current song you're playing is almost over and then you switch songs, the blue playback indicator slowly fades out to the left and in my case met the grey buffer bar in about the middle. It was kind of confusing the first couple times. maybe it's just me but I think it'd be better UX to instantly remove the blue bar on song change.
- when the now playing screen reappears on screen after exiting the screensaver, the blue playback bar kind of freaks out. it speeds up at first, then slows down, then seems to sync up. so it works fine but maybe we could instantly sync it

2022-06-01 14:03 UTC, cewert approved these changes

2022-06-01 14:06 UTC, cewert commented
Whoops. Was trying to clear out my request for changes not approve the PR

2022-06-01 14:48 UTC, 1hitsong commented
> if the current song you're playing is almost over and then you switch songs, the blue playback indicator slowly fades out to the left and in my case met the grey buffer bar in about the middle. It was kind of confusing the first couple times. maybe it's just me but I think it'd be better UX to instantly remove the blue bar on song change.

Simple fix. On it.

> when the now playing screen reappears on screen after exiting the screensaver, the blue playback bar kind of freaks out. it speeds up at first, then slows down, then seems to sync up. so it works fine but maybe we could instantly sync it

I'll take a look at the screensaver code and see what hooks are available when returning to the screen

> fast forward and rewind buttons are being using as last song and next song. I think it's cool to have that functionality but my brain (and I assume everyone else who uses a roku remote in the dark) is so used to that being rewind and ff from watching videos it just feels wrong. Maybe use left and right arrow instead? Plus if we implement rewind and ff for audio, how would that work with the current setup?

Let's talk about this one a bit more. 

In my experience, for audio playback, using these remote control buttons for previous/next song is the standard. This is how they do it in Pandora, Amazon Music, iHeartRadio. When a user wants to rewind/fast forward the audio, they can navigate to the ball indicator in the song seek bar and move it where they want it. This is how I was envisioning adding this functionality. 

This function is already in the roadmap as well "See if possible to add song progress bar & allow user to move through song using it"

2022-06-01 15:32 UTC, cewert commented
> I'll take a look at the screensaver code and see what hooks are available when returning to the screen

This is where we grab the event that the screensaver throws when it exits. It's only set up to refresh the custom clock and the home screen at the moment.

https://github.com/jellyfin/jellyfin-roku/blob/bacaf9071f148fba2ba394de7ca5b95ca926b1f1/source/Main.brs#L323-L337

2022-06-01 15:44 UTC, cewert commented
> In my experience, for audio playback, using these remote control buttons for previous/next song is the standard. This is how they do it in Pandora, Amazon Music, iHeartRadio. When a user wants to rewind/fast forward the audio, they can navigate to the ball indicator in the song seek bar and move it where they want it. This is how I was envisioning adding this functionality.

> This function is already in the roadmap as well "See if possible to add song progress bar & allow user to move through song using it"

You make some great points. The only thing about those apps is they are dedicated to audio vs jellyfin which has to deal with video, audio, pictures etc. But there's only so many buttons on the roku remote and skipping songs seems like it would be used way more than rewind and ff would.  So I think your current approach is best.

2022-06-01 16:49 UTC, 1hitsong commented
Fixed your 2 items, but in doing so uncovered a new issue. Because I'm no longer using the default audio playlist functionality (reworked in code as part of the speed up) albums no longer move from song to song if the screensaver is active. I guess because the screensaver scene is now active, it's no longer watching for the same events as it does when NowPlaying is active.

I'll dig into this later tonight.

2022-06-01 23:27 UTC, jimdogx commented
> @jimdogx Newest push should address description overflow for artists and albums. Please review.

Looks good 👍

2022-06-02 01:10 UTC, 1hitsong commented
Screensaver issue resolved.

2022-06-04 02:52 UTC, jimdogx approved these changes

2022-06-06 12:16 UTC, merged

2022-07-08 02:07 UTC, gbcox commented
Any idea when this will be available on the released Roku client.  I'm running version 1.4 build 12 and it doesn't work, so I'm guessing it is yet to be pushed.  Thanks!