Adds vscode launch config and update dev guide
jellyfin-archive/jellyfin-roku-legacy pull request #610
Opened 2022-05-26 12:18 UTC by TwitchBronBron

**Changes**
- Adds a baseline `.vscode/launch.json`
- remove the `.vscode` exclusion from .gitignore
- update devguide with some information about hardcoding vscode username/password 

**Issues**

- Fixes #607

2022-05-26 12:19 UTC, TwitchBronBron commented on DEVGUIDE.md
>  ## Method 3: Visual Studio Code
I'd love to make VSCode Method 1 instead of 3. It's by far the most developer friendly, imho. Would that be alright?

2022-05-26 12:24 UTC, cewert commented on .vscode/launch.json
> +            //"password": "${promptForPassword}",
Need to uncomment the host and password if it's going to work "out of the box"

2022-05-26 12:31 UTC, cewert commented on DEVGUIDE.md
>  ## Method 3: Visual Studio Code
👍 VSCode is all I use and I agree it's the most user friendly. It also should make it easier for the average user to sideload the beta version which may lead to more users posting logs for bug reports which would be a huge win.

2022-05-26 12:34 UTC, TwitchBronBron commented on .vscode/launch.json
> +            //"password": "${promptForPassword}",
These are the default values for `host` and `password` and thus are optional. Any `launch.json` values will override user settings, and that's the opposite of what we want (we want users to be able to override the values without needing to modify launch.json). 

I left them commented out here as "documentation" for guiding users away from manually editing the launch.json (to hopefully reduce accidentally including their info in PRs). 

Here's a quick demo showing it works correctly with this configuration:
![vscode-default-launch](https://user-images.githubusercontent.com/2544493/170488610-bc196f94-a0a0-4d98-a239-1a5a2a2cc6f4.gif)

2022-05-26 12:40 UTC, cewert commented on .vscode/launch.json
> +            //"password": "${promptForPassword}",
My fault. I didn't know they were the defaults.

Your approach is best because it further decreases the risk of a user accidentally committing their login info to git.

2022-05-26 19:12 UTC, cewert commented
I just want to add that this will make it easier to test PRs when using VSCode. My current workflow involves me manually copying over my .vscode folder. This PR would eliminate that step :heart:

2022-05-27 20:06 UTC, TwitchBronBron commented
I updated the devguide with some more vscode-specific information and made it the first option.

2022-05-27 21:14 UTC, jimdogx commented on DEVGUIDE.md
> +Out of the box, the VSCode extension will prompt you to pick a Roku from your device and enter a password on every launch. If you'd prefer to hardcode this information rather than entering it every t
```suggestion
Out of the box, the VSCode extension will prompt you to pick a Roku device (from devices found on your local network) and enter a password on every launch. If you'd prefer to hardcode this information rather than entering it every time, you can set these values in your vscode user settings:
```

2022-05-27 23:13 UTC, cewert commented on .vscode/launch.json
> +            "name": "BrightScript Debug: Launch",
I think we should have the word jellyfin in here but maybe I'm missing something.

Not every brightscript app will have the same file structure as we do; this launch config is only guaranteed to work with the jellyfin app. Plus this is the name that shows up in the little dropdown when viewing the debug tab on VSCode. It could help streamline things for people new to both VSCode and Brightscript.
![Capture](https://user-images.githubusercontent.com/16514652/170799051-3fd09812-57b8-43af-916f-3e388c93cb21.PNG)

```suggestion
            "name": "Jellyfin Debug: Launch",
```

2022-05-27 23:19 UTC, cewert commented on .vscode/launch.json
> +            "name": "BrightScript Debug: Launch",
I was going to say we should update your screenshot but your pic is of the run menu.

So we have 3 ways of doing it. F5, run ->debug, or debug tab -> click triangle. Including them all seems overkill but i like the idea of including the debug tab method. It kind of teaches noobies to check out the debug tab while running the app which they may not be familiar with. Thoughts?

Edit: After hitting F5 it auto switches to the debug tab so probably not as helpful as i was thinking

2022-05-27 23:43 UTC, cewert commented on DEVGUIDE.md
> +Out of the box, the VSCode extension will prompt you to pick a Roku device (from devices found on your local network) and enter a password on every launch. If you'd prefer to hardcode this informatio
Maybe change this to "Brightscript extension"? VSCode won't prompt for anything without it

```suggestion
Out of the box, the Brightscript extension will prompt you to pick a Roku device (from devices found on your local network) and enter a password on every launch. If you'd prefer to hardcode this information rather than entering it every time, you can set these values in your vscode user settings:
```

2022-05-27 23:55 UTC, cewert requested changes
Amazing job on the docs. Thank you. Just a couple things for you to look at then I think we're good

2022-05-28 01:45 UTC, TwitchBronBron commented on .vscode/launch.json
> +            "name": "BrightScript Debug: Launch",
>I think we should have the word jellyfin in here but maybe I'm missing something.
>
>Not every brightscript app will have the same file structure as we do; this launch config is only guaranteed to work with the jellyfin app. Plus this is the name that shows up in the little dropdown when viewing the debug tab on VSCode. It could help streamline things for people new to both VSCode and Brightscript.

This launch.json only applies to this specific workspace folder, and it doesn't leak into other workspace folders when having them open in other vscode windows. I can see us adding a unit test launch config in the future, and many of the other Roku projects I work on have a few NodeJS launch configs as well to help when debugging custom scripts. 

I'm ok with using the word "Jellyfin" to it if you want it there, but I think the default name works fine since it's scoped to this specific vscode workspace folder.

2022-05-28 01:45 UTC, TwitchBronBron commented on .vscode/launch.json
> +            "name": "BrightScript Debug: Launch",
>I was going to say we should update your screenshot but your pic is of the run menu.
>
>So we have 3 ways of doing it. F5, run ->debug, or debug tab -> click triangle. Including them all seems overkill but i like the idea of including the debug tab method. It kind of teaches noobies to check out the debug tab while running the app which they may not be familiar with. Thoughts?
>
>Edit: After hitting F5 it auto switches to the debug tab so probably not as helpful as i was thinking

Yeah, I'm not overly worried about fully documenting all the various ways to start a debug session within vscode. What I wrote shows power users the F5 keyboard shortcut, and shows the GUI users a UI menu. That's probably enough.

2022-05-28 02:02 UTC, cewert commented on .vscode/launch.json
> +            "name": "BrightScript Debug: Launch",
> I'm ok with using the word "Jellyfin" to it if you want it there, but I think the default name works fine since it's scoped to this specific vscode workspace folder.

Yea I don't think there's anything wrong with the way it is. Just thought seeing Jellyfin there on the debug page might help some people if they come across it and I couldn't see any downside. Was thinking more about regular users trying to give us bug logs than devs.

If you don't see any downside I say we do it.

2022-05-28 02:51 UTC, cewert approved these changes

2022-05-28 02:53 UTC, merged