Feature/jf 528 quick connect
jellyfin-archive/jellyfin-roku-legacy pull request #620
Opened 2022-05-30 05:04 UTC by jimdogx

Adds Quick Connect.

**Changes**
* Enables Quick Connect with servers 10.8.
* ConfigScene looks to have been originally thought to be used for configurations, but its sole purpose is for Login. So I've renamed it accordingly.

**Issues**
Fixes: #528

2022-05-30 13:22 UTC, crobibero commented
Has this been tested against a server running 10.7?
QuickConnect existed in that version but the authenticate calls differ

2022-05-30 15:46 UTC, jimdogx commented
> Has this been tested against a server running 10.7? QuickConnect existed in that version but the authenticate calls differ

Was only planning on supporting 10.8+. It is going to be released soon right? 😄

2022-05-30 15:59 UTC, crobibero commented
Soon™️ 

Even when 10.8 is released there will still be people that don't update... So we'll want to ensure that QuickConnect isn't displayed if they're on an unsupported version

2022-05-30 17:00 UTC, jimdogx commented
> Soon™️
> 
> Even when 10.8 is released there will still be people that don't update... So we'll want to ensure that QuickConnect isn't displayed if they're on an unsupported version

I'll go through soon (maybe tonight) and either hide it for 10.7 or just make it work 👍

2022-05-31 07:56 UTC, neilsb requested changes
Looks good, and working perfectly (in my limited testing).   Suggestion on the version string, but other than that looks good to go.

2022-05-31 07:56 UTC, neilsb commented on locale/en_US/translations.ts
> +        <translation></translation>
```suggestion
        <source>(Dialog will close automatically)</source>
        <translation>(Dialog will close automatically)</translation>
```
Think in the master version the translation should be set?

2022-05-31 08:01 UTC, neilsb commented on source/ShowScenes.brs
> +    if InStr(1, m.serverInfoResult.Version, "10.7") = 0
(Oops - didn't save this comment on the review)

Version strings.  Oh the fun.

This will currently match anyone using `10.6.x` or earlier and also will match when we hit `10.10.7` etc.

```suggestion
    regEx =  CreateObject("roRegex", "\.", "") ' split on period
    ver = regEx.split(m.serverInfoResult.Version)
    if ver[0].toInt() >= 10 and ver[1].toInt() >= 8     
```
Simple solution would be to split on the period.  Could do something more complex, and maybe that will be needed later on if (or rather when) we have more conditional code based on server version.

2022-05-31 12:10 UTC, jimdogx commented on source/ShowScenes.brs
> +    if InStr(1, m.serverInfoResult.Version, "10.7") = 0
Really I should just make QC work for 10.7 as well, but I'm being lazy LOL.

2022-05-31 12:26 UTC, crobibero commented on source/ShowScenes.brs
> +    if ver.Count() >= 2 and ver[0].toInt() >= 10 and ver[1].toInt() >= 8
Not that we're close to v11, but this check will fail for 11.0

2022-05-31 12:45 UTC, neilsb commented on source/ShowScenes.brs
> +    if ver.Count() >= 2 and ver[0].toInt() >= 10 and ver[1].toInt() >= 8
Dang version strings...

2022-06-01 00:15 UTC, jimdogx commented on source/ShowScenes.brs
> +    if ver.Count() >= 2 and ver[0].toInt() >= 10 and ver[1].toInt() >= 8
> Not that we're close to v11, but this check will fail for 11.0

Are you sure @crobibero ?  It says "greater than or equal to 10".

2022-06-01 00:15 UTC, jimdogx commented on source/ShowScenes.brs
> +    if ver.Count() >= 2 and ver[0].toInt() >= 10 and ver[1].toInt() >= 8
I figure that by the time JF is at v11, this check can be removed all together.  People should have moved off of 10.7 by then (I hope).

2022-06-01 05:09 UTC, jimdogx commented
@crobibero @neilsb 

I added a crude version checker.  I think it's plenty for our needs.  Let me know if you see any flaws.  Here are the results from a quick unit test I wrote:

![Screen Shot 2022-05-31 at 11 01 32 PM](https://user-images.githubusercontent.com/18198517/171332056-559a8d39-0d09-4c1f-a5a7-1510da2ff4a7.png)

2022-06-01 06:42 UTC, neilsb commented on source/utils/misc.brs
> +' to some minimum version alloed (e.g. 10.8.0)
```suggestion
' to some minimum version allowed (e.g. 10.8.0)
```

2022-06-01 06:44 UTC, neilsb approved these changes
I like the version checking.  In 2 years you're going to look back at it and go "Why the heck did we do it that way".  🤣 

I think I may implement a cut down `semver` implementation for roku and create a _ropm_ package for it if I get the time.

2022-06-01 23:02 UTC, crobibero approved these changes

2022-06-01 23:03 UTC, merged