Add Playlist Functionality
jellyfin-archive/jellyfin-roku-legacy pull request #638
Opened 2022-06-06 16:15 UTC by candry7731

Add Playlist functionality to Home/Grid screens. 

**Changes**
Added Playlist collection type

2022-07-02 12:44 UTC, 1hitsong requested changes
Adding mixed media results in a lackluster viewing experience. Movies get artwork. Songs and TV shows don't.

As it stands, this change allows you to access and view playlists, and play each item one at a time. I think since this is for playlist functionality we need it to move from the item the user selects to the next.

I'd also like to see the items in the list view, similar to how songs are listed on album detail pages, and how the web view displays playlists. The grid layout doesn't indicate to the user that items will play in the order they appear.

![WIN_20220702_08_37_32_Pro](https://user-images.githubusercontent.com/3330318/177001056-6bb0e938-2fc8-48cb-98e9-a80324647614.jpg)

2022-07-02 12:44 UTC, 1hitsong commented on components/ItemGrid/GridItem.brs
> +        print "Episode data: " itemData
Debug code

2022-07-02 12:44 UTC, 1hitsong commented on components/ItemGrid/LoadItemsTask2.brs
> +            else if item.Type = "Episode"
Adding this section causes a warning when you include a TV episode in your playlist:

`Warning occurred while setting a field of an RoSGNode
-- Tried to set nonexistent field "favorite" of a "TVEpisodeData" node
pkg:/components/ItemGrid/LoadItemsTask2.brs(93)`

2022-07-09 12:40 UTC, candry7731 commented
> Adding mixed media results in a lackluster viewing experience. Movies get artwork. Songs and TV shows don't.
> 
> As it stands, this change allows you to access and view playlists, and play each item one at a time. I think since this is for playlist functionality we need it to move from the item the user selects to the next.
> 
> I'd also like to see the items in the list view, similar to how songs are listed on album detail pages, and how the web view displays playlists. The grid layout doesn't indicate to the user that items will play in the order they appear.
> 
> ![WIN_20220702_08_37_32_Pro](https://user-images.githubusercontent.com/3330318/177001056-6bb0e938-2fc8-48cb-98e9-a80324647614.jpg)
> 

Can you check now? This has been updated to use the episode row scene

2022-07-09 14:07 UTC, 1hitsong commented
@candry7731 I'm away from home until next week. I'll check it out when I return 🤘

2022-07-09 14:30 UTC, candry7731 commented
> @candry7731 I'm away from home until next week. I'll check it out when I return 🤘

Sounds good! Thanks

2022-07-12 15:32 UTC, cewert commented on components/ItemGrid/GridItem.brs
> +        print "Episode data: " itemData
@candry7731 this still needs addressed

2022-07-12 15:32 UTC, cewert commented on components/ItemGrid/LoadItemsTask2.brs
> +            else if item.Type = "Episode"
@candry7731 this still needs addressed

2022-07-12 15:34 UTC, cewert commented
Marking this as draft till all the current issues are resolved. Please mark this PR as "ready for review" once everything is tested and you think it's ready to be merged

2022-07-16 11:49 UTC, 1hitsong commented
This messes up the display of the Music library posters. Here's what I'm seeing for each branch.

Master
![Master](https://user-images.githubusercontent.com/3330318/179353587-9e3d31e0-f288-4ef2-bb7a-0aa13c3dbdd6.jpg)

Playlist
![Playlist](https://user-images.githubusercontent.com/3330318/179353591-de236e5d-3219-4db2-afd5-d4055c10d041.jpg)

2022-07-16 12:03 UTC, 1hitsong commented
- [ ] On the main Playlist Grid View, let's use square posters instead of the tall ones.
- [ ] On the playlist list view, let's use square posters here as well, similar to the album detail screen
- [ ] On the playlist list view, let's make the rows smaller. I know it'll make the artwork difficult to really see, but in this view I think that's 100% fine.
- [ ] Movie posters in playlist list view are resized and squished to be square, making them look bad. Instead let's size it down and crop it to be square, like the webview does.
- [ ] Add Play button to playlist list view to make it play through the playlist from start to finish 😸 
- [ ] I played an episode from the playlist. At the end of the episode I expected it to play the next items in the playlist, instead it played the next episode in the series, which isn't in the playlist.

2022-07-16 12:15 UTC, 1hitsong requested changes

2022-07-16 12:15 UTC, 1hitsong commented on components/ItemGrid/ItemGrid.brs
> +    else if m.top.parentItem.collectionType = "books"
Dunno if we want/need to add any more book code at this moment.

2022-07-16 12:15 UTC, 1hitsong commented on components/music/NowPlaying.brs
> +            setPosterImage(data.posterURL)
This line is duplicated and can be moved outside of the conditional statement.

2022-07-16 12:15 UTC, 1hitsong commented on source/Main.brs
> +                'sceneManager.callFunc("pushScene", group)
Commented out code should be removed

2022-07-18 16:50 UTC, candry7731 commented on components/ItemGrid/ItemGrid.brs
> +    else if m.top.parentItem.collectionType = "books"
This is to get the audiobook to display the parent folders when selecting audiobook form the home screen nav.

2022-07-19 02:42 UTC, candry7731 commented on components/ItemGrid/LoadItemsTask2.brs
> +            else if item.Type = "Episode"
this has been fixed

2022-07-20 04:12 UTC, candry7731 commented
> * [X]  On the main Playlist Grid View, let's use square posters instead of the tall ones.
> * [X]  On the playlist list view, let's use square posters here as well, similar to the album detail screen
> * [X]  On the playlist list view, let's make the rows smaller. I know it'll make the artwork difficult to really see, but in this view I think that's 100% fine. 
> * [X]  Movie posters in playlist list view are resized and squished to be square, making them look bad. Instead let's size it down and crop it to be square, like the webview does. - **I set this to scaleToFit, I like this view better than cropped**
> * [X]  Add Play button to playlist list view to make it play through the playlist from start to finish 😸 - **I added the button but there is no functionality** 
> * [ ]  I played an episode from the playlist. At the end of the episode I expected it to play the next items in the playlist, instead it played the next episode in the series, which isn't in the playlist.

2022-10-23 02:13 UTC, closed without merging