Create Artist & Album view for music library
jellyfin-archive/jellyfin-roku-legacy pull request #640
Opened 2022-06-07 00:35 UTC by 1hitsong

**Changes**
Added Artist and Album sorting to the music library, in addition to the default view. Artist view is a list of all known artists in JF as found using MusicArtist item type. Album view is a list of all known albums in JF as found using MusicAlbum item type.

**Issues**
N/A. This is a New Feature.

2022-06-07 03:27 UTC, candry7731 commented
1. Default view is the artist view, I would remove the "default" option
2. I would add "songs" view option

2022-06-07 11:46 UTC, 1hitsong commented
> 1. Default view is the artist view, I would remove the "default" option
It's actually a little bit different. The default view displays everything that is a child of the root library. For example, in my library I mostly have artists, but I also have several albums of songs that aren't under an artist. These albums appear in the default view, but under Artist view, they're not shown because they have no artist value.

Perhaps we can change "Default" to something more descriptive to explain the different. Any ideas? 

Root? Folder? Base?

> 2. I would add "songs" view option

In an effort to keep these PRs smaller than the last, I'm limiting how much I change. Song view will be its own separate change after this.

2022-06-10 02:03 UTC, candry7731 commented
> 
I think "Default" is fine. Thanks for the clarification. I didn't notice the no artist albums

2022-06-10 02:04 UTC, candry7731 approved these changes
Functions as intended.

2022-06-11 13:16 UTC, jimdogx requested changes

2022-06-11 13:16 UTC, jimdogx commented on components/ItemGrid/ItemGrid.brs
> -        m.loadItemsTask.fallbackType = "MusicAlbum"
I might be missing it, but I think this is the only place you were setting FallbackType.  If it's no longer being used, can you remove it elsewhere?

2022-06-11 13:43 UTC, 1hitsong commented on components/ItemGrid/ItemGrid.brs
> -        m.loadItemsTask.fallbackType = "MusicAlbum"
:+1: PR Updated

2022-06-11 23:06 UTC, jimdogx approved these changes

2022-06-11 23:06 UTC, merged

2022-06-21 18:32 UTC, lakerssuperman commented
Humble user here again.  I just updated my Roku with the latest master code, but the artist/album sort ability seems to be gone.  The only option under view is "music" and it seems to be a mix of albums with some artists scattered throughout that have multiple albums.  Fully possible I'm doing something wrong or looking in the wrong place.  Just wanted to clarify that this PR merged the aritst/album sorting into master.  Thanks guys!!