Add preroll video support
jellyfin-archive/jellyfin-roku-legacy pull request #644
Opened 2022-06-09 00:35 UTC by 1hitsong

**Changes**
Added functionality to check if preroll videos are enabled and available. If so, they will play before any video, matching the functionality of the web client.

**Issues**
Fixes #448 https://github.com/jellyfin/jellyfin-roku/issues/448

2022-06-21 16:47 UTC, neilsb commented
On the server, while pre-rolls need to be enabled at the server level via the Plug-in, each user has an option whether to play them or not via the User Settings -> Playback -> Cinema Mode option.   We should probably do similar on this client to prevent pre-rolls being forced on the user by a server admin.   We can either use the web "Cinema Mode" option, or add our own User Setting to give similar control on the Roku.

When selecting a partially watched item, the Preroll plays before giving the user the popup menu of Continue / Restart.  Would probably be better to show this menu first (Especially now there are options to mark watched, go to season, go to episode etc).  

On web, if you're select a partially watched item them the preroll doesn't play at all.  Might be worth implementing that too?

2022-06-23 14:53 UTC, 1hitsong commented
> add our own User Setting to give similar control on the Roku.

I love this idea! Let's go this route.

> When selecting a partially watched item, the Preroll plays before giving the user the popup menu of Continue / Restart. Would  probably be better to show this menu first (Especially now there are options to mark watched, go to season, go to episode etc).

>On web, if you're select a partially watched item them the preroll doesn't play at all. Might be worth implementing that too?

100%! I'll work on this as well.

2022-07-01 21:15 UTC, 1hitsong commented
@neilsb Updates made

2022-07-04 06:50 UTC, neilsb requested changes
Looks like it almost perfects now.  The last thing that I just noticed is that when `Automatically play next episode` is selected, the preroll plays between every episode.  I'd suggest it's only wanted at the start of the first episode?

2022-07-04 06:50 UTC, neilsb commented on locale/en_US/translations.ts
> +        <translation>Cinema mode brings the theater experience straight to your living room with the ability to play trailers and custom intros before the main feature.</translation>
```suggestion
        <source>Cinema mode brings the theater experience straight to your living room with the ability to play custom intros before the main feature.</source>
        <translation>Cinema mode brings the theater experience straight to your living room with the ability to play custom intros before the main feature.</translation>
```

Lets not mention trailers before they're included, otherwise folks are going to ask why they're not working :)

2022-07-04 12:40 UTC, 1hitsong commented on locale/en_US/translations.ts
> +        <translation>Cinema mode brings the theater experience straight to your living room with the ability to play trailers and custom intros before the main feature.</translation>
👍

2022-07-04 13:02 UTC, 1hitsong commented
@neilsb Setting content updated. Added code to prevent intros before auto-played next episodes.

2022-07-09 08:21 UTC, neilsb approved these changes
All looks good.

2022-07-09 08:28 UTC, merged