Add setting: Use splashscreen as home background
jellyfin-archive/jellyfin-roku-legacy pull request #654
Opened 2022-06-12 20:38 UTC by 1hitsong

**Changes**
Adds new user setting allowing the user to use their generated splashscreen as their home screen background.

2022-06-12 22:46 UTC, jimdogx requested changes

2022-06-12 22:46 UTC, jimdogx commented on settings/settings.json
> +            },
Don't forget to add these new strings to a locale file (i.e. en-us).

2022-06-13 00:53 UTC, 1hitsong commented on settings/settings.json
> +            },
:+1:

2022-06-13 04:08 UTC, crobibero commented
What is displayed if the splashscreen isn't available?

2022-06-13 11:36 UTC, 1hitsong commented
@crobibero If the splashscreen doesn't load, then the user sees the default grey background. Same as if the setting were disabled.

2022-06-14 01:40 UTC, jimdogx commented
Since the Branding/Splashscreen endpoint doesn't appear to be used in any clients yet, I uploaded an image using Insomnia but when I run the Roku client it doesn't use the newly updated image.

2022-06-14 01:54 UTC, crobibero commented
Does the endpoint return the new image?

2022-06-14 01:58 UTC, jimdogx commented
> Does the endpoint return the new image?

Yes

2022-06-23 13:28 UTC, jimdogx commented
Tested this morning and this is working now??!!??!!  I still get the following server side, but it doesn't appear to affect the client:

`System.NotImplementedException: The method or operation is not implemented.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.ConvertImage(String inputPath, String outputPath) in /Users/jimi/Source/jellyfin-server/MediaBrowser.MediaEncoding/Encoder/MediaEncoder.cs:line 822
   at Emby.Drawing.ImageProcessor.GetSupportedImage(String originalImagePath, DateTime dateModified) in /Users/jimi/Source/jellyfin-server/Emby.Drawing/ImageProcessor.cs:line 466`

2022-06-23 13:30 UTC, jimdogx commented on components/home/Home.brs
> +    end if
Nothing to change for this PR, but the foregroundLayer might be a good user setting.  The particular background I selected for testing shows up too dark for my taste and I'd want to adjust it to be more visible 😄

2022-06-23 13:31 UTC, jimdogx approved these changes

2022-06-23 13:31 UTC, merged

2023-02-27 07:59 UTC, Neoakb commented
Is the splashscreen img generated per user, or per server? Is there a way for me (the server admin) to have a "custom" img to use as the background instead of a generated splashscreen?

Example that I use for the webUI

![image](https://user-images.githubusercontent.com/6175742/221505435-7d1dd587-6f7a-4698-8f2c-0aa3dba4c024.png)

I tried replacing /config/data/splashscreen.png with that same image for the WebUI that I'm using, but it's too big. I tried resizing it in PS but couldn't get the image to update within the app, both main and dev app versions.

If also possible, could this setting be defaulted to "on"?

Also, could this setting be implemented in other clients without too much pain? I understand you who work on this client might not work on others, I'm just looking in terms of general, client approved, background customization. 

I'd love to play around with this myself as I know a tiny bit about coding, but I don't know how helpful I would be. 

Maybe there could be a small logo like img (a smallish transparent png?) that could be generated into the background? I'll look more into how the splashscreen is generated.