Episode popScene MarkItemWatched
jellyfin-archive/jellyfin-roku-legacy pull request #658
Opened 2022-06-13 20:05 UTC by candry7731

Added the MarkItemWatched() to the autoPlayNextEpisode function
This marks the episode in the episode list marked as played

Should fix #616

2022-06-16 03:01 UTC, candry7731 commented
I would like to reload the "Continue Watching" row only but I can not wrap my head around the login so instead I am reloading the entire home scene.... This removes the "Watched Item" from the home scene.

2022-06-25 20:35 UTC, jimdogx requested changes

2022-06-25 20:35 UTC, jimdogx commented on source/VideoPlayer.brs
> +            MarkItemWatched(showID)
Looking at the logic, I think you only need to call MarkItemWatched() once, right before this "IF" block.  Regardless of whether the user can auto play the next episode or not, the "just finished" video can be marked watched.

2022-06-26 13:38 UTC, jimdogx commented
Just tested this, but from the TV Shows page (not the home screen).  When I watch an episode until the end, it auto plays the next episode, but it marks ALL episodes in EVERY season as watched LOL.

2022-06-26 16:13 UTC, candry7731 commented
Weird, maybe we need to change it back to how it was?

On Sun, Jun 26, 2022, 8:38 AM Jimi ***@***.***> wrote:

> Just tested this, but from the TV Shows page (not the home screen). When I
> watch an episode until the end, it auto plays the next episode, but it
> marks ALL episodes in EVERY season as watched LOL.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/658#issuecomment-1166535260>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRDKI4MNSQMYDWT2JHDVRBMNPANCNFSM5YVLK6EQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-06-27 13:07 UTC, jimdogx commented
> Weird, maybe we need to change it back to how it was?

I haven't stepped through the code, but I'm guessing that "showID" is the entire "Show".  What you probably need is just the episode.  It looks like autoplay works by querying for the show and getting two episodes and then playing the second one in the array.  Again, I'm not familiar with this code, but I'm wondering if the first item in the array is the episode just played?

I'm talking about these lines:

```
        if data <> invalid and data.Items.Count() = 2
            ' remove finished video node
            m.global.sceneManager.callFunc("popScene")
            ' setup new video node
            nextVideo = CreateVideoPlayerGroup(data.Items[1].Id)
```

Maybe Items[0].Id is what needs to be marked as watched?  You'd have to stop through and investigate.

2022-07-09 13:32 UTC, cewert commented on source/VideoPlayer.brs
> +    MarkItemWatched(showID)
```suggestion
    MarkItemWatched(videoID)
```
The video that was just watched is a fucntion parameter `sub autoPlayNextEpisode(videoID as string, showID as string)`

2022-07-09 13:35 UTC, cewert commented on source/VideoPlayer.brs
> +    MarkItemWatched(showID)
@jimdogx is right about `Items[0].Id` - that is the video ID. But if the api query fails then `Items[0].Id` will be invalid. Use videoID instead

2022-07-09 13:47 UTC, cewert commented on source/VideoPlayer.brs
> +                m.global.sceneManager.callFunc("pushScene", group)
The home rows not refreshing is a known bug #624 Let's keep this PR focused on "marking episodes as watched" and tackle the refresh bug in another PR

2022-07-09 13:58 UTC, cewert commented
> Added the MarkItemWatched() to the autoPlayNextEpisode function
This marks the episode in the episode list marked as played

> Should fix https://github.com/jellyfin/jellyfin-roku/issues/616

To be clear, this PR will not fix #616 because that feature hasn't been implemented yet (refreshing the episode list screen)

2022-09-03 08:06 UTC, neilsb commented
Can I just check what problem this is solving?   In the current store client, when I autoplay a series (server 10.8.4) as each episode is completed it is marked as played on the server.   The client reports the playback progress to the server while playing, and when the episode get within a certain %ag of the end, the item is marked as played.

So for me it is working as expected without this PR.  Can anyone reproduce the error of a series being autoplayed and the items not being marked as played on the server using the store version?

2022-09-04 08:18 UTC, alanazar commented
> Can I just check what problem this is solving? In the current store client, when I autoplay a series (server 10.8.4) as each episode is completed it is marked as played on the server. The client reports the playback progress to the server while playing, and when the episode get within a certain %ag of the end, the item is marked as played.
> 
> So for me it is working as expected without this PR. Can anyone reproduce the error of a series being autoplayed and the items not being marked as played on the server using the store version?

I wasn't able to replicate this problem either:
Jellyfin server 10.8.4 on Windows
Played the 1st episode of a tv show till the end, then it loaded the 2nd episode
Played the 4th episode till the end, then it loaded the 5th episode

Both 1st and 4th episode are marked as watched
and 2+3 are unwatched (mentioning this because Jimi said it marked all as watched)
the marked watch is only showing on the web client of the server.... the Roku app doesn't seem to show which episodes were watched

2022-09-05 00:59 UTC, closed without merging

2022-09-05 01:00 UTC, candry7731 commented
Seems like this is working, without this.