Update Boxset options
jellyfin-archive/jellyfin-roku-legacy pull request #663
Opened 2022-06-17 02:05 UTC by candry7731

Fixes Boxset menu options. Boxsets currently showed the default options as the b in Boxsets needed to be capitalized...

**Changes**
Change getCollectionType() = "Boxset"

2022-06-18 01:31 UTC, jimdogx requested changes

2022-06-18 01:31 UTC, jimdogx commented on components/ItemGrid/ItemGrid.brs
> +    return m.top.parentItem.Type
Why this change?  It breaks options for Movies, TVShows and everything else as far as I can tell.

2022-06-18 02:29 UTC, candry7731 commented on components/ItemGrid/ItemGrid.brs
> +    return m.top.parentItem.Type
Fixed this, when clicking into a boxset "folder" there is no Collectiontype param so we need to get the item type instead so the boxset options will show. 

I should have checked everything else after the change....

2022-06-18 13:40 UTC, jimdogx requested changes

2022-06-18 13:40 UTC, jimdogx commented on components/ItemGrid/ItemGrid.brs
> +    if m.top.parentItem.Type = "Boxset"
```suggestion
    if m.top.parentItem.collectionType = invalid or m.top.parentItem.Type = "Boxset"
```
I know books are going away soon, but right now it crashes when selecting books.  Best to be extra defensive incase in the future something else comes through here with "invalid".  If you commit this suggestion I think we'll be good to go.

2022-06-19 15:44 UTC, jimdogx approved these changes

2022-06-19 15:44 UTC, merged