Jf video stats
jellyfin-archive/jellyfin-roku-legacy pull request #781
Opened 2022-09-06 04:47 UTC by jimdogx

Currently you can hit "down" for subtitles during playback.  This PR adds "streaming information" if the user presses "up" during playback:

![Screen Shot 2022-09-05 at 10 39 21 PM](https://user-images.githubusercontent.com/18198517/188548786-7819395f-1d9b-4446-b58c-4874005d2c88.png)

**Changes**
Listens for "up" press during playback and shows any streaming / transcoding information available.

**Issues**
This is currently using the "built in" options dialog even though these are not options.  The presentation does have a side benefit of highlighting individual pieces of information as the users scrolls through the list.  A custom view can be created at a later dated if deemed necessary.

2022-09-06 06:41 UTC, neilsb commented on locale/en_US/translations.ts
> +            <translation>Level</translation>
Think it would be useful to add a Description tag here, just to clarify to the translator this is for the label for the video profile level.  Just aware "Level" can have multiple meaning in English that I suspect may translate differently based on context/meaning.

2022-09-06 11:57 UTC, jimdogx commented on locale/en_US/translations.ts
> +            <translation>Level</translation>
👍

2022-09-06 17:38 UTC, alanazar commented on locale/en_US/translations.ts
> +            <translation>Transcoding information</translation>
Keeping capitalization consistent with the rest
```suggestion
            <source>Transcoding Information</source>
            <translation>Transcoding Information</translation>
```

2022-09-06 17:39 UTC, alanazar commented on locale/en_US/translations.ts
> +            <translation></translation>
```suggestion
            <source>Audio Channels</source>
            <translation>Audio Channels</translation>
```

2022-09-06 17:41 UTC, alanazar commented on source/VideoPlayer.brs
> +            sessionStats.push("** " + tr("Transcoding information") + " **")
```suggestion
            sessionStats.push("** " + tr("Transcoding Information") + " **")
```

2022-09-06 17:47 UTC, alanazar commented on source/VideoPlayer.brs
> +        return Str(bitrate / 1000) + " kbps"
keeping consistent with above Mbps
```suggestion
        return Str(bitrate / 1000) + " Kbps"
```

2022-09-06 18:12 UTC, alanazar commented on source/VideoPlayer.brs
> +        return Str(bitrate / 1000000) + " Mbps"
can this be done with 2 decimal places for both Mbps and none for Kbps?

2022-09-06 18:23 UTC, alanazar commented
I've tested it and it works. Great idea for stats!

2022-09-06 18:28 UTC, alanazar commented on source/VideoPlayer.brs
> +        return Str(bitrate / 1000) + " kbps"
```suggestion
    if bitrate > 1000000
        return Str(round(bitrate / 1000000),2) + " Mbps"
    else
        return Str(round(bitrate / 1000)) + " Kbps"
```

2022-09-06 18:34 UTC, alanazar commented
The number values after "Total Bitrate: " and "Audio Codec: " have extra spaces
Answer from 1hitsong "Roku does odd auto-aligning when dealing with numbers. Likely needs to have a left align put on the value fields."
I don't know how to do that :D

2022-09-06 21:29 UTC, jimdogx commented on source/VideoPlayer.brs
> +        return Str(bitrate / 1000) + " kbps"
I don't think Roku has "round"... at least it didn't when I tested your suggestion.  I've updated it to "Fix" instead.

2022-09-07 04:24 UTC, alanazar commented on source/VideoPlayer.brs
> +        return Str(bitrate / 1000) + " kbps"
Alright thanks, didn't know that

2022-09-07 04:30 UTC, alanazar approved these changes
Tested it again and looks good
Worth revisiting later to find a way to not have Mbps or Kbps as an integer (I'll happily research this later)
Also, the left alignment of number values if that's possible.
It's a great feature to add, thanks for this!

2022-09-07 06:43 UTC, neilsb commented
Looks good - only one issue I found (purely by chance) is that if you have the Video Stats dialog open, and the Skip Intro button appears then the Stats Dialog loses focus, and you can't get it back.   

The video stats is now stuck on the screen until you exit the app with the home button (can't even exit app by pressing back).

2022-09-07 06:46 UTC, alanazar commented
> Looks good - only one issue I found (purely by chance) is that if you have the Video Stats dialog open, and the Skip Intro button appears then the Stats Dialog loses focus, and you can't get it back.
> 
> The video stats is now stuck on the screen until you exit the app with the home button (can't even exit app by pressing back).

Oh good catch! I'll keep it in mind for future testing as well

2022-09-07 12:11 UTC, jimdogx commented
> Looks good - only one issue I found (purely by chance) is that if you have the Video Stats dialog open, and the Skip Intro button appears then the Stats Dialog loses focus, and you can't get it back.
> 
> The video stats is now stuck on the screen until you exit the app with the home button (can't even exit app by pressing back).

Nice catch.  I don't have that plugin installed, but will try to install it soon and re-test 👍

2022-09-07 12:15 UTC, 1hitsong commented
To piggyback off Neil, if the Skip Into button is already shown when you press up, everything works nicely until the Skip Intro button fades out. That fade out sets the focus back to the video, not the popup. Then it's stuck on screen.

2022-09-20 00:40 UTC, 1hitsong commented
FYI, Intro Skipper plugin support has been removed. With that out of the way, were there any other lingering issues?

2022-09-20 02:21 UTC, jimdogx commented
I don't think so, but I'd wait until @neilsb chimes in to be sure 👍

2022-09-20 05:58 UTC, neilsb commented
Nope, was all good as I recall. Just would want to test it with the rolled back PR but if someone has given it the one over since then then that's cool. I can have a look at it later on today.

2022-09-20 19:24 UTC, alanazar commented
Last update broke the functionality.
On some videos i get a window.
On others nothing happens but then no other button works (back, play, forward, etc). I need to exit to Roku's home to then be able to access the server.

Is the bitrate what the video is reporting and not the live network traffic? If so, I suggest to revert the changes since it was working before and the missing stats were just codec dependent

2022-09-21 05:57 UTC, jimdogx commented
BitRate turned out to be an Integer, even though I could have sworn I looked at the server code and it said it was a String.  I've updated and pushed a fix (and was able to actually test it this time instead of pushing blindly) 😄

2022-09-21 11:42 UTC, jimdogx commented
Converting PR to a draft so I can add more data to be shown....

2022-09-21 12:09 UTC, jimdogx commented
I've added more info, I think this should be good enough for the first release of this feature:

![Screen Shot 2022-09-21 at 6 06 03 AM](https://user-images.githubusercontent.com/18198517/191499908-e391b68d-0310-4c1a-98f7-95b591f12fa5.png)

If the user scrolls:
![Screen Shot 2022-09-21 at 6 06 11 AM](https://user-images.githubusercontent.com/18198517/191499970-b47c589f-2354-4008-b3ef-85ff7c8b50a2.png)

2022-09-22 03:59 UTC, alanazar approved these changes
Tested and it works great :)
(Again, really like having this feature, thanks!)

2022-09-22 08:13 UTC, neilsb reviewed
Looks good, and works well.

Not sure if this is an issue or how it should work, but if you have the stream details up when the video ends, the next action (e.g. return to the details screen, autoplay next episode, etc) will not happen until the popup is closed.  I am not sure what the expected behaviour would be for a normal user.

2022-09-22 11:37 UTC, jimdogx commented
> Looks good, and works well.
> 
> Not sure if this is an issue or how it should work, but if you have the stream details up when the video ends, the next action (e.g. return to the details screen, autoplay next episode, etc) will not happen until the popup is closed. I am not sure what the expected behaviour would be for a normal user.

I think this is acceptable.  You can't move on until you close the popup.  Otherwise, we'd have to implement some special logic for the popup to "refresh" with the next video playing etc.

2022-09-22 12:46 UTC, 1hitsong requested changes

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if meta.live = false and get_user_setting("playback.tryDirect.h264ProfileLevel") = "true" and m.playbackInfo.MediaSources[0].TranscodingUrl <> invalid and forceTranscoding = false and m.playbackI
We need to break this line up. It's way too long.

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +        if m.playbackInfo.mediaSources[0].MediaStreams <> invalid and m.playbackInfo.mediaSources[0].MediaStreams.Count() > 0
There are 5 conditions in these 2 lines. I suggest we move the checks to a function to help readability/maintainability.

It'll also help if in the future we need to add new conditions.

Scratch code example:
![image](https://user-images.githubusercontent.com/3330318/191748818-88cc5a03-6768-406a-90ba-70bc4725d23a.png)

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.Container <> invalid
```suggestion
            if isValid(stream.Container)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.Size <> invalid
```suggestion
            if isValid(stream.Size)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.BitRate <> invalid
```suggestion
            if isValid(stream.BitRate)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.Codec <> invalid
```suggestion
            if isValid(stream.Codec)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.CodecTag <> invalid
```suggestion
            if isValid(stream.CodecTag)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.VideoRangeType <> invalid
```suggestion
            if isValid(stream.VideoRangeType)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.PixelFormat <> invalid
```suggestion
            if isValid(stream.PixelFormat)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.Width <> invalid and stream.Height <> invalid
```suggestion
            if isValid(stream.Width) and isValid(stream.Height)
```

2022-09-22 12:46 UTC, 1hitsong commented on source/VideoPlayer.brs
> +            if stream.Level <> invalid
```suggestion
            if isValid(stream.Level)
```

2022-09-22 17:46 UTC, jimdogx commented on source/VideoPlayer.brs
> +    if meta.live = false and get_user_setting("playback.tryDirect.h264ProfileLevel") = "true" and m.playbackInfo.MediaSources[0].TranscodingUrl <> invalid and forceTranscoding = false and m.playbackI
That's not part of this PR 😄

2022-09-22 18:26 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if meta.live = false and get_user_setting("playback.tryDirect.h264ProfileLevel") = "true" and m.playbackInfo.MediaSources[0].TranscodingUrl <> invalid and forceTranscoding = false and m.playbackI
Oh, sorry. Github had it highlighted as a change.

2022-09-22 20:01 UTC, jimdogx commented on source/VideoPlayer.brs
> +    if meta.live = false and get_user_setting("playback.tryDirect.h264ProfileLevel") = "true" and m.playbackInfo.MediaSources[0].TranscodingUrl <> invalid and forceTranscoding = false and m.playbackI
Nope, I did change something... when I was looking via VSCode it's just an existing line from a previous feature (I think Neil added)... but I did make "playbackInfo" a member variable. So I did change it, but I'll leave the cleanup for next time we need to much with this transcoding code stuff.

2022-09-22 21:04 UTC, 1hitsong approved these changes

2022-09-22 21:04 UTC, 1hitsong commented
To be merged 9/23 unless an issue arises.

2022-09-23 06:25 UTC, neilsb approved these changes

2022-09-23 12:20 UTC, merged