Add "Next Episode" button in the last 30 seconds of an episode
jellyfin-archive/jellyfin-roku-legacy pull request #784
Opened 2022-09-07 04:09 UTC by candry7731

Adds "Next Episode" Button in the last 30 seconds of an episode. If use click the OK button on the remote the next episode will load.

**Features for next PR**
Add user custom setting to set time to show button
Add user custom setting to disable button
Add ability to prebuffer next episode to speed up load time

2022-09-07 11:59 UTC, 1hitsong requested changes

2022-09-07 11:59 UTC, 1hitsong commented on source/VideoPlayer.brs
> +        'print (meta.json.RunTimeTicks / 10000000) / 60
Debug code

2022-09-07 11:59 UTC, 1hitsong commented on components/JFVideo.brs
> +        shownextEpisode()
I'm not a fan of having nextEpisode code in the HaveSkipIntroParams(). Separation of concerns says SkipIntroParams has nothing to do with showing the Next Episode. I'd move it into its own thing.

2022-09-27 05:10 UTC, candry7731 commented on components/JFVideo.brs
> +        shownextEpisode()
I moved this out of the skip intro sub()

2022-11-02 11:58 UTC, 1hitsong commented
@candry7731 If you can resolve the validate issue, I'll retest.

2022-11-02 12:03 UTC, candry7731 commented
Ill fix tonight

2022-11-05 19:08 UTC, 1hitsong commented
I think the  `<JFButton id="nextEpisode"` component in the JFVideo.xml was accidentually removed. Clicking on any episode throws an error at `m.nextEpisodeButton = m.top.findNode("nextEpisode")` because the node isn't found.

2022-11-07 04:37 UTC, candry7731 commented
> I think the `<JFButton id="nextEpisode"` component in the JFVideo.xml was accidentually removed. Clicking on any episode throws an error at `m.nextEpisodeButton = m.top.findNode("nextEpisode")` because the node isn't found.

This is fixed.

2022-11-09 21:57 UTC, 1hitsong commented
Button now appears!

At the end of an episode, once the button appeared, I went back on the trickplay bar to 2 minutes before the end and pressed OK expecting it to rewind, but instead it triggered the Next button.

2022-11-09 21:58 UTC, 1hitsong commented
The last second of the episode before it changes shows the Next Episode button with a negative value.

![image](https://user-images.githubusercontent.com/3330318/200950622-6771a15c-5160-4fb7-af98-121f9fc28faf.png)

2022-11-09 22:00 UTC, 1hitsong commented
I rewound the video to the middle, but the Next Episode button stayed as it was at the last second. It should instead hide the button as it no longer applies this far back in the video.

![image](https://user-images.githubusercontent.com/3330318/200951146-768a38de-eebc-4ec5-8ca6-84dc8ecc0956.png)

2022-11-11 04:56 UTC, candry7731 commented
> The last second of the episode before it changes shows the Next Episode button with a negative value.
> 
> ![image](https://user-images.githubusercontent.com/3330318/200950698-59032564-aa92-4594-a2aa-9c160833e767.png)

I could not reproduce this issue. all of my episodes stopped at 0

2022-11-11 04:57 UTC, candry7731 commented
> I rewound the video to the middle, but the Next Episode button stayed as it was at the last second. It should instead hide the button as it no longer applies this far back in the video.
> 
> ![image](https://user-images.githubusercontent.com/3330318/200951146-768a38de-eebc-4ec5-8ca6-84dc8ecc0956.png)

This has been fixed. the button will now hide and restore focus to the video screen.

2022-11-11 16:49 UTC, 1hitsong commented
Tried a different episode. It also has the -1 bug. I suppose add code so once it reaches 0 it doesn't countdown any further.

![image](https://user-images.githubusercontent.com/3330318/201389281-34a5f4b3-0b33-45ec-9314-682083931f7c.png)

2022-11-11 16:49 UTC, 1hitsong commented
This issue still exists: At the end of an episode, once the button appeared, I went back on the trickplay bar to 2 minutes before the end and pressed OK expecting it to rewind, but instead it triggered the Next button.

2022-11-11 16:59 UTC, candry7731 commented
what buttons did you use? the back arrow or the rewind button.

On Fri, Nov 11, 2022 at 10:49 AM 1hitsong ***@***.***> wrote:

> This issue still exists: At the end of an episode, once the button
> appeared, I went back on the trickplay bar to 2 minutes before the end and
> pressed OK expecting it to rewind, but instead it triggered the Next button.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/784#issuecomment-1311939126>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRFDYCA62HRDO7S3H2TWHZ2JRANCNFSM6AAAAAAQGMF4LI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>


-- 
Chris Andry

462 Browning Loop
Mandeville LA 70448
504-617-2924

2022-11-11 17:09 UTC, 1hitsong commented
1. Button shows at end of episode
2. Press LEFT on remote
3. Trickplay bar appears, continue pressing left until 2 minutes back
4. Press OK on remote

My expectation is since I'm manipulating the trickplay bar, pressing OK would send the video back to that point.

2022-11-11 20:39 UTC, candry7731 commented
Weird, I tested that exactly last night and had no issues with rewinding from the trickplay bar and pressing ok to restart the view..

I have the video set to focus if not within 30 seconds.... maybe need to add trickplay.focus to false also?
`sub handleNextEpisode()
    if int(m.top.position) >= (m.top.runTime - 30)
        shownextEpisode()
        updateCount()
    else
        m.nextEpisodeButton.visible = false
        m.nextEpisodeButton.setFocus(false)
        m.top.setFocus(true)
    end if`

2022-11-13 04:56 UTC, candry7731 commented
Added so more logic to the "ok" button press. Basically if the video is not playing the next up button is hidden and focus is returned to the video player

2022-11-13 10:40 UTC, alanazar commented
Transcoding info (Up button) and subtitles (Down button) get stuck if you try pressing it during the 30sec countdown.
I even tested it at the start and it also gets stuck.
Only way to resolve it is to exit back to Roku then back in again

2022-11-18 02:31 UTC, 1hitsong approved these changes

2022-11-21 01:19 UTC, 1hitsong commented
If there is no next episode (example: Last episode of last season) then don't show the button.

2022-11-21 01:20 UTC, 1hitsong requested changes
If there is no next episode (example: Last episode of last season) then don't show the button.

2022-11-21 21:50 UTC, 1hitsong approved these changes

2022-11-22 00:34 UTC, 1hitsong commented
To be merged 11/22 unless an issue arises.

2022-11-22 13:53 UTC, merged