Fix Episode titles when search
jellyfin-archive/jellyfin-roku-legacy pull request #792
Opened 2022-09-15 04:05 UTC by candry7731

Hide Episode titles when a new search is processed

Fixes 1 issue out of 3 for issue #779, Fixed TV Series Name incorrectly displayed when a new search is conducted.

2022-09-25 10:00 UTC, neilsb requested changes

2022-09-25 10:00 UTC, neilsb commented on source/VideoPlayer.brs
> -        return option_dialog(["Resume playing at " + ticksToHuman(time) + ".", "Start over from the beginning."])
This function need to return a value, which it won't do now if it doesn't go into this `if`, so think the correct logic is to revert this change and leave it as it was.

The reason the back command on the Resume dialog is that if the user hits back then playback is cancelled and `invalid` is eventually returned from the call to `CreateVideoPlayer()` in `main.brs` line 269.  This `invalid` is then being passed to `PushScene()` which is failing.

Simplest thing to do is probably to add a check in the `PushScene()` function to ensure that the argument is not invalid, and if it is then just return immediately.  May need to check focus isn't lost on the search result screen then this happens.

2022-09-25 10:00 UTC, neilsb commented on source/Main.brs
> +            m.type = selectedItem.type
Since this variable is added to hold the Selected Item Type, and since `type` is a very generic name, can we rename this variable  `m.selectedItemType` just to ensure that someone else doesn't see the variable `m.type` and assume it's something else?

2022-09-25 10:00 UTC, neilsb commented on components/data/SceneManager.brs
> +    m.groups.Delete(2)
Why is this change needed?

2022-09-27 04:05 UTC, candry7731 commented on components/data/SceneManager.brs
> +    m.groups.Delete(2)
This clears the last video node. If not then everytime the video node refreshes the live tv stream it adds to the stack.... cause you to click back multiple times to get back to the guide.

2022-10-11 06:30 UTC, neilsb approved these changes

2022-10-12 00:10 UTC, merged

2022-10-21 16:02 UTC, 1hitsong commented on components/data/SceneManager.brs
> +    m.groups.Delete(2)
This change broke Intro Video support. Can you create a new sub for the Delete(2) call and leave the Pop() as is?