UI changes to Movie Details, Extras Slider, and Options menu.
jellyfin-archive/jellyfin-roku-legacy pull request #798
Opened 2022-09-18 00:19 UTC by Any-Fuel-5635

Cleaned up the movie details screen, movie options menu, used a bold font on the movie description and cleaned up the extras slider. On the Movie Details screen, I re-positioned the buttons to be vertical to keep with the vertical interaction present in the rest of the application in various other places. The goal is to make entire screen is less busy and more straightforward, and as a result, it will also naturally draw the user's eye to the extras slider below as they navigate downward. 

Movie Details - Buttons are vertical now, play button is larger with a stylized Jellyfin logo to serve as the play icon. Added a gradient transparent image that is scalable and uses the brand color stated on Jellyfin's branding page.

2022-09-18 01:05 UTC, 1hitsong commented
Navigating around the Movie Detail page threw several warnings in console.

![image](https://user-images.githubusercontent.com/3330318/190881200-b9a478c0-a377-4f7a-80fd-b7f5b7240062.png)

2022-09-18 01:20 UTC, 1hitsong requested changes
Other than the comments, the changes seem fine, but they are minor - like you said. 

Bigger picture, I think it's time for us to come up with real design mockups for all the screens so we can have a unified and cohesive design throughout the application.

2022-09-18 01:20 UTC, 1hitsong commented on components/movies/MovieDetails.xml
> +          <Button text="Play" id="play-button" iconUri="pkg:/images/play_button_jf_white_18dp.png" focusedIconUri="pkg:/images/play_button_jf_white_18dp.png" blendColor="#a4dcFF" maxWidth="300" minWi
This line causes warnings in console.

2022-09-18 01:20 UTC, 1hitsong commented on components/movies/MovieDetails.xml
> +          <Button id="trailer-button" visible="false" iconUri="" focusedIconUri="" maxWidth="350" minWidth="350" />
2 issues with the trailer button.

1.  The bottom of the letters touch the background of the Extras section.
2. I can't navigate to the Play Trailer button. Pressing down from Set Favorite causes the extra section to slide up.

2022-09-18 01:20 UTC, 1hitsong commented on components/movies/MovieDetails.xml
> +        <!--  <Label id="tagline" /> -->
Tagline shouldn't be commented out.

2022-09-18 01:48 UTC, Any-Fuel-5635 commented on components/movies/MovieDetails.xml
> +          <Button id="trailer-button" visible="false" iconUri="" focusedIconUri="" maxWidth="350" minWidth="350" />
Fixed colorBlend oddity. Looking at positioning of the extras screen next. Do we want Extras window to be more visible with maybe a 10 gap fro the bottom? If so, easy fix. 

The play trailer button has never worked based on previous code and visibility was previously marked as false, I just re-positioned it to the bottom since it was unused... but I still referenced it in the event that it was added in the future. 

The down function to bring the extra slider was present before, it is just more noticeable now since it is a vertical menu.

2022-09-18 03:26 UTC, Any-Fuel-5635 commented on components/movies/MovieDetails.xml
> +        <!--  <Label id="tagline" /> -->
Personally, I looked over a bunch of them throughout my collection and 95% of them were, IMHO, a bit cringe. Plex doesn't use them, either. I just commented it out, but this was a personal choice. It was only clutter in my opinion.

2022-09-18 13:58 UTC, 1hitsong commented on components/movies/MovieDetails.xml
> +        <!--  <Label id="tagline" /> -->
We have a user settings on Roku that allows people to hide it if they choose to.

2022-09-18 14:48 UTC, Any-Fuel-5635 commented on components/movies/MovieDetails.xml
> +        <!--  <Label id="tagline" /> -->
I am aware that we do, but this is just a proof of concept for a different design setup that will continue to evolve. I am proposing that we discuss removing it entirely, though, as it rarely contributes anything to the page/summary and just takes up space and other apps in the user-space do not include these. Thank you again for your time and review!

2022-09-18 16:01 UTC, Any-Fuel-5635 commented on components/movies/MovieDetails.xml
> +        <!--  <Label id="tagline" /> -->
I brought back taglines, as requested. Given the nature of that that trailer button is just kind of hidden, I had to adjust the flow of the movie details screen. I am well aware that my changes to the slider are global and make the slider invisible on TV shows, however, it is just a proof of concept. This could easily be added/adjusted elsewhere, and my next commit will likely add just that. To be honest, when I first started using the Jellyfin app, I did not even notice the cast and crew slider at the bottom. It was pretty hidden and I felt bad for whoever made it that I didn't see it sooner. It is really well made. This will ensure that the average user can see this hard work and view the cast with an easily visible button.

2022-09-18 16:29 UTC, neilsb commented
When there are local trailers for the item and the "Play Trailer" button is shown, it's right at the bottom of the screen.

We should be trying to respect [Roku's advice on Safe Zones](https://developer.roku.com/en-gb/docs/specs/graphics.md#action-safe-zone) just to prevent any issues with Overscanning.  (There's an issue open currently to do with not being able to see the whole screen - #796) 

![image](https://user-images.githubusercontent.com/5013482/190917494-7100c86d-a313-42d5-a44b-3aaa052ca83e.png)

2022-09-18 16:33 UTC, 1hitsong commented
Perhaps we can work in the section navigation work I've been working on for music playback.

Essentially, each navigation section is represented in a small navigation section on the left hand side. You can still navigate through content section by pressing up and down a million times through the sections, or you can go left to the section navigation menu to see all available sections and go straight there.

2022-09-18 21:23 UTC, Any-Fuel-5635 commented
I adjusted the size of the buttons to accommodate the safe zones. 

Also, is there a way to keep the invisible (for me, I don't have trailers on my server) trailer button from not being able to be navigated to when it is invisible? 

I have an else statement in place on the .brs for when it is present, but from a user-standpoint, even on the unstable branch which is horizontal, you could still "navigate" to it on the far right even though it was neither visible nor functional. The same can be seen on this PR when navigating all the way to the bottom if the button is not present, its highlighting that invisible (for me) trailer button. When I force it to be visible for testing, it works as intended, but I do not have trailers and I know other users who do not either. I am sure it is a simple fix I am just not aware of, but I can include it if I can get a bit more info on how that is accomplished. Thank you!

2022-09-20 04:28 UTC, Any-Fuel-5635 commented
Made some tweaks to the ItemGrid for Movies to have a blurred background of the movie poster. It is less distracting based on reviews from multiple non-biased users  and the "blur" is enough to be pleasing to the eye, but not weak enough to pull visual focus from the poster to the background. As an experiment, changed movie, options menu behavior to shift with directional keys from user input. The flow seems to be a bit cleaner and less visually jarring. When navigating far to the right, the result, especially on the Extras slider, is quite clean. I am still working on button behavior when entering/exiting the extras slider, as the performance is not consistent. Will update this in a later commit. Thank you.

2022-09-20 19:44 UTC, alanazar commented
I appreciate the effort that went into this and I hope you take this constructively
I prefer the older UI\UX, it was actually neater and simpler
Also, the older UI had the Cast & Crew kind of visible, so you knew you could scroll down further and then Up when done. Only 2 buttons were needed, Up or Down.
In this one you have to go down to cast, click ok, scroll down, then back to go to the movie details. Personally didn't like it.

Since this is a massive change even from what the other players show I think it would be best to instead focus on smaller design changes that would make these look better without overhauling the page.

2022-09-20 21:24 UTC, Any-Fuel-5635 commented
It's no problem at ALL! I just wanted to throw some ideas out to experiment with since I have a user base that is not overly technical available to try things out. The changes I made are based around things that those people found to be more challenging/difficult to navigate and requests that they made. Given the fact the a portion of the userbase for this particular app will likely not be server hosts, I was just trying to see what we could do to clean things up for them to make it easier to use. 

Some changes that I personally liked had to do with the blur on the background of the movie details page, as many stated that if the image didn't match the movie it was somewhat confusing and the constantly changing image, while "cool" to be a bit distracting.

The floatingFocus navigation versus the fixedFocus(+/- wrap) I also thought made things more intuitive. It was a bit less movement on the screen and a child was able to more easily navigate the menus especially because of the ability to follow the cursor (best I could gather from what they said). 

The bold font for the movie descriptions were easier to read for my older users who stated the normal font size was a bit more challenging to view at a distance. I found that interesting. 

The Cast and Crew button was a result of most of the users not seeing nor noticing the tab down below. I thought the tab was pretty cool, personally, as well. For some user's devices, it did not render in the safe zone (I'm assuming), and after reading more about safe zones that Neilsb pointed out, this makes sense.

A proposed change I would personally suggest is if we could make the entire screen move up and down versus a slider covering the previous screen, similar to how HBOMAX navigates. That is a very well designed app and we could take some good notes from them (aside from the inherent lagginess it shares with Disney+). They also have an interesting way of doing icons for playing content, etc. that is an icon until it is highlighted, then it changes to the icon and word. With typescript translations, we could maybe set a wider max width and have those longer translations fit more easily. 

Anyway, those were the reasons for the changes, and I didn't expect a full pull, but maybe we could, no pun intended, pull from some of these suggestions/implementations if we ever redesign the UI. We are unfortunately more limited by the Roku scripting confines, but parity with the Jellyfin Desktop App would be really neat in the future.

2022-09-21 06:11 UTC, alanazar commented
These make a lot more sense now and I'll know what to look out for :)
I won't be able to properly test for a while, but may I suggest in the meantime, updating the opening comment as a task-list so that it'll be easier to know what we're testing and leave comments per point.
For the older users \ accessibility I think this is a wonderful idea, and maybe instead of changing the whole layout we can keep it as an option that users can select which layout they want to use.
Give me some time to get back to you on more testing and maybe we can discuss these on Matrix

2022-09-22 04:27 UTC, alanazar commented
Examples of task list to keep better track.
I just put in what you wrote, but you can edit it in your original comment and we can go from there

- [ ] Background blur of movie details page when the image does not match the movie
Description: If the image didn't match the movie it was somewhat confusing and the constantly changing image, while "cool" to be a bit distracting.

- [ ] floatingFocus navigation versus the fixedFocus(+/- wrap)
Description: It was a bit less movement on the screen and a child was able to more easily navigate the menus especially because of the ability to follow the cursor (best I could gather from what they said).

- [ ] Bold font for movie description
Description: Easier to read for my older users who stated the normal font size was a bit more challenging to view at a distance. I found that interesting.

- [ ] Cast & Crew button vs scroll down
Description: Was a result of most of the users not seeing nor noticing the tab down below. I thought the tab was pretty cool, personally, as well. For some user's devices, it did not render in the safe zone (I'm assuming), and after reading more about safe zones that Neilsb pointed out, this makes sense.

2022-09-22 07:15 UTC, neilsb commented
> Also, is there a way to keep the invisible (for me, I don't have trailers on my server) trailer button from not being able to be navigated to when it is invisible?

Easiest thing to do it just to create a "trailers" folder under one movie for testing, and copy any video file in there.  That will show the button on that movie.

2022-09-22 07:33 UTC, neilsb commented on components/data/MovieData.brs
> +            m.top.backdropURL = ImageURL(m.top.json.id, "Primary", imgParams)
I understand what you're saying about the background image in the item grid, but I think it would be better to have a new property (maybe `blurBackdropUrl` or something), then set the itemGrid to use this.  

If the `MovieData` is used elsewhere in the code and then the developer will likely be expecting the full backdrop at this URL rather than the blur.  (e.g.  If it were to be used in the Movie Details screen for example)

2022-09-23 02:09 UTC, Any-Fuel-5635 commented
> > Also, is there a way to keep the invisible (for me, I don't have trailers on my server) trailer button from not being able to be navigated to when it is invisible?
> 
> Easiest thing to do it just to create a "trailers" folder under one movie for testing, and copy any video file in there. That will show the button on that movie.

Yes sir, and thank you for the clarification. What I am referring to, however, is making the "trailer" button non-functional/non-focusable in the event that a user does not have a trailer available.  I can toggle the visibility by simply tweaking the XML. On unstable, for example, in the absence of a trailer, there is instead an invisible button to the far right (where the trailer button is hiding, although not visible). The cursor will disappear, highlighting the trailer button (audio cue confirms this) until "left" is pressed again to return to the main menu and the cursor returns. 

This is the same on my example with the vertical menu layout. This was another reason that I had to explore alternatives to the Cast and Crew slider function screen as this button kept catching cursor on the way down and it was confusing to some of my users. They essentially had to hit down twice to skip past the (invisible) trailer button.

2022-09-23 02:09 UTC, Any-Fuel-5635 commented on components/data/MovieData.brs
> +            m.top.backdropURL = ImageURL(m.top.json.id, "Primary", imgParams)
I'll see what I can come up with. Thank you for the input, and what you said makes perfect sense.

2022-09-23 02:11 UTC, Any-Fuel-5635 commented
> Examples of task list to keep better track. I just added in what you wrote, but you can make further changes, add it in your original comment and we can go from there
> 
>     * [ ]  **Background blur of movie details page when the image does not match the movie**
>       If the image didn't match the movie it was somewhat confusing and the constantly changing image, while "cool" to be a bit distracting.
> 
>     * [ ]  **floatingFocus navigation versus the fixedFocus(+/- wrap)**
>       It was a bit less movement on the screen and a child was able to more easily navigate the menus especially because of the ability to follow the cursor (best I could gather from what they said).
> 
>     * [ ]  **Bold font for movie description**
>       Easier to read for my older users who stated the normal font size was a bit more challenging to view at a distance. I found that interesting.
> 
>     * [ ]  **Cast & Crew button vs scroll down**
>       Was a result of most of the users not seeing nor noticing the tab down below. I thought the tab was pretty cool, personally, as well. For some user's devices, it did not render in the safe zone (I'm assuming), and after reading more about safe zones that Neilsb pointed out, this makes sense.
> 
>     * [ ]  **Movie Details**
>       Buttons are vertical now, play button is larger with a stylized Jellyfin logo to serve as the play icon. Added a gradient transparent image that is scalable and uses the brand color stated on Jellyfin's branding page.

Thank you, I just quickly renamed the PR last night to mitigate confusion until I could come back and clarify things. I may flip this back to a draft to keep it off of your feed until things are cleaned up. As always, I appreciate your time and feedback.

2022-10-30 02:13 UTC, closed without merging