remove server circumvention
jellyfin-archive/jellyfin-roku-legacy pull request #810
Opened 2022-09-28 18:33 UTC by whiteowl3

We no longer bypass jf server when requesting external strms because the core team insisted.
In my opinion these changes ruin the playback of external resources when jf server is on an rpi4, but i don't disagree with the team's logic on why the previous functionality was bad.
we no longer use the mediasource's Path unless that path contains localhost, and in that case we replace the entire schema:localhost:port expression with that of the currently connected jf server.
This is important because otherwise ALL content served this way (from a jf-local server) looks like garbage on the rpi4, instead of only external content.
It is fine and correct to do it this way because we are still limiting our communications to the jf port, and advanced users can still use locations to configure whatever server business they want in their reverse proxy.
The use of "localhost" strm uri's is important when serving this way to allow jellyfin to scan off those local servers, but it must step out of the way when serving them to produce good results on low power hardware.

**Issues**

2022-09-29 06:50 UTC, neilsb commented
Linter errors are 

1. You're typo'd `subtitute_localhost` in line 231
2. you should be using `m.playbackInfo` instead if `playbackInfo`

That should make the linter happy

2022-09-29 06:51 UTC, neilsb commented on source/VideoPlayer.brs
> +		subtitute_localhost = false
```suggestion
	substitute_localhost = false
```

2022-09-29 06:52 UTC, neilsb commented on source/VideoPlayer.brs
> +            uri = uriRegex.Match(playbackInfo.MediaSources[0].Path)
```suggestion
            uri = uriRegex.Match(m.playbackInfo.MediaSources[0].Path)
```

2022-09-29 06:52 UTC, neilsb commented on source/VideoPlayer.brs
> +        protocol = LCase(playbackInfo.MediaSources[0].Protocol)
```suggestion
        protocol = LCase(m.playbackInfo.MediaSources[0].Protocol)
```

2022-09-29 06:52 UTC, neilsb commented on source/VideoPlayer.brs
> +        if playbackInfo.MediaSources[0].TranscodingUrl = invalid
```suggestion
        if m.playbackInfo.MediaSources[0].TranscodingUrl = invalid
```

2022-09-29 06:53 UTC, neilsb commented on source/VideoPlayer.brs
> +        video.content.url = buildURL(playbackInfo.MediaSources[0].TranscodingUrl)
```suggestion
        video.transcodeReasons = getTranscodeReasons(m.playbackInfo.MediaSources[0].TranscodingUrl)
        video.content.url = buildURL(m.playbackInfo.MediaSources[0].TranscodingUrl)
```

2022-10-09 23:48 UTC, 1hitsong requested changes

2022-10-09 23:48 UTC, 1hitsong commented on settings/settings.json
> +        "title": "Advanced",
All of these strings need to be added to the english translation file.

2022-11-08 02:11 UTC, closed without merging