Fix Cinema Mode Intro bug
jellyfin-archive/jellyfin-roku-legacy pull request #823
Opened 2022-10-21 16:10 UTC by 1hitsong

**Changes**
Fixes bug with Cinema Mode intro videos where pressing back goes back to the intro video instead of the screen before it.

2022-10-21 16:36 UTC, jimdogx approved these changes

2022-10-21 16:43 UTC, neilsb requested changes

2022-10-21 16:43 UTC, neilsb commented on components/data/SceneManager.brs
> +    m.groups.Delete(sceneLength)
The `Delete` function just removes the item at that index, rather than a range.

2022-10-21 16:57 UTC, 1hitsong commented on components/data/SceneManager.brs
> +    m.groups.Delete(sceneLength)
Updated

2022-10-21 17:11 UTC, neilsb approved these changes

2022-10-22 13:24 UTC, merged

2022-11-25 03:44 UTC, candry7731 commented
If the Live channel closes because of an error we auto reload the video player. However this change does not currently delete the previous video from the stack. so If my live channel auto opens 4 times I will have to hit the back button 4 times to get back to the guide.