Fix Filter reload Issues with Live TV
jellyfin-archive/jellyfin-roku-legacy pull request #826
Opened 2022-10-26 03:37 UTC by candry7731

Add the ability for the user to say "all" to show all channels after the guide has been filtered by a voice command.

In the channel view the reload button will clear the filter and show all channels

2022-11-05 19:33 UTC, 1hitsong requested changes
Voice search is activating Roku search for me.

2022-11-05 19:33 UTC, 1hitsong commented on components/liveTv/schedule.brs
> +    print "Key Pressed = "key
Debug Code

2022-11-05 19:33 UTC, 1hitsong commented on components/liveTv/schedule.brs
> +        print "Press Return"
Debug code

2022-12-06 00:17 UTC, 1hitsong commented
👍 Works as described.

Can we apply the same logic to both views? Add reload button logic to the TV Guide, and "All" voice filter to the Channels view?

2022-12-06 21:07 UTC, 1hitsong approved these changes

2022-12-07 03:41 UTC, jimdogx commented
A couple of things:

1. LoadItemTask2.xml (not the BRS), has a default value of "All" (uppercase).  Not sure if that matters but thought I should point it out since you are specifically looking for lowercase "all"

2. The replay button doesn't work for me.  It's not even registering on the TV Guide (I added some debug print statements and "replay" is not even showing up in onKeyEvent).  No idea why or if it's just me.

Voice filtering and resetting the filter by saying "All" does work though 👍

2022-12-07 04:07 UTC, candry7731 commented
> A couple of things:
> 
> 1. LoadItemTask2.xml (not the BRS), has a default value of "All" (uppercase).  Not sure if that matters but thought I should point it out since you are specifically looking for lowercase "all"
> 2. The replay button doesn't work for me.  It's not even registering on the TV Guide (I added some debug print statements and "replay" is not even showing up in onKeyEvent).  No idea why or if it's just me.

_the replay button is assigned by roku to take users back to the current time when in the guide view. so if you scroll to the right to advance the time in the guide and then hit the replay button it will bring you back to the current time. _
> 
> Voice filtering and resetting the filter by saying "All" does work though 👍

2022-12-07 13:48 UTC, jimdogx commented
@candry7731 I'm talking about this piece of code:

```
   if key = "replay"
        m.spinner.visible = true
        m.top.searchTerm = " "
        m.LoadChannelsTask.searchTerm = " "
        channelsearchTermSet()
        return true
    end if
```

I thought it implied that I could say "All" or that I could hit the replay button to remove the filter.  But this code is never hit.  So maybe it's not needed?  Or am I not using it correctly?

2022-12-07 13:49 UTC, jimdogx requested changes

2022-12-07 13:49 UTC, jimdogx commented on components/liveTv/schedule.brs
> +    if key = "replay"
Remove this if it doesn't do anything (see conversation).

2022-12-07 18:44 UTC, candry7731 commented on components/liveTv/schedule.brs
> +    if key = "replay"
Done, This is removed

2022-12-08 13:58 UTC, jimdogx approved these changes

2022-12-08 14:15 UTC, merged