loading spinner, Progress Dialog and movie details button animate
jellyfin-archive/jellyfin-roku-legacy pull request #827
Opened 2022-10-27 04:09 UTC by candry7731

Added loading spinner to movies detail screens

Added loading spinner to the movie details screen

Added progress dialog when user clicks the play button for movies and trailers

Updated movie details buttons to be hidden until all data is loaded

Updated critic rating star to be hidden until all data is loaded

2022-11-05 23:04 UTC, jimdogx commented
I noticed that when I hit Play Movie, I get the new "Loading Movie" spinner, that goes away and then I get the regular spinner (not text).  Not sure if that was the desired behavior?

2022-11-06 23:02 UTC, whiteowl3 commented
If the server holding the strm fails to respond, the spinner locks us out forever.  back or instant replay should cancel the loading job and clear the spinner.
Why it is so visually different from all the other spinners?

2022-11-06 23:07 UTC, whiteowl3 commented
> I noticed that when I hit Play Movie, I get the new "Loading Movie" spinner, that goes away and then I get the regular spinner (not text). Not sure if that was the desired behavior?
The first spinner is to lock out additional inputs (esp play inputs) until jellyfin responds with the stream.  if the media is remote, this can take a second.  so, the first spinner drops as soon as jellyfin says "here it is" and the second spinner waits until we have enough buffered to play.  we need both.

2022-11-28 03:35 UTC, candry7731 commented
This should be good to go unless anyone else finds any bugs.

2022-12-20 02:59 UTC, 1hitsong commented
This works as described for me. 

@jimdogx You good?

@candry7731 Can you resolve the merge conflict?

2022-12-23 17:26 UTC, jimdogx commented
This might be due to the conflicts, but if I run this branch on a movie that is partially watched (so I should see the "Resume" or "start over" popup), I am shown "Loading Movie" with a spinner that never goes away.

2023-02-01 23:00 UTC, 1hitsong commented
Status: Pending code updates.

2023-02-02 05:26 UTC, candry7731 commented
> This might be due to the conflicts, but if I run this branch on a movie that is partially watched (so I should see the "Resume" or "start over" popup), I am shown "Loading Movie" with a spinner that never goes away.

This should be fixed. Please test and let me know.

2023-02-02 20:02 UTC, sevenrats commented
it's important that we restart the progress dialog in VideoPlayer.brs after we have closed it in startPlayBackOver.

2023-02-10 23:50 UTC, 1hitsong commented
From Home View, Click TV Episode from Continue Watching
- [ ] From popup click Go To Series. Spinner shows and doesn't go away
- [ ] From popup click Go To Season. Spinner shows and doesn't go away
- [ ] From popup click Go To Episode. Spinner shows and doesn't go away

2023-02-11 03:28 UTC, candry7731 commented
I'm also getting an error when clicking on the season...  

![image](https://user-images.githubusercontent.com/83685828/218236685-1db152d8-dc41-4462-9afc-f71142b4ea54.png)

2023-02-11 03:43 UTC, candry7731 commented
I'm working on these now.... Just fyi

2023-02-11 04:00 UTC, candry7731 commented
These are completed and ready for review

2023-02-11 12:24 UTC, 1hitsong requested changes
Functionality looks good. Just a few small finishing touches and it's done.

2023-02-11 12:24 UTC, 1hitsong commented on components/movies/MovieDetails.xml
> +        <ButtonGroupHoriz id="buttons" itemSpacings="[10]" visible = "false">
```suggestion
        <ButtonGroupHoriz id="buttons" itemSpacings="[10]" visible="false">
```

2023-02-11 12:24 UTC, 1hitsong commented on components/movies/MovieDetails.xml
> +    <Spinner id="spinner" translation="[900, 450]" visible = "true" />
```suggestion
    <Spinner id="spinner" translation="[900, 450]" visible="true" />
```

2023-02-11 12:24 UTC, 1hitsong commented on source/Main.brs
> +                dialog.title = tr("Loading trailer")
"Loading trailer" needs to be added to translations

2023-02-11 18:58 UTC, candry7731 commented on source/Main.brs
> +                dialog.title = tr("Loading trailer")
Done

2023-02-11 19:27 UTC, 1hitsong approved these changes
To be merged 2/12 unless an issue arises.

2023-02-12 12:00 UTC, merged