Fast TVguide loading
jellyfin-archive/jellyfin-roku-legacy pull request #841
Opened 2022-11-07 03:42 UTC by candry7731

Loads first 10 channels in the "guide view". Once user scrolls past the 6th channel the guide will load the next 10 channels until there is nothing left to load. 

This does not change the way the LiveTV "channel view" operates 

**Changes**
Added a new function to the schedule.brs file, advanceGuide()
Set the LoadChannelsTask.xml Limit to 10

2022-12-06 18:54 UTC, candry7731 commented
let me know what you guys think of this

2022-12-31 13:05 UTC, 1hitsong commented
Focus was lost immediately after I loaded the Live TV library. My default is Guide view. If I changed to Channel View, then back to Guide, it worked.
https://user-images.githubusercontent.com/3330318/210137682-5ce93513-51ec-48dc-b7b9-ae6952709302.mp4

2022-12-31 13:08 UTC, 1hitsong commented
Let's increase the look ahead a bit so it attempts loading the new channels off screen. 

As I scroll to the bottom of the loaded data, Channel 1 will show at the bottom, then get replaced. It jumps around when it happens, so best to do that off screen.

2022-12-31 13:12 UTC, 1hitsong requested changes

2022-12-31 13:12 UTC, 1hitsong commented on components/liveTv/schedule.brs
> +    'm.scheduleGrid.jumpToChannel = 0
Remove

2022-12-31 13:12 UTC, 1hitsong commented on components/liveTv/schedule.brs
> +    'm.scheduleGrid.jumpToChannel = 0
Remove

2022-12-31 13:12 UTC, 1hitsong commented on components/liveTv/schedule.brs
> +        'm.LoadChannelsTask.channels = m.LoadChannelsTask.channels
Remove

2022-12-31 13:12 UTC, 1hitsong commented on components/liveTv/schedule.brs
> +        'm.top.currentChannelFocused = m.scheduleGrid.channelFocused
Remove

2022-12-31 13:12 UTC, 1hitsong commented on components/movies/MovieDetails.brs
> +    m.spinner = m.top.findNode("spinner")
Why are there changes to MovieDetails.brs and MovieDetails.xml?

2022-12-31 13:12 UTC, 1hitsong commented on source/Main.brs
> +                dialog.title = tr("Loading trailer")
Are any of these changes to Live TV? If not, then need to be moved out.

2023-01-04 02:25 UTC, candry7731 commented on source/Main.brs
> +                dialog.title = tr("Loading trailer")
I did not add any of this trailer-button code.... not sure where it came from

2023-01-04 02:32 UTC, candry7731 commented
> Focus was lost immediately after I loaded the Live TV library. My default is Guide view. If I changed to Channel View, then back to Guide, it worked. https://user-images.githubusercontent.com/3330318/210137682-5ce93513-51ec-48dc-b7b9-ae6952709302.mp4

Hmm, I do not get this same issue. do you have guide data? I wonder if the focus is lost because the program data is never loaded.

2023-01-26 22:05 UTC, 1hitsong commented
I clicked on Live TV, and it just spins. The guide never loads. I don't have up-to-date program data. No errors in console.

![image](https://user-images.githubusercontent.com/3330318/214961077-3b98c07b-c4a0-4ebb-a485-7ad5a5ae55d2.png)

2023-02-01 23:19 UTC, 1hitsong commented
I'm still having issues with focus being lost. It seems to happen when I load the TV in guide view, press back, then load TV again.

https://user-images.githubusercontent.com/3330318/216189512-c247de83-896f-4348-940d-f53a84339e4b.mp4

2023-02-02 02:13 UTC, candry7731 commented
I do not get this at all. I always have focus even when switching views and pressing back buttons. I'll try to post a small video it said mine is too big....

2023-02-03 01:33 UTC, 1hitsong commented
1. Scrolling up from channel 1 makes it freak out
2. If you do a voice search for something that returns no results, you get an endless waiting spinner.

2023-02-08 23:56 UTC, 1hitsong commented
- [ ] Scrolling up from channel 1 makes it freak out
- [x] If you do a voice search for something that returns no results, you get an endless waiting spinner.

2023-02-09 00:53 UTC, 1hitsong commented
I'm unsure how best to approach item 1. I feel as if disabling scrolling Up all together isn't the right solution.

Just brainstorming here, what if we load the initial 20 channel data like you have it, then trigger the load task for the next 20. Once that batch loads, we load the next 20, etc. until all channels are loaded.

If a user scrolls up, they'll see the channel, and after a moment of waiting, the data will load. Users who only scroll down will have the best experience, and users who scroll up will have only a slight delay.

Thoughts?

2023-02-09 05:19 UTC, candry7731 commented
I like that theory! Can you implement it?

On Wed, Feb 8, 2023 at 6:53 PM 1hitsong ***@***.***> wrote:

> I'm unsure how best to approach item 1. I feel as if disabling scrolling
> Up all together isn't the right solution.
>
> Just brainstorming here, what if we load the initial 20 channel data like
> you have it, then trigger the load task for the next 20. Once that batch
> loads, we load the next 20, etc. until all channels are loaded.
>
> If a user scrolls up, they'll see the channel, and after a moment of
> waiting, the data will load. Users who only scroll down will have the best
> experience, and users who scroll up will have only a slight delay.
>
> Thoughts?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/841#issuecomment-1423451200>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRGQ76YHMBYWCCIYAZ3WWQ5YLANCNFSM6AAAAAARYYNVEY>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>


-- 
Chris Andry

462 Browning Loop
Mandeville LA 70448
504-617-2924

2023-02-10 02:03 UTC, 1hitsong commented
> I like that theory! Can you implement it?

I'll see what I can come up with this weekend.

2023-03-29 01:59 UTC, closed without merging