Add Aired Date to episode details
jellyfin-archive/jellyfin-roku-legacy pull request #844
Opened 2022-11-09 03:31 UTC by candry7731

Add Aired Date to the episode details row

**Changes**
Added Aired Date to the episode details row
Added "Aired" to the translation file

**Issues**
None Detected.

2022-11-09 13:22 UTC, jimdogx requested changes

2022-11-09 13:22 UTC, jimdogx commented on components/tvshows/TVListDetails.brs
> +    print item.json
debug code

2022-11-09 13:22 UTC, jimdogx commented on components/tvshows/TVListDetails.brs
> +    airDate = CreateObject("roDateTime")
Make sure to check for itemData.PremierDate <> invalid, otherwise this crashes on episodes that don't have an air date.

2022-11-09 16:50 UTC, candry7731 commented on components/tvshows/TVListDetails.brs
> +    airDate = CreateObject("roDateTime")
ahh, yes...... damn debug code and checks..... lol I'll get this updated

2022-11-09 21:41 UTC, 1hitsong requested changes
Let's go ahead and add the Aired Date to the individual episode screen as well. 

I know this screen is a mess, but ignore that for now.

You get to it by clicking on an episode on the home screen, in the Continue Watching section, then choosing Go To Episode from the popup.
![image](https://user-images.githubusercontent.com/3330318/200947606-a7626738-895c-4820-8157-008870050c13.png)

2022-11-09 21:49 UTC, 1hitsong commented
The spacing looks weird when the Aired date is the only item on the row. If there are no items to the left, let's make it align left.

![image](https://user-images.githubusercontent.com/3330318/200949125-8d2bdcc4-8a2b-4453-8b83-88b56eb40c3a.png)

2022-11-11 04:55 UTC, candry7731 commented
> The spacing looks weird when the Aired date is the only item on the row. If there are no items to the left, let's make it align left.
> 
> ![image](https://user-images.githubusercontent.com/3330318/200949125-8d2bdcc4-8a2b-4453-8b83-88b56eb40c3a.png)

This has been fixed

2022-12-05 23:11 UTC, 1hitsong commented
@candry7731 Can you resolve the merge conflicts?

2022-12-06 00:41 UTC, 1hitsong commented
I adjusted the spacing for the TV season episode list. I think it's looking good.

The movie view needs some help.

1. The label for movies should be "Released" not "Aired"
2. We show the release year first, then also the exact date. Let's only show 1 or the other
3. The data is so wide that it runs off the screen (See screenshot below)

![image](https://user-images.githubusercontent.com/3330318/205777489-012eaf4d-da44-4a99-b3cf-71aa1ce04abf.png)

2022-12-07 04:03 UTC, jimdogx approved these changes

2022-12-07 13:23 UTC, 1hitsong requested changes

2022-12-07 13:23 UTC, 1hitsong commented on components/movies/MovieDetails.brs
> -    setFieldText("officialRating", itemData.officialRating)
Why was the movie's content rating removed? (ex: PG, PG-13, R)

2022-12-07 18:48 UTC, candry7731 commented on components/movies/MovieDetails.brs
> -    setFieldText("officialRating", itemData.officialRating)
Good Catch, This was removed on accident.

2022-12-07 21:20 UTC, 1hitsong approved these changes

2022-12-07 21:21 UTC, merged