Working, needs more testing.
jellyfin-archive/jellyfin-roku-legacy pull request #857
Opened 2022-11-20 16:38 UTC by jimdogx

Show any "additional parts" (part 2, part 3, etc) of a movie.

**Changes**
Adds a new row of additional parts (if any are found) so that the user can continue watching Part2, Part 3, etc.

**Issues**
Fixes #830

2022-11-21 22:06 UTC, 1hitsong commented
👍 Works as intended.

The only issue I see is as the final row in the extras slide up, it's pretty well hidden. Can we check if additional parts exist and add a button to the main details page that says "Play Additional Parts" and popups up a list of found parts to play?

2022-11-21 23:46 UTC, jimdogx commented
> 👍 Works as intended.
> 
> The only issue I see is as the final row in the extras slide up, it's pretty well hidden. Can we check if additional parts exist and add a button to the main details page that says "Play Additional Parts" and popups up a list of found parts to play?

We could do that or we could just make sure additional parts is always first in the list (when additional parts are found of course).  Preference?

2022-11-22 13:56 UTC, 1hitsong commented
Using the issue as an example, we're talking about playing the 2nd half of the movie. It just feels wrong to have the playback button for it anywhere the user can't see immediately.

2022-11-22 15:33 UTC, jimdogx commented
> Using the issue as an example, we're talking about playing the 2nd half of the movie. It just feels wrong to have the playback button for it anywhere the user can't see immediately.

I was mostly trying to be consistent with the web client:
<img width="320" alt="Screenshot 2022-11-22 at 8 32 35 AM" src="https://user-images.githubusercontent.com/18198517/203355053-568c62ca-f322-45d2-a239-14651ec45213.png">

But there is no rule that says we need to do that (specially if we think we can do it better) 😄

2022-11-28 07:14 UTC, frob commented
Bringing my comment from the issue into the PR:

> I tested that build and it does show a section labeled "Additional Features" though it was hard to find.

> This new section is below "Cast & Crew" and the "More like this" section. It should probably be above those other sections and labeled "Additional Parts" which is how the web client presents it.

> Another bug I noticed with this was the screenshot isn't shown in a screen shot image style but rather if displays in a portrait style like the head shots and box art.

2022-11-28 07:19 UTC, frob commented
> We could do that or we could just make sure additional parts is always first in the list (when additional parts are found of course). Preference?

Another consideration is that they don't just say "Part 2" or "Part 3"

In the screenshot you post it is "Isle of Destiny - Part 2" in my example from the issue it would be "The Lord of the Rings The Fellowship of the Ring (2001) - Extended Edition Part 2" or really what gets show in the UI is something like "The L ... art 2"

2022-12-03 13:26 UTC, jimdogx commented
@frob I've pushed a changed that moves "Additional Parts" to the top (if found), just like on the web client.  Let me know if this works for you.

Also, the title of the Part 2 movie should scroll if it is too long, is it not scrolling for you?

2022-12-06 13:44 UTC, 1hitsong commented
This is better. 

Is there anything we can do with the thumbnail? Can we change it to a wide thumbnail instead of a vertical poster image?

2022-12-07 08:08 UTC, frob commented
![image](https://user-images.githubusercontent.com/316176/206122637-666a9ddd-65ab-4342-a918-5d58e3902f83.png)

It would be nice if the image was 16:9 or at least not squished.

![image](https://user-images.githubusercontent.com/316176/206122950-499cdc71-0ef5-45dc-8ef0-54c579786d60.png)

Additional Parts may still get lost with the text muted the way it is. Giving it a bit more line-height or even a tab like treatment may make it stand out more. If that is difficult then making the text white should do the trick.

2022-12-07 13:52 UTC, jimdogx commented
@frob @1hitsong I agree the thumbnail needs adjusting.  I'll see if I can do that one of these days.

As for the "Additional Parts" being muted, that is our current way of subtly hinting that there is more stuff below.  Not saying it is perfect or won't get redesigned in the future, but if you're using the Roku client you'll already be used to this pattern for everything else (e.g. Cast and Crew, More Like This, etc are all presented this way).

2022-12-07 14:06 UTC, 1hitsong commented
Perhaps in a follow up PR we can look into using some of the slider logic I made for the artist view.

2022-12-07 22:02 UTC, 1hitsong requested changes

2022-12-07 22:02 UTC, 1hitsong commented on components/extras/ExtrasRowList.brs
> +    m.top.rowItemSize = [[234, 396]]
```suggestion
        row = buildRow("Additional Parts", parts, 464)
        addRowSize([464, 291])
        m.top.content.appendChild(row)
    end if
    m.top.translation = "[75,10]"
    m.top.rowItemSize = [[464, 291]]
```

2022-12-07 22:02 UTC, 1hitsong commented on components/extras/ExtrasRowList.brs
> +    m.top.rowItemSize = [[234, 396]]
I believe this will make the thumbnail image be horizontal.

2022-12-08 13:50 UTC, jimdogx commented on components/extras/ExtrasRowList.brs
> +    m.top.rowItemSize = [[234, 396]]
Unfortunately that makes the first row wide no matter what the first row is (including Cast and Crew).  I'm taking a look now.

2022-12-08 13:54 UTC, jimdogx commented
@frob @1hitsong I think it's finally working correctly.  Wide thumbnail for Additional Parts, but keeping the slimmer aspect for Cast and Crew etc.

2022-12-08 14:13 UTC, 1hitsong approved these changes

2022-12-08 14:13 UTC, merged

2022-12-08 16:37 UTC, 1hitsong commented
@frob Found a bug in this that can cause the user to get stuck with no way out other than turning the roku off/on.

I've notified @jimdogx about the underlying issue, but the fix isn't very straightforward.