VideoNav Buttons
jellyfin-archive/jellyfin-roku-legacy pull request #859
Opened 2022-11-24 03:42 UTC by candry7731

add buttons to the video player

This is a working draft. 

- [ ] need to fix focus issues when dialogs are closed. 

- [ ] need to fix cast not populating when button selected

- [ ] add favorite button

- [ ] add mini guide button when watching live tv

**Issues**
many....

2023-02-02 04:55 UTC, sevenrats commented
there is still a focus issue with the cast slider.  i haven't nailed it down, but it is fairly common to drop focus into the video and have the cast slider remain on top.

2023-02-05 18:04 UTC, sevenrats commented
- [ ] closing thedescription dialog by any method makes it impossible to bring the buttons back up
- [ ] closing the playback info dialog by any method makes it impossible to bring the buttons back up
- [ ] down and back buttons should get rid of the buttongroup without stopping or closing video (just up feels claustrophobic)
- [ ] buttongroup should still be up when we press down from extras slider, maybe/maybe not when pressing back from dialogs

2023-02-11 03:00 UTC, 1hitsong commented
- [ ] Press down to show buttons. I expected pressing "Back" would close the buttons, but instead if left the video player.
- [ ] Press down to show buttons. Press "OK" to select info. Press "OK" to close info. Pressing down doesn't show the buttons.
- [ ] The Info dialog needs a title to go along with the info icon
- [ ] Clicking CC when video has no subtitles does nothing. We need to hide the button, disable the button (gray out button, put cross out over it?), or show a dialog telling the user there are no subtitles available.
- [ ] Clicking the Cast button when there is no cast data brings up an empty slider. We should do whatever we do with subtitles here as well.
- [ ] Play video. Press down, and choose Stream Info. Press "OK" once to close. With video still paused, press left to rewind. Pressing right doesn't fast forward.
- [ ] Icon text says Stream In.... last two letters are cut off on my Roku TV.
- [ ] Icon text says Stream In..., but first header text I see in the popup says Playback Info.

2023-02-11 03:01 UTC, 1hitsong requested changes

2023-02-11 03:01 UTC, 1hitsong commented on components/music/ArtistView.brs
> +                print "index= "m.top.selectedButtonIndex
Debug code

2023-02-11 03:01 UTC, 1hitsong commented on components/music/ArtistView.brs
> +                print "if press"
Debug code

2023-02-11 03:01 UTC, 1hitsong commented on components/music/ArtistView.brs
> +                print "first if"
Debug code

2023-02-11 03:01 UTC, 1hitsong commented on components/music/ArtistView.brs
> +                    print "second if"
Debug code

2023-02-11 03:01 UTC, 1hitsong commented on components/music/ArtistView.brs
> +                print "index= "m.top.selectedButtonIndex
Debug code

2023-02-11 03:02 UTC, sevenrats commented
I have a pr that just needs to get polished up that essentially fixes all the focus issues.  I will submit it to this branch tomorrow probably. @candry, don't fix any of the above until you see my code unless you're down to duplicate work.

2023-02-11 03:27 UTC, 1hitsong requested changes

2023-02-11 03:27 UTC, 1hitsong commented on components/PersonDetails.brs
> +    'm.top.findNode("VertSlider").keyValue = "[[30, 998], [30, 789], [30, 580], [30,371 ], [30, 162]]"
Remove commented out code

2023-02-11 03:27 UTC, 1hitsong commented on components/PersonDetails.brs
> +    'm.extrasGrp.translation = "[30, 998]"
Remove commented out code

2023-02-11 03:27 UTC, 1hitsong commented on components/JFVideo.brs
> +    if m.buttonGrp.visible = true
```suggestion
    if m.buttonGrp.visible
```

2023-02-11 04:04 UTC, candry7731 commented
@sevenrats, Thanks I will wait for your pr.

2023-02-21 03:25 UTC, sevenrats commented
since i had to implement another special-case dialog, i think it would be wise if this PR also renamed the relatively new "PlaybackDialog" to be called "PlaybackFailureDialog" to make it more reasonably distinct from the new "PlaybackInfoDialog"

Other than that, I think this is ready for prime time.

2023-02-22 23:56 UTC, 1hitsong commented
- [ ] Switching channels from mini guide didn't work. Resulted in never ending spinner
- [ ] Regression: Pressing "OK" while video plays no longer toggles playback
- [ ] The Info & stream info dialogs need a title to go along with the icon
- [ ] Play video. Press down, and choose Stream Info. Press "OK" once to close. Pressing left will rewind. Pressing right doesn't fast forward.
- [ ] Icon text says "Stream In" last two letters are cut off on my Roku TV.

2023-02-22 23:57 UTC, 1hitsong requested changes

2023-02-22 23:57 UTC, 1hitsong commented on components/JFVideo.brs
> +            print "m.top.id" m.top.id
Debug code

2023-02-23 00:00 UTC, candry7731 commented
Hmm,

Not sure why any of this would change?? We have tested this on unstable a
ton.....

Ill check it out again.

On Wed, Feb 22, 2023, 5:56 PM 1hitsong ***@***.***> wrote:

>
>    - Switching channels from mini guide didn't work. Resulted in never
>    ending spinner
>    - Regression: Pressing "OK" while video plays no longer toggles
>    playback
>    - The Info & stream info dialogs need a title to go along with the icon
>    - Play video. Press down, and choose Stream Info. Press "OK" once to
>    close. Pressing left will rewind. Pressing right doesn't fast forward.
>    - Icon text says "Stream In" last two letters are cut off on my Roku
>    TV.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/859#issuecomment-1441019749>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AT6PDRERT7G4NRHNMZ5DPI3WY2RT7ANCNFSM6AAAAAASJVHTG4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-02-23 02:16 UTC, candry7731 reviewed
@1hitsong can you remove this commit? I committed it by accident.

2023-02-23 04:19 UTC, candry7731 commented
Switching channels from mini guide didn't work. Resulted in never ending spinner - DONE
 Regression: Pressing "OK" while video plays no longer toggles playback
 The Info & stream info dialogs need a title to go along with the icon - DONE
 Icon text says "Stream In" last two letters are cut off on my Roku TV. - DONE

**Still needs work**
 Play video. Press down, and choose Stream Info. Press "OK" once to close. Pressing left will rewind. Pressing right doesn't fast forward.
 Regression: Pressing "OK" while video plays no longer toggles playback

2023-04-14 04:08 UTC, candry7731 reviewed
Fixes Regression: Pressing "OK" while video plays no longer toggles playback

2023-04-22 21:11 UTC, cewert commented on locale/en_US/translations.ts
> +         <message>
```suggestion
        <message>
```

2023-04-22 21:11 UTC, cewert commented on locale/en_US/translations.ts
> +            <translation>Stream Information</translation>
```suggestion
            <translation>Program Information</translation>
```

2023-04-22 21:13 UTC, cewert commented on locale/en_US/translations.ts
> +            <extracomment>Trickplaybar button, Guide</extracomment>
```suggestion
            <extracomment>Trickplaybar button text</extracomment>
```

No need to add "guide". It's obvious from context

2023-04-22 21:14 UTC, cewert commented on locale/en_US/translations.ts
> +            <extracomment>Trickplaybar button, Info</extracomment>
```suggestion
            <extracomment>Trickplaybar button text</extracomment>
```

2023-04-22 21:15 UTC, cewert commented on locale/en_US/translations.ts
> +            <extracomment>Trickplaybar button, Cast</extracomment>
```suggestion
            <extracomment>Trickplaybar button text</extracomment>
```

2023-04-22 21:15 UTC, cewert commented on locale/en_US/translations.ts
> +            <extracomment>Trickplaybar button, Loop</extracomment>
```suggestion
            <extracomment>Trickplaybar button text</extracomment>
```

2023-05-21 01:56 UTC, closed without merging