nest related settings
jellyfin-archive/jellyfin-roku-legacy pull request #905
Opened 2022-12-17 17:21 UTC by sevenrats

Nested some related settings, change some settings strings

2022-12-21 13:44 UTC, 1hitsong requested changes
While you're in there, how about moving `UI/Design Elements/Use Splashscreen as Home Background` to the `UI/Homepage` section?

2022-12-21 13:44 UTC, 1hitsong commented on settings/settings.json
> +                "description": "Enable or disable Direct Play for optional codecs",
```suggestion
                "description": "Enable or disable Direct Play support for certain codecs",
```

2022-12-29 13:52 UTC, jimdogx approved these changes

2022-12-29 14:11 UTC, 1hitsong approved these changes

2022-12-29 14:11 UTC, merged