restore tag query parameter
jellyfin-archive/jellyfin-roku-legacy pull request #907
Opened 2022-12-17 21:50 UTC by sevenrats

revert # 605
these were manual reversions please review carefully.

2022-12-17 23:28 UTC, sevenrats commented
Still needs tags added to image calls:
- [ ] MusicAlbumSongListData.brs
- [ ] MusicArtistData.brs

2022-12-17 23:56 UTC, sevenrats commented on components/data/ChannelData.brs
> +        m.top.hdsmalliconurl = api_API().items.getimageurl(m.top.itemId, "logo", 0, imgParams)
wrong type

2022-12-17 23:58 UTC, sevenrats commented on components/data/HomeData.brs
> +        if datum.ImageTags.Primary <> invalid
Is this check appropriate?

2022-12-17 23:59 UTC, sevenrats commented on components/data/HomeData.brs
replicate this reformatting in similar blocks

2022-12-18 00:00 UTC, sevenrats commented on components/data/HomeData.brs
> +        if datum.ImageTags.Primary <> invalid
do we need this new check either?

2022-12-18 00:00 UTC, sevenrats commented on components/data/HomeData.brs
> +        if datum.ImageTags.Primary <> invalid
another new check maybe not needed

2022-12-20 02:39 UTC, 1hitsong commented
- [ ] Movie Extras throws warning `[sg.scene.bitmap.big] Warning! Loaded texture (800 x 1200) larger than the UI resolution (1920 x 1080) - ExtrasItem/Poster:posterImg`
- [ ] Actor throws warning `[sg.scene.bitmap.big] Warning! Loaded texture (1000 x 1500) larger than the UI resolution (1920 x 1080) - ExtrasItem/Poster:posterImg`
- [ ] TV Show extras throws warning `[sg.scene.bitmap.big] Warning! Loaded texture (1000 x 1500) larger than the UI resolution (1920 x 1080) - ExtrasItem/Poster:posterImg`
- [ ] Clicking on a Music Artist causes crash `ImageURL() is not defined` - line 360 in items.brs
- [ ] Clicking on a song to play it causes crash `PosterImage() is not defined` - line 150 and 154 in itemsbrs

2022-12-21 13:34 UTC, 1hitsong requested changes
- [ ] Movie Extras throws warning `[sg.scene.bitmap.big] Warning! Loaded texture (800 x 1200) larger than the UI resolution (1920 x 1080) - ExtrasItem/Poster:posterImg`
- [ ] Actor throws warning `[sg.scene.bitmap.big] Warning! Loaded texture (1000 x 1500) larger than the UI resolution (1920 x 1080) - ExtrasItem/Poster:posterImg`
- [ ] TV Show extras throws warning `[sg.scene.bitmap.big] Warning! Loaded texture (1000 x 1500) larger than the UI resolution (1920 x 1080) - ExtrasItem/Poster:posterImg`
- [ ] Clicking on a Music Artist causes crash `ImageURL() is not defined` - line 360 in items.brs
- [ ] Clicking on a song to play it causes crash `PosterImage() is not defined` - line 150 and 154 in itemsbrs

2022-12-25 17:40 UTC, cewert commented
Did you revert #605 or did you change them back manually? I don't see the revert in the commit log

As far as deprecating `ImageURL()`, maybe that should be it's own PR? Or does that need to be done at the same time to make it work?

I approved the CI to run and there were a lot of validation errors - see [here](https://github.com/jellyfin/jellyfin-roku/actions/runs/3722614271/jobs/6414872301). Looks like a lot of the same stuff @1hitsong found. You can also view these locally by running `npm run validate` FYI

2022-12-26 18:13 UTC, sevenrats commented
> Did you revert #605 or did you change them back manually? I don't see the revert in the commit log
> 
> As far as deprecating `ImageURL()`, maybe that should be it's own PR? Or does that need to be done at the same time to make it work?
> 
> I approved the CI to run and there were a lot of validation errors - see [here](https://github.com/jellyfin/jellyfin-roku/actions/runs/3722614271/jobs/6414872301). Looks like a lot of the same stuff @1hitsong found. You can also view these locally by running `npm run validate` FYI

i did it manually as I note in my comment.  there were so many conflicts with the automatic revert that it was just easier to reverse it by hand.
as far as the deprecation is concerned, it's something that 1hitsong and I talked about because I'm already knee deep in the relevant lines.  its a burden to review, for sure, but we figured 1 heavy pr would be better than 2 heavy prs, in that respect.

I will validate before I push from now on.

2022-12-26 19:27 UTC, sevenrats commented
hmm. actually now that I'm knee-deep in this, I kinda suspect that it should be done differently.  Instead of replacing ImageURL calls with the api call directly, we should simply retool Images.brs to use the api.  the primary reason for this is  the checks in ImageURL:
![image](https://user-images.githubusercontent.com/79296037/209578389-5c61825f-c22f-4e0e-92f5-28720c9081a9.png)

2022-12-26 22:09 UTC, sevenrats commented
too much.

2022-12-26 22:09 UTC, closed without merging