Add user setting: Go straight to episode listing (if only 1 season)
jellyfin-archive/jellyfin-roku-legacy pull request #919
Opened 2022-12-22 23:46 UTC by ApexArray

**Changes**
Adds a new user setting that, when enabled, goes straight to episode listing when selecting TV series with only one season.

If enabled,, selecting a TV series with only one season will go straight to the episode listing for that season, rather than the season listing.

**Issues**
Discussed in #662

**Tests**
Tested multiple series with various numbers of seasons/episodes on Roku 4200X:
✔ Single-season series go straight to episode listing
✔ While in episode listing, the back button correctly returns to TV series listing, rather than the (bypassed) season listing
✔ Multi-season series are not affected, and always go to season listing
✔ Reverts to old behavior when setting is disabled

2022-12-23 13:57 UTC, 1hitsong requested changes

2022-12-23 13:57 UTC, 1hitsong commented on settings/settings.json
> +                        "default": "true"
Default should be false

2022-12-23 13:57 UTC, 1hitsong commented on settings/settings.json
> +                        "title": "Go straight to episode listing (if only 1 season)",
1. Settings titles should capitalize main works.
2. Can we shorted it so it doesn't scroll in the full view? How do you feel about "Skip Details for Single Seasons"

2022-12-23 13:57 UTC, 1hitsong commented on settings/settings.json
> +                        "description": "If enabled, selecting a TV series with only one season will go straight to the episode listing for that season, rather than the season listing.",
```suggestion
                        "description": "If enabled, selecting a TV series with only one season will go straight to the episode list rather than the show details and season list.",
```

2022-12-23 15:47 UTC, ApexArray commented on settings/settings.json
> +                        "title": "Go straight to episode listing (if only 1 season)",
Makes sense to me. No need to cram details in the title.

2022-12-23 16:19 UTC, 1hitsong requested changes

2022-12-23 16:19 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <source>If enabled, selecting a TV series with only one season will go straight to the episode list rather than the show details and season list..</source>
2 periods at the end.

2022-12-23 16:19 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <translation>If enabled, selecting a TV series with only one season will go straight to the episode list rather than the show details and season list..</translation>
2 periods at the end.

2022-12-23 16:19 UTC, 1hitsong commented on settings/settings.json
> +                        "description": "If enabled, selecting a TV series with only one season will go straight to the episode list rather than the show details and season list..",
2 periods at the end.

2022-12-23 16:48 UTC, ApexArray commented
Doh! Fixed.

2022-12-24 13:51 UTC, 1hitsong approved these changes

2022-12-24 13:51 UTC, 1hitsong commented
To be merged 12/26 unless issue arises.

2022-12-28 13:45 UTC, merged