Fix crash on empty contentId
jellyfin-archive/jellyfin-roku-legacy pull request #920
Opened 2022-12-23 17:18 UTC by ApexArray

For some reason, launching the channel via a RASP automation script sets this value to an empty string in stead of null, which was causing the channel to crash.

**Changes**
Fixes crash when `args.contentId` is set to an empty string.

Also replaces instances of `<> invalid` with `isValid()` within this function.

2022-12-28 14:06 UTC, 1hitsong requested changes

2022-12-28 14:06 UTC, 1hitsong commented on source/Main.brs
> +    if isValid(args.mediaType) and isValid(args.contentId) and not args.contentId = ""
`args.mediaType` Also needs to be confirmed as not an empty string.

Both arg empty string checks should be trimmed so `" "` won't be valid

2022-12-28 14:06 UTC, 1hitsong commented on source/Main.brs
> +        if isValid(video) and video.errorMsg <> "introaborted"
If bad data is passed, even with these checks the client will crash. Let's go ahead and make the client stay working.

In Subtitles.brs change line 24 `if meta.json.mediaSources <> invalid` to `if meta?.json?.mediaSources <> invalid`

In videoplayer.brs, move `m.videotype = meta.type` down to after the `if meta = invalid` condition block.

2022-12-28 16:23 UTC, ApexArray commented on source/Main.brs
> +    if isValid(args.mediaType) and isValid(args.contentId) and not args.contentId = ""
Good call. This would make the if-statement pretty long though.  We're also likely to need to apply these checks in other locations in the future.

What are your thoughts on adding a new function `isValidNotEmpty()` that combines all these checks together?

2022-12-28 17:31 UTC, 1hitsong requested changes

2022-12-28 17:31 UTC, 1hitsong commented on source/VideoPlayer.brs
> +        m.videotype = meta.type
Close. This needs to move down to line 30, after the entire condition block.

2022-12-28 17:31 UTC, 1hitsong commented on source/Main.brs
> +    if isValid(args.mediaType) and isValid(args.contentId) and not args.contentId = ""
Using C# as a reference, they use `IsNullOrEmpty()`  so how about we use `isValidAndNotEmpty()`

2022-12-28 23:44 UTC, ApexArray commented on source/VideoPlayer.brs
> +        m.videotype = meta.type
Sorry about that! I really need to pay closer attention to my PRs before resolivng/requesting review.

2022-12-29 00:52 UTC, ApexArray commented on source/Main.brs
> +    if isValid(args.mediaType) and isValid(args.contentId) and not args.contentId = ""
Implemented in latest commit.

2022-12-29 14:39 UTC, 1hitsong requested changes

2022-12-29 14:39 UTC, 1hitsong commented on source/utils/misc.brs
> +    if type(input) = "String" or type(input) = "roString"
Instead of determining the type 2 more times, let's reuse the inputType variable.

Also, all string comparisons should force case just to be safe. So we should ensure both sides are LCase() before comparing.

2022-12-29 20:29 UTC, ApexArray commented
Tests:
![image](https://user-images.githubusercontent.com/91706106/210008168-d40e327a-377e-4889-8571-ce271a82145c.png)

2022-12-31 13:30 UTC, 1hitsong approved these changes

2022-12-31 13:31 UTC, merged