Fix distorted TV episode posters
jellyfin-archive/jellyfin-roku-legacy pull request #922
Opened 2022-12-24 20:37 UTC by ApexArray

**Changes**
Sets `loadDisplayMode="scaleToZoom"` on TV episode posters to avoid squashing the image. 

From the [Roku docs](https://developer.roku.com/docs/references/scenegraph/renderable-nodes/poster.md#fields):
> Scale the image to fill the target screen element area, preserving the aspect ratio but not "letterboxing" or "pillarboxing" the image, with some of the image cropped out.

Before and after:
![image](https://user-images.githubusercontent.com/91706106/209450359-7cf6f8c3-f3dd-499b-8aff-ee0f3d2d56d0.png)
![image](https://user-images.githubusercontent.com/91706106/209450363-11eacbb0-69d1-4d23-9790-7f5e51f954b7.png)

**Issues**
Fixes #603

2022-12-25 16:43 UTC, cewert commented
What if we changed the poster size to be 16:9 aspect ratio and used `loadDisplayMode="scaleToFit"`? HD Posters would be fixed with no resize and SD 4:3 posters would use the black bars but keep aspect ratio and no zooming. I would prefer to have the black bars than zoom and lose the whole image but that's my 2c.

2022-12-26 23:48 UTC, ApexArray commented
I considered that as well, but I figured it was best to default to the same behavior in jellyfin-web. It looks like they’re cropping the image and adding a custom icon/progress bar.

2022-12-28 22:47 UTC, ApexArray commented
I think this is a good semi-final version of this PR. Thanks @neilsb for pointing me in the right direction on the "played" icon.

@1hitsong, care to take a look?

2022-12-29 22:15 UTC, 1hitsong requested changes

2022-12-29 22:15 UTC, 1hitsong commented on components/tvshows/TVListDetails.xml
> +          <Rectangle id="progressBackground" visible="false" color="0x00000098" width="350" height="16" translation="[0,286]">
Can we make the height 8 to match the homepage bar height?

2022-12-29 22:15 UTC, 1hitsong commented on source/api/Items.brs
> -        imgParams = { "AddPlayedIndicator": item.UserData.Played, "maxWidth": 400, "maxheight": 250 }
By removing the maxWidth and maxHeight params, the default values of maxWidth=384 and maxHeight=196 are used.

We then are resizing it to 350x300 using the poster tag, meaning we're blowing up the image, which is causing them to be blurry. We can remove the AddPlayedIndicator, but should add back `imgParams = { "maxWidth": 350, "maxheight": 300 }`

2022-12-29 22:15 UTC, 1hitsong commented on source/api/Items.brs
> -        imgParams = { "AddPlayedIndicator": item.UserData.Played, "maxWidth": 400, "maxheight": 250 }
As Is Today
![image](https://user-images.githubusercontent.com/3330318/210015402-d0276821-3235-42bc-b266-dea3856d8910.png)

Updated, but no imgParams
![image](https://user-images.githubusercontent.com/3330318/210015427-806b07ff-875e-42b1-8d09-4e160fc85f3e.png)

Updated, with imgParams
![image](https://user-images.githubusercontent.com/3330318/210015447-6e2b250c-7cd2-4a25-92a8-a2cecac6b318.png)

2022-12-29 22:15 UTC, 1hitsong commented on components/tvshows/TVListDetails.xml
> +            <Label id="checkmark" width="60" height="42" font="font:SmallestBoldSystemFont" horizAlign="center" vertAlign="bottom" text="✓"/>
Let's bump up the font size on the check to 35.

Here's what it looks like.
![image](https://user-images.githubusercontent.com/3330318/210016068-f7ce234d-7f57-4735-be1e-dbe79632765a.png)

2022-12-29 22:36 UTC, ApexArray commented on components/tvshows/TVListDetails.xml
> +          <Rectangle id="progressBackground" visible="false" color="0x00000098" width="350" height="16" translation="[0,286]">
At a height of 8, the row selector blocks a good chunk of the progress bar. Do we want to stick with this height, or try to move/resize the progress bar on selection?

2022-12-29 22:37 UTC, ApexArray commented on components/tvshows/TVListDetails.xml
> +          <Rectangle id="progressBackground" visible="false" color="0x00000098" width="350" height="16" translation="[0,286]">
image.png

2022-12-29 22:57 UTC, ApexArray commented on components/tvshows/TVListDetails.xml
> +            <Label id="checkmark" width="60" height="42" font="font:SmallestBoldSystemFont" horizAlign="center" vertAlign="bottom" text="✓"/>
Is there a way to override font size here? Couldn't find a way to do that, so I've set it over in the TVListDetails.brs init funciton.

2022-12-29 23:03 UTC, ApexArray commented on source/api/Items.brs
> -        imgParams = { "AddPlayedIndicator": item.UserData.Played, "maxWidth": 400, "maxheight": 250 }
Good catch. fixed in latest commit.

2023-01-26 22:25 UTC, 1hitsong approved these changes

2023-01-26 22:26 UTC, 1hitsong commented
To be merged 1/27 unless an issue arises.

2023-01-27 13:04 UTC, merged