Disable Community Rating for Episodes of TV shows
jellyfin-archive/jellyfin-roku-legacy pull request #937
Opened 2023-01-01 14:31 UTC by dezchai

**Changes**
Outlined in more detail in the enhancement request https://github.com/jellyfin/jellyfin-roku/issues/936
Adds setting to disable community rating for episodes of TV shows.

Also, the if statement could maybe be brought out so that it's not nested.
```Brightscript
if get_user_setting("ui.tvshows.disableCommunityRating") = "false"
    if isValid(itemData.communityRating)
        m.top.findNode("star").visible = true
        m.top.findNode("communityRating").text = str(int(itemData.communityRating * 10) / 10)
    else
        m.top.findNode("star").visible = false
    end if
```

```Brightscript
if get_user_setting("ui.tvshows.disableCommunityRating") = "false" and isValid(itemData.communityRating)
    m.top.findNode("star").visible = true
    m.top.findNode("communityRating").text = str(int(itemData.communityRating * 10) / 10)
else:
    m.top.findNode("star").visible = false
end if
```
**Issues**
ex. Fixes #936 

**To Do**
A small spacing is left over after the setting is turned on.

2023-01-01 14:50 UTC, jimdogx commented on settings/settings.json
> +                        "title":"Disable Community Rating for Episodes",
Don't forget to add these new strings (title and description) to locale\translations.  You only need to add it to the en-US one, the rest will magically get updated.

2023-01-01 15:17 UTC, dezchai commented on settings/settings.json
> +                        "title":"Disable Community Rating for Episodes",
Thanks for letting me know.
Added.

2023-01-01 18:05 UTC, jimdogx requested changes

2023-01-01 18:05 UTC, jimdogx commented on components/tvshows/TVListDetails.brs
> +        m.top.findNode("rating").visible = false
```suggestion
       m.rating.visible = false
       m.infoBar.itemSpacings = [20, -25, 20, 20] 
```

Recommend using the already defined global variable m.rating instead of "finding node" again.  Also, adding the new itemSpacings line fixes the blank space issue.

2023-01-01 18:06 UTC, jimdogx commented
For future PRs, make sure to name your branch something informative (instead of the default main branch name of "unstable").  For example, for this PR, I would have named it something like "disable-community-rating" 👍

2023-01-02 13:16 UTC, jimdogx approved these changes

2023-01-02 13:17 UTC, jimdogx commented
Congrats on your first contribution.  Now come join us in the [Matrix](https://matrix.to/#/+jellyfin:matrix.org) 😄

2023-01-02 13:17 UTC, merged