Don't crash when viewing in progress recording.
jellyfin-archive/jellyfin-roku-legacy pull request #939
Opened 2023-01-02 22:52 UTC by jimdogx

Current version crashes when trying to view a recording in progress.

**Changes**
Defensive coding

**Issues**
Fixes #501

2023-01-04 13:47 UTC, 1hitsong requested changes

2023-01-04 13:47 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if isValid(meta.json) and isValid(meta.json.ChannelId)
```suggestion
    if isValid(meta?.json?.ChannelId)
```

2023-01-04 13:47 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if meta.live = invalid
```suggestion
    if not isValid(meta.live)
```

2023-01-04 13:47 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if m.playbackInfo.MediaSources[0] = invalid and isValid(meta.json)
```suggestion
    if not isValid(m.playbackInfo.MediaSources[0]) and isValid(meta.json)
```

2023-01-04 13:47 UTC, 1hitsong commented on source/VideoPlayer.brs
> +    if meta.json = invalid or meta.json.mediaSources = invalid then return ""
```suggestion
    if not isValid(meta?.json?.mediaSources) then return ""
```

2023-01-04 14:09 UTC, jimdogx commented on source/VideoPlayer.brs
> +    if isValid(meta.json) and isValid(meta.json.ChannelId)
I keep forgetting that Roku introduced the ? operator recently.  Thanks 👍

2023-01-04 19:06 UTC, 1hitsong approved these changes

2023-01-05 07:11 UTC, neilsb approved these changes

2023-01-05 13:36 UTC, merged

2023-01-09 15:13 UTC, numericOverflow commented
@jimdogx - Is there a way for me to test this updated version of the Roku app now that you've implemented a fix?

2023-01-09 19:52 UTC, jimdogx commented
@numericOverflow if you feel comfortable with side loading apps on your Roku (it does not remove or alter your main installation), you can read up on it more here:

https://github.com/jellyfin/jellyfin-roku/blob/unstable/DEVGUIDE.md