improve settings menu
jellyfin-archive/jellyfin-roku-legacy pull request #964
Opened 2023-01-16 00:51 UTC by sevenrats

I noticed I have a credit for the settings organization now so I figured they better look nice lol.  This is mostly an aesthetic change, with the exception of the ellimination of a confusing and redundant setting in the MovieGridView that is not currently being used as far as I can tell.  I pointed the setting at "alwaysShowTitles" or whatever its called.
This structure should be ready to get expanded as new views are implemented.  If there are no notes I will add the new strings, but this draft does not include translations because we may decide to change some strings.
Please let me know what you think.

2023-01-16 01:09 UTC, sevenrats commented
I see now that I pulled out the newer of the two settings.  I put the new setting back and stitched it together while we wait for the new grid view to be implemented.

2023-01-18 17:55 UTC, candry7731 commented
Looks good to me.

2023-01-18 18:06 UTC, candry7731 approved these changes
I think as we add to this we always need to think about our wording to make sure it is easy for our grandparents to understand.... if they can understand then everyone else will too. 

I think this is great!

2023-01-26 00:07 UTC, 1hitsong requested changes

2023-01-26 00:07 UTC, 1hitsong commented on settings/settings.json
> +                                        "title": "Return to Top",
Return to Top setting is used outside of Presentation Views. It likely fits under "General."

2023-01-26 00:07 UTC, 1hitsong commented on settings/settings.json
> +                                                "title": "Always Hide",
Always Hide is currently only implemented for Movies.

2023-01-26 00:07 UTC, 1hitsong commented on settings/settings.json
> +                        "settingName": "load.allowwhatsnew",
Having the what's new popup setting under UI feels out of place.

2023-01-26 00:38 UTC, 1hitsong requested changes

2023-01-26 00:38 UTC, 1hitsong commented on settings/settings.json
> +                "title": "General",
Since we're already moving so many things around, let's go ahead and put each of the left navigation menus in alphabetical order.

2023-01-27 01:25 UTC, sevenrats commented on settings/settings.json
> +                "title": "General",
I feel like the "general" one should always be at the top.
my gut instinct says:
1) General menu
2) All setting menus in alpha order
3) All settings in alpha order

2023-01-27 05:52 UTC, sevenrats commented on settings/settings.json
> +                                                "title": "Always Hide",
im not really sure what to do about that.  maybe just change the description to let people know this until we are done migrating to new layouts?

2023-01-27 05:52 UTC, sevenrats commented on settings/settings.json
> +                        "settingName": "load.allowwhatsnew",
I'm open to suggestions but it's a UI thing.

2023-01-27 06:05 UTC, sevenrats commented on settings/settings.json
> +                "title": "General",
this would be much better looking if menus _looked_ like menus.  like they do in file trees and stuff.

2023-01-27 23:41 UTC, 1hitsong commented on settings/settings.json
> +                                                "title": "Always Hide",
How about `Always Hide (Movie Library Only)`

2023-01-28 17:40 UTC, sevenrats commented on settings/settings.json
> +                                                "title": "Always Hide",
just implemented the feature everwhere else instead.

2023-01-28 21:12 UTC, sevenrats commented
tiny bug: the item that is automatically selected when the library is loaded does not have it's title shown when "showonhover" is set, but I can't seem to figure out why.

2023-02-02 01:31 UTC, 1hitsong approved these changes

2023-02-02 01:32 UTC, 1hitsong commented
To be merged 2/2 unless an issue arises.

2023-02-02 14:07 UTC, merged