Allow for unlimited bitrate
jellyfin-archive/jellyfin-roku-legacy pull request #975
Opened 2023-01-25 13:50 UTC by jimdogx

Just giving the people what they want.  Some users swear that without capping their bitrate, their devices can direct stream videos that have a higher bitrate than what Roku says is allowed.

**Changes**
New setting that will not send the max bitrate to the Jellyfin server.  With the default being OFF.

**Issues**
Users that don't understand this setting my turn it on and have issues with playback.

2023-01-25 14:07 UTC, 1hitsong requested changes

2023-01-25 14:07 UTC, 1hitsong commented on source/utils/deviceCapabilities.brs
> +    else
else isn't needed. If we call into the main condition, we're returned.

2023-01-25 14:38 UTC, jimdogx commented on source/utils/deviceCapabilities.brs
> +    else
This is why I shouldn't code at 5 am before I've had my coffee or breakfast 😄

2023-01-26 02:35 UTC, 1hitsong requested changes
I reworded the setting a bit. The translations will need to be updated once finalized.

2023-01-26 02:35 UTC, 1hitsong commented on settings/settings.json
> +                "title": "Turn off bitrate limiting",
```suggestion
                "title": "Bitrate Limiting",
```

2023-01-26 02:35 UTC, 1hitsong commented on settings/settings.json
> +                "description": "This will ignore Roku's official max bitrate specifications and attempt to stream without enforcing a max bitrate.",
```suggestion
                "description": "Enable or disable limiting video bitrates based on Roku's specifications.",
```

2023-01-26 02:35 UTC, 1hitsong commented on settings/settings.json
> +                "default": "false"
```suggestion
                "default": "true"
```

2023-01-26 02:35 UTC, 1hitsong commented on settings/settings.json
> +                "settingName": "playback.bitrate.unlimited",
```suggestion
                "settingName": "playback.bitrate.maxlimited",
```

2023-01-26 02:35 UTC, 1hitsong commented on source/utils/deviceCapabilities.brs
> +    if get_user_setting("playback.bitrate.unlimited") = "true"
```suggestion
    if not get_user_setting("playback.bitrate.maxlimited") = "true"
```

2023-01-26 03:26 UTC, jimdogx commented on source/utils/deviceCapabilities.brs
> +    if get_user_setting("playback.bitrate.unlimited") = "true"
I went ahead and adjusted the if block now that it's "maxlimited" instead of "unlimited" 👍

2023-01-26 03:46 UTC, NeuroDawg commented
Thanks. I'm one of those folks who's Roku 4 would play h264 files with bitrates higher than Roku publishes.

2023-01-27 04:35 UTC, candry7731 commented
Should we add an alert to change the setting if the video fails/errors because of the bitrate setting?

2023-01-27 05:28 UTC, crobibero commented
Just an fyi- if the bitrate limit isnt set the server will default to 80Mbit

2023-01-27 12:44 UTC, jimdogx commented
> Should we add an alert to change the setting if the video fails/errors because of the bitrate setting?

The default will be to limit it per Roku's specs.  I think most users won't be changing this setting.  For those that do, they most likely know what they're getting themselves in to 😄

2023-01-29 18:31 UTC, sevenrats commented
can we please change "Bitrate Limiting" to "Limit Bitrate"  this will better match our current style of using imperatives instead of infinitives.

2023-02-04 14:02 UTC, 1hitsong requested changes

2023-02-04 14:02 UTC, 1hitsong commented on source/utils/deviceCapabilities.brs
> +    print "DEBUG: "
Debug code 255 - 261

2023-02-04 14:13 UTC, 1hitsong requested changes

2023-02-04 14:13 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <source>Max bitrate (MBPS) to use if 'Limit Bitrate' is enabled. If set to 0 limits will be per Roku's specifications.</source>
```suggestion
            <source>Max bitrate (MBPS) to use if 'Limit Bitrate' is enabled. Set to 0 to use Roku's specifications.</source>
```

2023-02-04 14:13 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <translation>Max bitrate (MBPS) to use if 'Limit Bitrate' is enabled. If set to 0 limits will be per Roku's specifications.</translation>
```suggestion
            <translation>Max bitrate (MBPS) to use if 'Limit Bitrate' is enabled. Set to 0 to use Roku's specifications.</translation>
```

2023-02-04 14:13 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <source>Enable or disable limiting video bitrates (based on the 'Playback Bitrate Limit' setting *or* Roku's specifications).</source>
```suggestion
            <source>If enabled, playback bitrates will be limited based on the 'Playback Bitrate Limit' setting.</source>
```

2023-02-04 14:13 UTC, 1hitsong commented on locale/en_US/translations.ts
> +            <translation>Enable or disable limiting video bitrates (based on the 'Playback Bitrate Limit' setting *or* Roku's specifications).</translation>
```suggestion
            <translation>If enabled, playback bitrates will be limited based on the 'Playback Bitrate Limit' setting.</translation>
```

2023-02-04 14:20 UTC, jimdogx commented on source/utils/deviceCapabilities.brs
> +    print "DEBUG: "
@#$^@#ADF@%

2023-02-04 15:29 UTC, sevenrats commented on settings/settings.json
> +                "title": "Limit Bitrate",
would you please insert these settings in alphabetical order?  It goes General Menu, Menus, Settings.

2023-02-04 15:31 UTC, jimdogx commented on settings/settings.json
> +                "title": "Limit Bitrate",
I think @1hitsong just did this for me 👍

2023-02-04 17:31 UTC, 1hitsong approved these changes

2023-02-04 17:32 UTC, merged