reorganize options modal
jellyfin-archive/jellyfin-roku-legacy pull request #979
Opened 2023-01-26 06:49 UTC by sevenrats

**Changes**
reorganize options modal per conversation from chat.

2023-01-27 07:25 UTC, sevenrats commented
i can't get any genres to show up in my music library even after using beets with the genre plugin, so I'm unable to test that.  if you have music genres, please test.

2023-02-11 00:16 UTC, 1hitsong commented
Regression: I set my layout to Presentation view, but when I click on a movie genre it shows in grid view.

2023-02-11 00:23 UTC, 1hitsong commented
Regressioin: Music Library - Genre View no longer works. Logs a warning in console.

```
=================================================================
Warning occurred while setting a field of an RoSGNode
-- Tried to set nonexistent field "view" of a "MusicLibraryView" node
pkg:/components/ItemGrid/MusicLibraryView.brs(662)
=================================================================
```

2023-02-11 00:29 UTC, 1hitsong commented
Regressioin: Music Library - Views get messed up. Select View: Artists & Layout Presentation. Now change View to Album. The items are now in grid layout, but the presentation data remains visible behind the items.

https://user-images.githubusercontent.com/3330318/218226214-034097ed-d3b1-443e-aba7-5ec4c29acae1.mp4

2023-02-11 00:39 UTC, 1hitsong requested changes
Notes for follow up PRs:

1. Favorites is still a filter for everything other than the Movie Library
2. This removes the ability for users to Favorite something from the library view

2023-02-11 00:39 UTC, 1hitsong commented on components/data/MovieData.brs
> +        else if isValid(m.top.json.BackdropImageTags)
This isValid() isn't testing the same as it did before. It needs to test the first item is valid.

2023-02-11 00:39 UTC, 1hitsong commented on components/Buttons/JFButtons.brs
> +            return true
Should return false so proper sfx plays.
```suggestion
            return false
```

2023-02-11 00:39 UTC, 1hitsong commented on components/Buttons/JFButtons.brs
> +            return true
Should return false so proper sfx plays.
```suggestion
            return false
```

2023-02-11 00:39 UTC, 1hitsong commented on components/ItemGrid/MovieLibraryView.brs
> +    else if m.options.layout = "grid" or m.layout = "grid"
We should be forcing a case on these string comparisons. LCase()

2023-02-11 00:52 UTC, sevenrats commented on components/data/MovieData.brs
> +        else if isValid(m.top.json.BackdropImageTags)
it will need to be two lines then because the reason I changed it was for attempting to perform array operations on an invalid object.

2023-02-11 00:54 UTC, sevenrats commented on components/ItemGrid/MovieLibraryView.brs
> +    else if m.options.layout = "grid" or m.layout = "grid"
i believe you. can you help me understand why we are forcing cases like this though?  Im familiar with doing this on user inputs, but, why would we not just insist that devs enter the values correctly?

2023-02-11 01:18 UTC, 1hitsong commented on components/ItemGrid/MovieLibraryView.brs
> +    else if m.options.layout = "grid" or m.layout = "grid"
Because it's such an easy thing to fall through the cracks. If we had access to `Enum` in brightscript it wouldn't be an issue. But alas...

2023-02-11 01:20 UTC, 1hitsong commented on components/data/MovieData.brs
> +        else if isValid(m.top.json.BackdropImageTags)
I believe brightscript reads left to right and stops on failure, so I think combining with `and` would work.

`isValid(m.top.json.BackdropImageTags) and isValid(m.top.json.BackdropImageTags[0])`

2023-09-11 21:30 UTC, cewert commented
@sevenrats Are you still working on this? It's been ~7 months without any updates and there are still review comments that didn't get addressed.

2023-09-11 21:34 UTC, sevenrats commented
lol i 1hitsong was makeing new views at the speed of light last time i tried this. I will come back around to it again but there is no reason we can't close for now.

2023-09-11 21:34 UTC, closed without merging