Change subtitle renderer from Roku embedded to a custom task
jellyfin-archive/jellyfin-roku-legacy pull request #982
Opened 2023-01-27 00:16 UTC by jkim2492

**Changes**

Disables Roku's global captions and uses JFVideo labels to render captions
**Issues**

Related to issue #514

2023-01-27 01:16 UTC, sevenrats commented
This is very cool but you have to download the fonts from somewhere at runtime.  Roku will not publish any app over 4 mb.

2023-01-27 01:35 UTC, 1hitsong requested changes

2023-01-27 01:35 UTC, 1hitsong commented on components/captionTask.brs
> +    if m.top.playerState = "playing" then
m.top.playerState value never changes, it's always "shopped"

This prevents subtitles from every being shown.

2023-01-27 01:35 UTC, 1hitsong commented on components/JFVideo.brs
> +    m.captionGroup.appendChildren(m.captionTask.currentCaption)
The label is getting appended, but the height and width are both 0, so the captions aren't being displayed.

2023-01-27 01:35 UTC, 1hitsong commented on components/captionTask.brs
> +        m.top.currentPos = m.top.currentPos + 100
The captions always start at the beginning. If you resume a video, the captions don't begin where the video does.

2023-01-27 01:35 UTC, 1hitsong commented on components/captionTask.brs
> +        m.top.currentPos = m.top.currentPos + 100
The captions continue moving even if the video is paused.

2023-01-27 01:35 UTC, 1hitsong commented on components/captionTask.brs
> +        m.top.currentPos = m.top.currentPos + 100
If the user fast forwards or rewinds the video, the captions don't adjust to follow them. They continue regardless of the updated video position.

2023-01-27 01:37 UTC, 1hitsong commented
We should honor a user's closed captioning styles as set in the Roku global captionStyle: https://developer.roku.com/docs/references/scenegraph/media-playback-nodes/video.md#closed-caption-fields

2023-01-27 01:39 UTC, 1hitsong commented
We can't include the font files, just 1 of them is larger than our max allowed app size.

But, the API does provide us a method to transfer fonts from the server over to the client and store them in a temp folder.

https://api.jellyfin.org/#tag/Subtitle/operation/GetFallbackFont

2023-01-27 01:39 UTC, 1hitsong commented
That's all my notes for the first pass. Very cool enhancement!

2023-01-27 02:01 UTC, jkim2492 commented on components/captionTask.brs
> +        m.top.currentPos = m.top.currentPos + 100
These things were working when I was testing but I must've messed up while copying them over. Let me check!

2023-01-27 02:40 UTC, jkim2492 commented on components/captionTask.brs
> +        m.top.currentPos = m.top.currentPos + 100
All of the issues should be solved now. I've moved the fonts folder to /components so that it would be included in the build with default settings

2023-01-27 03:01 UTC, jkim2492 commented
> We can't include the font files, just 1 of them is larger than our max allowed app size.
> 
> But, the API does provide us a method to transfer fonts from the server over to the client and store them in a temp folder.
> 
> https://api.jellyfin.org/#tag/Subtitle/operation/GetFallbackFont

This is great! I had considered downloading it from the web on boot but this would be more bandwidth friendly

2023-01-27 03:04 UTC, jkim2492 commented
> We should honor a user's closed captioning styles as set in the Roku global captionStyle: https://developer.roku.com/docs/references/scenegraph/media-playback-nodes/video.md#closed-caption-fields
Yup, I'm thinking about doing it alongside srt tag support using MultiStyleLabel

2023-01-27 19:49 UTC, sevenrats commented
Is it possible to change the position of the labels?  If so, it would be nice to eventually extend this for full ssa/ass support as well.

2023-01-28 03:02 UTC, jkim2492 commented
Ya it shouldn't be too hard. As it is, jellyfin server seems to convert SRT
to VTT before sending it to client. I'm not sure if that's the case for ASS
as well

On Fri, 27 Jan 2023, 14:49 Austin Crandall, ***@***.***>
wrote:

> Is it possible to change the position of the labels? If so, it would be
> nice to eventually extend this for full ssa/ass support as well.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/982#issuecomment-1407002729>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM7RJUET7YCL2MJ5VNOQVA3WUQRFBANCNFSM6AAAAAAUIDPQPE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-01-28 04:34 UTC, Lorde627 commented
We stan!

2023-02-02 02:12 UTC, 1hitsong commented
By default subtitles are off. I selected a movie and selected a subtitle language, but it didn't turn subtitles on. I had to go into Roku settings to enable them.

2023-02-02 02:28 UTC, 1hitsong commented
When both global subtitles and new subtitles are enabled, they overlap.

![image](https://user-images.githubusercontent.com/3330318/216216284-e0b2c5c2-f2c6-41ca-ac92-fac39a4f83a8.png)

2023-02-02 02:32 UTC, 1hitsong commented
We should clear the displayed subtitle when the track changes. When I changed tracks it kept the original one until it updated several seconds later.

2023-02-02 03:24 UTC, jkim2492 commented
> When both global subtitles and new subtitles are enabled, they overlap.
> 
> ![image](https://user-images.githubusercontent.com/3330318/216216284-e0b2c5c2-f2c6-41ca-ac92-fac39a4f83a8.png)



> We should clear the displayed subtitle when the track changes. When I changed tracks it kept the original one until it updated several seconds later.

Both should be solved now!

2023-02-02 06:59 UTC, jkim2492 commented
> We should clear the displayed subtitle when the track changes. When I changed tracks it kept the original one until it updated several seconds later.

The subtitles should clear instantly now. Subtitle visibility will now follow Roku's settings and will not overlap i.e. if Roku settings is always on, it will be always on

2023-02-02 07:11 UTC, Lorde627 commented
Merge! Merge! Merge!

2023-02-02 22:59 UTC, 1hitsong commented
Do you mind changing the name of your branch? It's causing git to act very funky due to your feature branch also being named unstable.

2023-02-02 23:04 UTC, 1hitsong commented
Play movie, subtitles showing
Press Back
Play movie again, no subtitles

Console error: `*** ERROR: Missing or invalid PHY: 'noto.otf'`

After several seconds, subtitles show

2023-02-02 23:05 UTC, 1hitsong commented
If you click on a movie you've already watched part of and from the resume popup select `Resume from %time%` the subtitles start from the beginning and not from the resume point.

2023-02-03 00:36 UTC, jkim2492 commented
> Do you mind changing the name of your feature branch? It's causing git to act very funky due to your feature branch also being named unstable.

I've tried this but it resulted in this PR closing. It seems like github doesn't support changing the target branch at the moment

2023-02-03 00:36 UTC, jkim2492 commented
> Play movie, subtitles showing Press Back Play movie again, no subtitles
> 
> Console error: `*** ERROR: Missing or invalid PHY: 'noto.otf'`
> 
> After several seconds, subtitles show

This should be fixed now

2023-02-03 00:37 UTC, jkim2492 commented
> If you click on a movie you've already watched part of and from the resume popup select `Resume from %time%` the subtitles start from the beginning and not from the resume point.

I haven't been able to reproduce this issue. Perhaps it was linked to the invalid PHY error

2023-02-03 01:39 UTC, 1hitsong commented
Confirmed, missing file error is fixed.

It didn't fix my other issue. Scrubbing through the video doesn't advance subtitles to new time point, and resuming always starts subtitles back at beginning.

https://user-images.githubusercontent.com/3330318/216490771-9ab991f0-4ffb-4254-a5f3-eb1471a0218d.mp4

2023-02-03 03:50 UTC, jkim2492 commented
> Confirmed, missing file error is fixed.
> 
> It didn't fix my other issue. Scrubbing through the video doesn't advance subtitles to new time point, and resuming always starts subtitles back at beginning.
> 
>  Subtitle.mp4

Aha! Problem was JFVideo not observing position for non-episode videos. I've adjusted and will also test movies as well in the future! Seeking / resuming should work now

2023-02-03 23:03 UTC, 1hitsong commented
Much better! I do think we need to use the Roku global subtitle styles for 1st release. Since that's what we currently use with the subtitles, people will complain if it suddenly changes and styles are gone.

I noticed a pause of several seconds when I started playback. I assume it's due to the font file transfer. Instead of transferring on playback start, can we asynchronously transfer the file starting on client startup within main.brs?

2023-02-04 18:10 UTC, jkim2492 commented
I've moved the font download to Main.brs, let me know if it's better. I fear that it wasn't the font download but subtitle parsing that was bottlenecking. When tested with larger subtitles, it look around ~3s longer than using global subs. It seems like string functions are a _lot_ slower than I had expected

2023-02-04 21:22 UTC, 1hitsong requested changes

2023-02-04 21:22 UTC, 1hitsong commented on components/captionTask.brs
> +            entry = { "start": curStart, "end": curEnd, "text": lines[i].trim() }
This line threw an error and crashed the Roku.

`Use of uninitialized variable. (runtime error &he9) in pkg:/components/captionTask.brs(130)`

2023-02-04 21:22 UTC, 1hitsong commented on source/Main.brs
> +        APIRequest("FallbackFont/Fonts/" + filename).gettofile("tmp:/font" + ext)
Instead of `gettofile()` can we use `AsyncGetToFile()`?

2023-02-04 21:57 UTC, jkim2492 commented on source/Main.brs
> +        APIRequest("FallbackFont/Fonts/" + filename).gettofile("tmp:/font" + ext)
Both should be fixed now!

2023-02-04 22:42 UTC, 1hitsong commented
Went to play a movie and it crashed again.

![image](https://user-images.githubusercontent.com/3330318/216792529-d5ebfc8b-2573-41ba-a2aa-0ceb4f6b15f2.png)

2023-02-06 15:13 UTC, jkim2492 commented
> Much better! I do think we need to use the Roku global subtitle styles for 1st release. Since that's what we currently use with the subtitles, people will complain if it suddenly changes and styles are gone.
> 
> I noticed a pause of several seconds when I started playback. I assume it's due to the font file transfer. Instead of transferring on playback start, can we asynchronously transfer the file starting on client startup within main.brs?

For now, I've changed it so that the new subtitles are applied only if the user has a fallback font

2023-02-06 15:17 UTC, jkim2492 commented
> Went to play a movie and it crashed again. Line 25.
> 
> ![image](https://user-images.githubusercontent.com/3330318/216792529-d5ebfc8b-2573-41ba-a2aa-0ceb4f6b15f2.png)

This should be fixed now. However, I've noticed a new problem with subtitle sync : video.position field is correct at time 0 but gradually drifts to around +2s around 20 min mark. I suspect that it could be a problem with my roku device since the problem persists with global subtitles

2023-02-06 15:20 UTC, jkim2492 commented on source/Main.brs
> +        APIRequest("FallbackFont/Fonts/" + filename).gettofile("tmp:/font" + ext)
> Instead of `gettofile()` can we use `AsyncGetToFile()`?

Does booting take a long time with "gettofile()"? I've changed it back to "gettofile()" for now since

- On async, I've waited for a minute after boot and checked for file but it wasn't downloaded
- I think gettofile will be more convenient for possible future enhancements with changing gui fonts

2023-02-06 15:29 UTC, jkim2492 commented
> Much better! I do think we need to use the Roku global subtitle styles for 1st release. Since that's what we currently use with the subtitles, people will complain if it suddenly changes and styles are gone.
> 
> I noticed a pause of several seconds when I started playback. I assume it's due to the font file transfer. Instead of transferring on playback start, can we asynchronously transfer the file starting on client startup within main.brs?

As for the captionStyle, implementing

- Text/Size
- Text/Color
- Text/Opacity
- Background/Color : as outline color
- Background/Opacity : as outline opacity

should be straightforward but I'm not too sure on the other ones. Any suggestions?

2023-02-07 21:42 UTC, 1hitsong commented
"Text/Effect" simply isn't available on labels. I say we ignore it for now and perhaps in a follow up PR was can evaluate methods to fake the various effects.

2023-02-07 23:40 UTC, jkim2492 commented
> Much better! I do think we need to use the Roku global subtitle styles for 1st release. Since that's what we currently use with the subtitles, people will complain if it suddenly changes and styles are gone.
> 


Alright! captionStyle has been implemented

2023-02-08 02:10 UTC, 1hitsong commented
I played around the the settings some and got an outcome that wasn't what I expected, but might prove helping in faking the "Text/Effect" property.

Here's what I was expecting to see based on my Roku settings
![image](https://user-images.githubusercontent.com/3330318/217410754-de58be10-355d-4f35-8e48-c46255f8b57f.png)

Here's what I saw in Jellyfin
![image](https://user-images.githubusercontent.com/3330318/217410780-03ec79d5-ce8c-414f-a248-28556e02fbe5.png)

2023-02-08 02:16 UTC, jkim2492 commented
The "effect" is present with the default settings as well I think. It's just more visible with modified settings. I'm not quite sure how to fix it at the moment since it shouldn't be like that with proper rendering

2023-02-08 02:47 UTC, 1hitsong commented
What if we drop use of background color and opacity and instead support window color and opacity?

That would mean we support the rectangle "window" around the lines of text, and the text itself. The Background settings, which are an odd background-within-a-background setting to begin with, we ignore.

2023-02-08 21:37 UTC, jkim2492 commented
> What if we drop use of background color and opacity and instead support window color and opacity?
> 
> That would mean we support the rectangle "window" around the lines of text, and the text itself. The Background settings, which are an odd background-within-a-background setting to begin with, we ignore.

Perhaps we can implement both : window settings for the rectangle and background settings for the outline (or vice versa)

2023-02-08 21:57 UTC, 1hitsong commented
I suppose it's worth a shot, but at least on my Roku, that text outline looks bad.

2023-02-08 22:15 UTC, jkim2492 commented
Hm in that case we can hold back on the outlines until a solution is found

2023년 2월 8일 (수) 오후 4:57, 1hitsong ***@***.***>님이 작성:

> I suppose it's worth a shot, but at least on my Roku, that text outline
> looks bad.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jellyfin/jellyfin-roku/pull/982#issuecomment-1423291103>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AM7RJUELHYVSRQ3PSKZHG7TWWQJDVANCNFSM6AAAAAAUIDPQPE>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-02-10 17:20 UTC, jkim2492 commented
We are using background rectangles instead of outlines now. They can be adjusted with Background/* settings

2023-02-10 21:44 UTC, 1hitsong commented
Is the expectation for this PR that this only work for external subtitle files, or should this work for subtitles that are part of the video file as well?

I ask because it works for my videos with external files, but the files with encoded subtitles get the "old" build-in subtitle render that don't support the CJK font.

2023-02-12 05:11 UTC, jkim2492 commented
> Is the expectation for this PR that this only work for external subtitle files, or should this work for subtitles that are part of the video file as well?
> 
> I ask because it works for my videos with external files, but the files with encoded subtitles get the "old" build-in subtitle render that don't support the CJK font.

The intent was to make it for external files only but we can probably handle encoded ones in a separate PR later!

2023-02-12 11:59 UTC, 1hitsong commented
> we can probably handle encoded ones in a separate PR later!

Excellent. Cuts my testing in half! 

I hope to have functional testing completed tonight and will do a code review pass after that.

2023-02-18 19:13 UTC, 1hitsong commented
Functionality works great! Here are some updates we need to make for users.

1. The fallback font API endpoint will always return any fonts, even if fallback fonts are disabled. We should only grab a fallback font if fallback fonts are enabled on the server

![image](https://user-images.githubusercontent.com/3330318/219883879-6e882f70-77a7-47d8-9d51-dab80da2054f.png)

2. This is an awesome update, but there **_WILL_** be people who complain we're not using the Roku default function. Can you add a user setting that allows users to opt-in to use custom subtitle functionality instead of default?

2023-02-18 19:28 UTC, 1hitsong requested changes

2023-02-18 19:28 UTC, 1hitsong commented on components/JFVideo.brs
> +    if m.top.globalCaptionMode = "On"
```suggestion
    if LCase(m.top.globalCaptionMode) = "on"
```
String comparisons should always force a case.

2023-02-18 19:28 UTC, 1hitsong commented on components/JFVideo.brs
> +    while m.captionGroup.removeChildIndex(0)
Instead of using a while loop to remove all the children, could we use the removechildrenindex function?

`m.captionGroup.removeChildrenIndex(m.captionGroup.getChildCount(), 0)`

2023-02-18 19:28 UTC, 1hitsong commented on components/JFVideo.brs
> +    ' if m.top.content.contenttype <> 4
Commented out code should just be removed

2023-02-18 19:28 UTC, 1hitsong commented on components/JFVideo.brs
> +    if m.top.content.contenttype = 4
Instead of nesting this clause, let's just escape early.

At the top of showNextEpisodeButton() do `if m.top.content.contenttype <> 4 then return`

2023-02-18 19:28 UTC, 1hitsong commented on components/JFVideo.brs
> +    if m.top.content.contenttype = 4
Same as above. Let's exit early.

`if m.top.content.contenttype <> 4 then return`

2023-02-18 19:28 UTC, 1hitsong commented on components/JFVideo.brs
> -    ' Check if dialog is open
Let's keep this comment, just move 1 line down so it's below your captaintask code.

2023-02-18 19:28 UTC, 1hitsong commented on components/captionTask.brs
> +        ?url
Debug code

2023-02-18 19:28 UTC, 1hitsong commented on components/captionTask.brs
> +function newlabel(txt):
```suggestion
function newlabel(txt)
```

2023-02-18 19:28 UTC, 1hitsong commented on components/captionTask.brs
> +    if m.top.playerState = "playingOn"
```suggestion
    if LCase(m.top.playerState) = "playingon"
```
String comparisons should force case

2023-02-18 19:28 UTC, 1hitsong commented on components/captionTask.brs
> +    else if right(m.top.playerState, 4) = "Wait"
```suggestion
    else if LCase(right(m.top.playerState, 4)) = "wait"
```

2023-02-18 19:28 UTC, 1hitsong commented on source/utils/Subtitles.brs
> +        ?"Check2"
Debug code

2023-02-18 19:28 UTC, 1hitsong commented on source/utils/Subtitles.brs
> +    ?"Check3"
Debug code

2023-02-19 18:33 UTC, jkim2492 commented
> Functionality works great! Here are some updates we need to make for users.
> 
> 1. The fallback font API endpoint will always return any fonts, even if fallback fonts are disabled. We should only grab a fallback font if fallback fonts are enabled on the server
> 
> ![image](https://user-images.githubusercontent.com/3330318/219883879-6e882f70-77a7-47d8-9d51-dab80da2054f.png)
> 
> 2. This is an awesome update, but there **_WILL_** be people who complain we're not using the Roku default function. Can you add a user setting that allows users to opt-in to use custom subtitle functionality instead of default?

This and all of the change requests should be fixed now. Hope there aren't new bugs!

2023-02-19 20:28 UTC, 1hitsong requested changes

2023-02-19 20:28 UTC, 1hitsong commented on settings/settings.json
> +                "title": "Use Custom Subtitles",
title: Custom Subtitles
description: Replace Roku's default subtitle functions with custom functions that support CJK fonts. Fallback fonts must be configured and enabled on the server for CJK rendering to work.

Move this setting above Text Sustitles Only.

Add title and description to translation file so it can be translated for users who don't use English: locale\en_US\translations.ts

2023-02-19 20:29 UTC, 1hitsong commented on settings/settings.json
> +                "title": "Use Custom Subtitles",
Everything worked great! Amazing job! 1 last bit of housekeeping in the settings and translations and this is great to go!

2023-02-20 22:39 UTC, jkim2492 commented on settings/settings.json
> +                "title": "Use Custom Subtitles",
Done!

2023-02-21 01:54 UTC, 1hitsong commented
@jkim2492 Double check the translations file. Github shows the entire file as modified.

2023-02-21 02:45 UTC, jkim2492 commented
@1hitsong Seems the line endings had changed for some reason. It should correctly show diffs now

2023-02-21 13:41 UTC, 1hitsong approved these changes

2023-02-21 13:45 UTC, 1hitsong commented
@jkim2492 Approved. Can you resolve the merge conflicts?

2023-02-21 17:44 UTC, jkim2492 commented
@1hitsong Yup it should be good now

2023-02-21 17:53 UTC, merged

2023-02-21 17:54 UTC, 1hitsong commented
Merged. For the follow up, please use a different name for the branch 😉

2023-03-03 22:26 UTC, depctg commented
> Is it possible to change the position of the labels? If so, it would be nice to eventually extend this for full ssa/ass support as well.

As a follow up simple ass support is implemented in #1075