make title scrolling consistent in extras slider
jellyfin-archive/jellyfin-roku-legacy pull request #999
Opened 2023-01-31 17:28 UTC by sevenrats

only scroll name labels in the extras slider if they have focus.  this is more consistent and more visually appropriate.

**Changes**
only scroll pLabel in ExtrasItem if it has focus.

2023-02-06 03:22 UTC, candry7731 commented on components/extras/ExtrasItem.xml
>        <Label id="SubTitle" horizAlign="center" vertAlign="center" font="font:SmallestBoldSystemFont" height="32" color="#A7A7A7FF"  />
should make this a scrolling label also as this is the characters title and is almost always cutoff 
```suggestion
            <ScrollingLabel id="SubTitle" horizAlign="center" vertAlign="center" font="font:SmallestBoldSystemFont" maxWidth="246" height="32" color="#A7A7A7FF" repeatCount="0"  />
  />
```

2023-02-06 03:23 UTC, candry7731 commented on components/extras/ExtrasItem.brs
> +        m.name.repeatCount = -1
need to make the scroll work for the role text
```suggestion
        m.name.repeatCount = -1
        m.role.repeatCount = -1
```

2023-02-06 03:23 UTC, candry7731 commented on components/extras/ExtrasItem.brs
> +        m.name.repeatCount = 0
same

```suggestion
        m.name.repeatCount = 0
        m.role.repeatCount = 0

```

2023-02-10 22:25 UTC, 1hitsong requested changes

2023-02-10 22:25 UTC, 1hitsong commented on components/extras/ExtrasItem.xml
> +      <ScrollingLabel id="SubTitle"
The change of this from a `label` to a `scrollinglabel` causes this warning to be logged.

```
=================================================================
Warning occurred while setting a field of an RoSGNode
-- Tried to set nonexistent field "width" of a "ScrollingLabel" node
pkg:/components/extras/ExtrasItem.brs(14)
=================================================================
```

2023-02-11 20:26 UTC, 1hitsong approved these changes
To be merged 2/12 unless an issue arises.

2023-02-12 12:01 UTC, merged